import type { Activity } from "./types";

/* Science NCERT-style activity lab — original step write-ups with inline SVG art.
   Key: chapterKey ("<subject>-<group>-<chapter>", 0-based). */
export const ACTIVITIES: Record<string, Activity[]> = {
 "science-0-0": [
  { title: "Magnesium ribbon burning", aim: "Observe a combination reaction and the nature of the product.", art: "heating",
   steps: ["Clean a 3-4 cm magnesium ribbon with sandpaper.", "Hold it with tongs and heat over a flame.", "Collect the white ash formed on a watch glass."],
   observe: "A dazzling white flame; white powder (magnesium oxide) forms.", conclusion: "Magnesium combines with oxygen — a combination reaction: 2Mg + O2 -> 2MgO." },
  { title: "Zinc + dilute sulphuric acid", aim: "See a displacement reaction with gas evolution.", art: "acid",
   steps: ["Add zinc granules to dilute H2SO4 in a test tube.", "Note the bubbles on the zinc surface.", "Touch the test tube base to feel temperature."],
   observe: "Bubbles of gas; the tube becomes warm.", conclusion: "Zn displaces hydrogen: Zn + H2SO4 -> ZnSO4 + H2 (heat is released)." },
 ],
 "science-0-1": [
  { title: "Litmus with acids and bases", aim: "Test colour changes of indicators.", art: "acid",
   steps: ["Put dilute HCl in one tube, NaOH solution in another.", "Touch blue and red litmus papers to each.", "Record the colour changes."],
   observe: "Acid turns blue litmus red; base turns red litmus blue.", conclusion: "Indicators distinguish acids from bases." },
  { title: "Neutralisation with temperature rise", aim: "Show that acid + base gives salt + water with heat.", art: "heating",
   steps: ["Take dilute NaOH in a tube.", "Add dilute HCl drop by drop while shaking.", "Feel the base of the tube."],
   observe: "The tube warms up as the solution neutralises.", conclusion: "Neutralisation is exothermic: NaOH + HCl -> NaCl + H2O." },
 ],
 "science-0-2": [
  { title: "Reactivity of metals with water", aim: "Compare Na, Mg, Fe reactivity.", art: "flask",
   steps: ["Drop sodium (pea-sized, teacher demo) in cold water.", "Put magnesium in warm water, iron in steam.", "Compare the vigour of reaction."],
   observe: "Na reacts violently; Mg slowly with hot water; Fe only with steam.", conclusion: "Reactivity order Na > Mg > Fe — the basis of the reactivity series." },
  { title: "Displacement: iron nail in copper sulphate", aim: "Show a more reactive metal displaces a less reactive one.", art: "acid",
   steps: ["Dip a clean iron nail in CuSO4 solution.", "Leave for 20 minutes.", "Compare the solution colour and nail coating."],
   observe: "Blue solution turns pale green; reddish-brown coating on nail.", conclusion: "Fe + CuSO4 -> FeSO4 + Cu; iron is above copper in the series." },
 ],
 "science-0-3": [
  { title: "Soap vs detergent in hard water", aim: "Compare cleansing action and scum formation.", art: "flask",
   steps: ["Take two tubes with the same hard water.", "Add soap to one, detergent to the other.", "Shake both and note the foam."],
   observe: "Soap forms scum and less foam; detergent foams well.", conclusion: "Soap reacts with Ca/Mg ions; detergents work in hard water." },
  { title: "Ethanol combustion", aim: "Observe a clean-burning carbon compound.", art: "heating",
   steps: ["Put 1 mL ethanol on a watch glass (teacher demo).", "Ignite with a splint.", "Note flame colour and residue."],
   observe: "Clean blue flame, no residue.", conclusion: "Alcohols burn completely: C2H5OH + 3O2 -> 2CO2 + 3H2O." },
 ],
 "science-0-4": [
  { title: "Starch test on a destarched leaf", aim: "Prove sunlight is needed for photosynthesis.", art: "leaf",
   steps: ["Cover part of a leaf with black paper and expose to sun for a day.", "Boil the leaf in water, then in alcohol to remove chlorophyll.", "Wash and add iodine solution."],
   observe: "Uncovered part turns blue-black; covered part stays brown.", conclusion: "Starch forms only where light reached — light is essential for photosynthesis." },
  { title: "CO2 is necessary for photosynthesis", aim: "Show carbon dioxide's role using KOH.", art: "plant",
   steps: ["Place a KOH pot inside a sealed bag over one potted plant's branch.", "Keep another plant as control in sunlight.", "After a day, test both leaves for starch."],
   observe: "Leaf without CO2 shows no starch; control shows starch.", conclusion: "CO2 is a raw material of photosynthesis." },
 ],
 "science-0-5": [
  { title: "Knee-jerk style reflex demonstration", aim: "Trace the reflex arc pathway.", art: "reflex",
   steps: ["Touch a hot (not burning) object briefly and note the instant withdrawal.", "Discuss the path: receptor -> sensory nerve -> spinal cord -> motor nerve -> muscle.", "Compare with a slow, deliberate movement."],
   observe: "Withdrawal is instant and involuntary.", conclusion: "Reflexes bypass the brain for speed — the spinal cord is the centre." },
  { title: "Tropism in plants", aim: "Observe phototropism with a potted plant.", art: "plant",
   steps: ["Keep a potted plant near a window for 3 days.", "Note the direction of shoot bending.", "Rotate the pot 180 degrees and re-observe after 2 days."],
   observe: "Shoot bends towards light each time.", conclusion: "Auxin redistribution causes growth towards light (positive phototropism)." },
 ],
 "science-0-6": [
  { title: "Budding in Hydra (slide/-chart study)", aim: "See asexual reproduction by budding.", art: "flask",
   steps: ["Study a prepared slide or chart of Hydra.", "Locate the bud and its point of attachment.", "Compare bud size across stages."],
   observe: "A small outgrowth develops into a new individual.", conclusion: "Budding gives genetically identical offspring without gametes." },
  { title: "Seed germination on wet cotton", aim: "Observe sexual reproduction beginning in plants.", art: "plant",
   steps: ["Soak bean seeds overnight.", "Place them on wet cotton for 3-4 days.", "Measure root and shoot growth daily."],
   observe: "Radicle appears first, then plumule.", conclusion: "The embryo in the seed grows into a new plant on germination." },
 ],
 "science-0-7": [
  { title: "Mendel's pea cross (model)", aim: "Derive the 3:1 ratio in F2 with a paper model.", art: "grid",
   steps: ["Use T (tall) and t (dwarf) cards to cross TT x tt.", "Write the F1 (all Tt) and self it: Tt x Tt.", "Fill a 2x2 Punnett square and count phenotypes."],
   observe: "F2 shows TT, Tt, Tt, tt — three tall, one dwarf.", conclusion: "Dominant and recessive traits segregate in a 3:1 ratio." },
  { title: "Sex determination chance game", aim: "Model why births are ~50:50 male:female.", art: "dice",
   steps: ["Take cards X, X (mother) and X, Y (father).", "Draw one from each repeatedly (30 trials).", "Tally XX vs XY outcomes."],
   observe: "XX and XY appear in roughly equal numbers.", conclusion: "The sperm (X or Y) decides sex, with equal probability." },
 ],
 "science-0-8": [
  { title: "Image formation by a concave mirror", aim: "Map object positions to image nature.", art: "light",
   steps: ["Find the mirror's approximate focal length using a distant window.", "Place a candle beyond C, at C, between F and P.", "Note image size, position and nature on a screen."],
   observe: "Beyond C: diminished real; at C: same size; near P: enlarged virtual.", conclusion: "Image nature changes predictably with object position." },
  { title: "Refraction through a glass slab", aim: "Show bending and lateral displacement.", art: "light",
   steps: ["Fix a white sheet and place a glass slab on it.", "Mark pins P1, P2 and their images through the slab.", "Draw the ray path and remove the slab."],
   observe: "The emergent ray is parallel to the incident ray but shifted.", conclusion: "Light bends towards the normal entering glass, away on exit; equal bending gives parallel shift." },
 ],
 "science-0-9": [
  { title: "Near point and far point test", aim: "Measure your eye's comfortable range.", art: "eye",
   steps: ["Bring a printed page closer until it blurs — note the distance (near point).", "Read a distant board clearly (far point).", "Compare with the normal 25 cm near point."],
   observe: "Most students read clearly from ~25 cm to far away.", conclusion: "The eye lens adjusts its focal length — accommodation." },
  { title: "Dispersion with a prism", aim: "Split white light into its spectrum.", art: "light",
   steps: ["Let a narrow sunbeam enter a dark room through a slit.", "Pass it through a glass prism onto a white wall.", "Note the colour order."],
   observe: "A band VIBGYOR appears; violet bends most.", conclusion: "White light is a mixture of seven colours; refraction angles differ." },
 ],
 "science-0-10": [
  { title: "Ohm's law with a nichrome wire", aim: "Show V is proportional to I.", art: "circuit",
   steps: ["Connect a nichrome wire, ammeter, key and 1 cell; note I.", "Repeat with 2, 3, 4 cells in series; note V and I each time.", "Plot V against I."],
   observe: "V/I stays nearly constant; the graph is a straight line.", conclusion: "V = IR; the constant slope is the wire's resistance." },
  { title: "Series vs parallel lamps", aim: "Compare brightness and independence.", art: "circuit",
   steps: ["Connect two bulbs in series with a cell; note brightness.", "Reconnect them in parallel; note brightness.", "Unscrew one bulb in each case."],
   observe: "Parallel bulbs glow brighter; one removal doesn't kill the other.", conclusion: "Homes use parallel wiring so appliances work independently at full voltage." },
 ],
 "science-0-11": [
  { title: "Magnetic field of a bar magnet with iron filings", aim: "Visualise field lines.", art: "magnet",
   steps: ["Fix a white sheet; place a bar magnet at the centre.", "Sprinkle iron filings evenly; tap gently.", "Trace the pattern formed."],
   observe: "Filings align in curved lines from N to S; dense near poles.", conclusion: "The field is strongest at the poles; lines never cross." },
  { title: "Electromagnet strength", aim: "See how coil turns affect magnetism.", art: "circuit",
   steps: ["Wind 20 turns of wire on an iron nail; connect to a cell.", "Count pins attracted.", "Increase to 40 turns; compare."],
   observe: "More turns attract more pins.", conclusion: "Electromagnet strength grows with turns and current." },
 ],
 "science-0-12": [
  { title: "10% energy transfer model", aim: "Model energy loss across trophic levels.", art: "grid",
   steps: ["Take 100 paper units as producer energy.", "Pass 10% to herbivores, 10% of that to carnivores.", "Compare available units at each level."],
   observe: "Top level receives only 1 unit.", conclusion: "Energy pyramids explain why food chains stay short." },
  { title: "Biodegradable vs non-biodegradable", aim: "Classify waste by decomposition.", art: "leaf",
   steps: ["Bury peels, paper, plastic and glass in moist soil pots.", "Observe after 3 weeks.", "Record which materials changed."],
   observe: "Peels and paper decompose; plastic and glass remain.", conclusion: "Microbes break down only biodegradable matter — segregate waste." },
 ],
};
