/* AI Half Yearly - objective practice bank, Part B Unit 2 (Modelling) + Unit 3 (Evaluating Model). */
import type { AiObqItem } from "./aiHyTypes";

export const AI_HY_OBQ_C: AiObqItem[] = [
  { q: "In AI, a model is built from:", o: ["an algorithm plus data", "hardware only", "a printer", "a spreadsheet only"], a: 0, why: "The algorithm learns from the data to give the model." },
  { q: "A rule-based model works on:", o: ["fixed if-then rules", "learning from data", "rewards and penalties", "clustering"], a: 0, why: "The programmer writes every rule; the machine does not learn." },
  { q: "Labelled data is used in:", o: ["supervised learning", "unsupervised learning", "reinforcement learning", "rule-based systems"], a: 0, why: "The correct answers (labels) guide the training." },
  { q: "Predicting marks from the number of study hours is an example of:", o: ["regression", "classification", "clustering", "reward learning"], a: 0, why: "The output is a number, so it is regression." },
  { q: "Deciding whether a mail is spam or not spam is an example of:", o: ["classification", "regression", "clustering", "sorting"], a: 0, why: "The output is a category, not a number." },
  { q: "K-means is an algorithm used for:", o: ["clustering", "classification", "regression", "rule writing"], a: 0, why: "It groups similar unlabelled data points." },
  { q: "In a decision tree, the topmost node is called the:", o: ["root node", "leaf node", "branch", "child"], a: 0, why: "The first question asked sits at the root." },
  { q: "In a decision tree, the final answers are found at the:", o: ["leaves", "root", "edges", "top"], a: 0, why: "Leaf nodes carry the classification or value." },
  { q: "KNN predicts the class of a new point by:", o: ["the majority vote of its nearest neighbours", "a random guess", "fixed rules", "deleting old data"], a: 0, why: "K nearest neighbours vote for the new point's class." },
  { q: "In KNN, the value of k is usually kept:", o: ["odd", "very large", "zero", "negative"], a: 0, why: "An odd k avoids a tie in the vote." },
  { q: "The layers of an artificial neural network are:", o: ["input, hidden and output", "top, middle and bottom", "front and back", "only output"], a: 0, why: "Data enters the input layer and leaves from the output layer." },
  { q: "Weights in a neural network decide:", o: ["how strongly an input affects the output", "the file size", "the number of users", "the screen size"], a: 0, why: "Training adjusts the weights to reduce error." },
  { q: "Reinforcement learning learns through:", o: ["reward and penalty", "labelled examples", "clustering", "fixed if-then rules"], a: 0, why: "Good actions get rewards, wrong actions get penalties." },
  { q: "CNN (Convolutional Neural Network) is mainly used for:", o: ["image recognition", "printing documents", "storing files", "typing speed"], a: 0, why: "It is the backbone of computer vision tasks." },
  { q: "Assertion (A): A learning-based model can handle situations not covered by rules. Reason (R): It learns patterns from data instead of fixed instructions.", o: ["Both correct, R explains A", "Both correct, R does not explain A", "A correct, R incorrect", "A incorrect, R correct"], a: 0, why: "Learning from data is exactly why it goes beyond the rules." },
  { q: "A train-test split usually keeps:", o: ["70-80 % for training and 20-30 % for testing", "50 % each", "10 % training, 90 % testing", "100 % for testing"], a: 0, why: "Most data trains; a good part tests the model." },
  { q: "Testing data must be kept separate because:", o: ["the model must be checked on data it has never seen", "it trains faster", "it deletes extra data", "it increases marks"], a: 0, why: "Seen data can give a falsely high score." },
  { q: "Accuracy =", o: ["(TP + TN) / (TP + TN + FP + FN)", "TP / (TP + FP)", "TP / (TP + FN)", "2 x (P x R) / (P + R)"], a: 0, why: "It is all correct predictions divided by all predictions." },
  { q: "Recall =", o: ["TP / (TP + FN)", "TP / (TP + FP)", "(TP + TN) / total", "FP / (FP + TN)"], a: 0, why: "Recall measures how many real positives were caught." },
  { q: "The F1 score is the:", o: ["harmonic mean of precision and recall", "average of all accuracies", "sum of all errors", "difference of precision and recall"], a: 0, why: "It balances precision and recall in one number." },
  { q: "A model performs very well on training data but poorly on new data. This is:", o: ["overfitting", "underfitting", "good learning", "perfect evaluation"], a: 0, why: "It has memorised the training data instead of learning." },
  { q: "Underfitting means the model is:", o: ["too simple to learn the pattern", "memorising the data", "perfectly trained", "too large"], a: 0, why: "A simple model misses the real pattern of the data." },
  { q: "False Positive means:", o: ["the model predicted yes but the actual answer was no", "predicted no but actual was yes", "predicted correctly", "no prediction"], a: 0, why: "It is a false alarm." },
  { q: "False Negative means:", o: ["the model predicted no but the actual answer was yes", "predicted yes but actual was no", "predicted correctly", "no prediction"], a: 0, why: "It is a missed case - usually the costlier error." },
  { q: "For a disease-detection model, the most important metric is:", o: ["recall, so that no patient is missed", "only speed", "only file size", "only accuracy"], a: 0, why: "Missing a patient (FN) is the worst error there." },
  { q: "In a spam filter, a genuine mail landing in the spam folder is a:", o: ["false positive", "false negative", "true positive", "true negative"], a: 0, why: "The model said 'spam (yes)' but the truth was 'not spam'." },
  { q: "Which metrics are calculated from a confusion matrix?", o: ["accuracy, precision and recall", "only speed", "only memory used", "only accuracy"], a: 0, why: "TP, TN, FP and FN give all four evaluation metrics." },
  { q: "If a model makes 100 predictions and 90 are correct, its accuracy is:", o: ["90 %", "10 %", "100 %", "50 %"], a: 0, why: "Accuracy = correct / total x 100 = 90 %." },
  { q: "Model evaluation is which stage of the AI Project Cycle?", o: ["the last stage", "the first stage", "the second stage", "not a stage"], a: 0, why: "It closes the cycle before deployment." },
  { q: "Assertion (A): A model with 99 % accuracy can still be useless. Reason (R): On imbalanced data it may never catch the rare but important cases.", o: ["Both correct, R explains A", "Both correct, R does not explain A", "A correct, R incorrect", "A incorrect, R correct"], a: 0, why: "High accuracy hides a zero recall on the rare class." },
];
