/* AI Half Yearly - objective practice bank, ICT Skills + Part B Unit 1 (AI Project Cycle & Ethics). */
import type { AiObqItem } from "./aiHyTypes";

export const AI_HY_OBQ_B: AiObqItem[] = [
  { q: "Which of the following is an operating system?", o: ["Windows 10", "MS Word", "Google Chrome", "Photoshop"], a: 0, why: "An OS manages the whole computer; the rest are applications." },
  { q: "Which one is application software?", o: ["Windows 10", "MS Word", "Linux", "Android"], a: 1, why: "MS Word does a specific user task; the others are operating systems." },
  { q: "Ctrl + Z is used to:", o: ["undo the last action", "redo the last action", "zoom the page", "close the file"], a: 0, why: "Z undoes; it is the safest key in the exam hall." },
  { q: "Ctrl + V is used to:", o: ["cut", "copy", "paste", "print"], a: 2, why: "Ctrl + C copies, Ctrl + X cuts, Ctrl + V pastes." },
  { q: "A folder can:", o: ["hold files and sub-folders", "hold only one file", "not hold any file", "work as a printer"], a: 0, why: "Folders keep files organised, and can also hold sub-folders." },
  { q: "The extension .jpg tells you that the file is a/an:", o: ["image", "audio", "text", "video"], a: 0, why: "Extensions tell the file type: .mp3 audio, .mp4 video, .txt text." },
  { q: "Which of these is a search engine?", o: ["Google", "Windows", "MS Excel", "Gmail"], a: 0, why: "Search engines find information on the internet." },
  { q: "Which of these is a cloud storage service?", o: ["OneDrive", "Notepad", "Calculator", "MS Paint"], a: 0, why: "Cloud storage keeps files on internet servers." },
  { q: "A strong password should:", o: ["be your own name", "have 8 or more characters with letters, numbers and symbols", "be 123456", "be shared with friends"], a: 1, why: "Length plus mixed characters makes it hard to guess." },
  { q: "Phishing is:", o: ["catching fish in a pond", "fraud mails or sites that steal personal details", "an antivirus feature", "a file transfer method"], a: 1, why: "Never click on links in unknown mails asking for passwords." },
  { q: "Backup means:", o: ["deleting old files", "keeping a copy of data in another place", "formatting the hard disk", "hiding the files"], a: 1, why: "A backup saves the data when a device fails." },
  { q: "Which practice can spread a virus to your computer?", o: ["opening attachments from unknown mails", "updating the antivirus", "scanning a pen drive", "using licensed software"], a: 0, why: "Unknown attachments are a common carrier of malware." },
  { q: "Netiquette means:", o: ["internet etiquette - polite behaviour online", "a network cable", "an internet speed test", "a firewall"], a: 0, why: "It covers respectful language and behaviour on the internet." },
  { q: "Which one is NOT an ICT tool?", o: ["e-mail", "video conferencing", "spreadsheet", "hammer"], a: 3, why: "A hammer is a physical tool, not information technology." },
  { q: "Assertion (A): Cloud storage protects files from device damage. Reason (R): The files are saved on internet servers, not only on the device.", o: ["Both correct, R explains A", "Both correct, R does not explain A", "A correct, R incorrect", "A incorrect, R correct"], a: 0, why: "If the device breaks, the file still opens from the cloud." },
  { q: "AI stands for:", o: ["Artificial Intelligence", "Automatic Information", "Advanced Internet", "Applied Idea"], a: 0, why: "Machines that perform tasks needing human-like intelligence." },
  { q: "The correct order of the AI Project Cycle is:", o: ["Problem scoping, Data acquisition, Data exploration, Modelling, Evaluation", "Modelling, Problem scoping, Evaluation, Data acquisition, Data exploration", "Data acquisition, Modelling, Evaluation, Problem scoping, Data exploration", "Evaluation, Modelling, Data exploration, Data acquisition, Problem scoping"], a: 0, why: "Define the problem first, then data, then model, then check." },
  { q: "The 4Ws canvas stands for:", o: ["Who, What, Where, Why", "When, Which, Who, Why", "What, When, Where, Whom", "Who, When, Which, Why"], a: 0, why: "Problem scoping uses Who, What, Where and Why." },
  { q: "The problem statement template is prepared during:", o: ["problem scoping", "data exploration", "modelling", "evaluation"], a: 0, why: "It is the output of the problem scoping stage." },
  { q: "Data collected directly by the project team through a survey is:", o: ["primary data", "secondary data", "hidden data", "testing data"], a: 0, why: "Primary data is collected first-hand for the project." },
  { q: "Data taken from a government website or an old report is:", o: ["primary data", "secondary data", "live data", "training data"], a: 1, why: "Someone else collected it earlier - that makes it secondary." },
  { q: "Which of the following is unstructured data?", o: ["images, videos and audio", "a marks table", "a spreadsheet of names", "an attendance register"], a: 0, why: "Unstructured data has no fixed rows and columns." },
  { q: "Data exploration is done mainly to:", o: ["find patterns and outliers", "train the model", "collect the data", "deploy the model"], a: 0, why: "It prepares and studies the data before modelling." },
  { q: "An outlier is:", o: ["a value far away from the other values", "the average of all values", "the smallest value in the data", "a fault in the computer"], a: 0, why: "Outliers can spoil a model if not studied." },
  { q: "Machine Learning is a ______ of Artificial Intelligence.", o: ["subset", "superset", "synonym", "competitor"], a: 0, why: "AI is the umbrella; ML and DL sit inside it." },
  { q: "Deep learning uses:", o: ["neural networks with many layers", "if-then rules only", "calculators", "spreadsheets"], a: 0, why: "Many layers let it learn very complex patterns." },
  { q: "Face unlock in a smartphone mainly uses:", o: ["Computer Vision", "Natural Language Processing", "Data Science", "Robotics"], a: 0, why: "It understands images of the face - a CV task." },
  { q: "Google Translate is an example of:", o: ["Natural Language Processing", "Computer Vision", "robotics", "data storage"], a: 0, why: "It works on human language - text and speech." },
  { q: "Ethical AI means AI that is:", o: ["fair, private and transparent", "only fast", "only profitable", "only expensive"], a: 0, why: "Fairness, privacy and transparency are core AI ethics." },
  { q: "Assertion (A): Human supervision is necessary for important AI decisions. Reason (R): AI models can make unfair or wrong predictions.", o: ["Both correct, R explains A", "Both correct, R does not explain A", "A correct, R incorrect", "A incorrect, R correct"], a: 0, why: "Because the model can err, a human must remain responsible." },
];
