import type { ChapterDetail } from "./types";

/* Six hand-polished chapters from v1 — kept authoritative. */
export const CHAPTER_DETAILS: Record<string, ChapterDetail> = {

"maths-0-0": {
  slides: [
    { kicker: "Chapter 1 • Real Numbers", title: "Real Numbers — the complete number system",
      points: ["Natural, Whole, Integers, Rational, Irrational — together they form Real Numbers", "Every point on the number line is a Real Number", "Three heroes of this chapter: Euclid's Division Lemma, HCF, and irrationality proofs"],
      formula: "ℕ ⊂ 𝕎 ⊂ ℤ ⊂ ℚ ⊂ ℝ" },
    { kicker: "Concept 1", title: "Euclid's Division Lemma",
      points: ["a = bq + r, where 0 ≤ r < b", "The fastest way to find HCF — repeat division until the remainder is 0", "A fixed 3-mark question in the board exam"],
      formula: "a = bq + r   (0 ≤ r < b)" },
    { kicker: "Concept 2", title: "Fundamental Theorem of Arithmetic",
      points: ["Every composite number = a unique product of primes", "HCF = product of smallest powers • LCM = product of greatest powers", "Remember the golden relation:"],
      formula: "HCF(a,b) × LCM(a,b) = a × b" },
    { kicker: "Concept 3", title: "Proofs of Irrational Numbers",
      points: ["√2, √3, √5 are irrational — proved by contradiction", "Trick: assume rational (p/q) → both turn out even → contradiction!", "√2 + √3 is also irrational — an exam favourite"],
      formula: "√2 ∉ ℚ  (irrational)" },
    { kicker: "Concept 4", title: "The Rule of Decimal Expansions",
      points: ["Denominator in the form 2ⁿ × 5ᵐ → terminating decimal", "Otherwise non-terminating repeating", "1/8 = 0.125 (terminates) • 1/7 = 0.142857… (repeats)"],
      formula: "q = 2ⁿ·5ᵐ  ⇒  terminating" },
    { kicker: "Revision", title: "Exam-Day Checklist",
      points: ["HCF by Euclid's lemma — write all steps", "HCF × LCM = a × b — always show the verification", "√2 irrational proof — memorise the 5 steps, asked every year"],
      formula: "Practice = Ex 1.1 + 1.2 + 1.4" },
  ],
  formulas: [
    { name: "Euclid's Division Lemma", expr: "a = bq + r, 0 ≤ r < b" },
    { name: "HCF × LCM Relation", expr: "HCF(a,b) × LCM(a,b) = a × b" },
    { name: "Prime Factorisation", expr: "n = p₁^a₁ × p₂^a₂ × … (unique)" },
    { name: "HCF from factors", expr: "HCF = ∏ p^min(a,b)" },
    { name: "LCM from factors", expr: "LCM = ∏ p^max(a,b)" },
    { name: "Terminating decimal", expr: "q = 2ⁿ × 5ᵐ ⇒ terminating" },
  ],
  examples: [
    { title: "Ex 1.1 Q1 — HCF of 135 and 225", steps: ["225 > 135, so 225 = 135×1 + 90", "135 = 90×1 + 45", "90 = 45×2 + 0", "Remainder 0 → HCF = 45"], answer: "HCF = 45" },
    { title: "Ex 1.2 Q3 — HCF & LCM of 12, 15, 21", steps: ["12 = 2²×3,  15 = 3×5,  21 = 3×7", "HCF = 3 (lowest common)", "LCM = 2²×3×5×7 = 420"], answer: "HCF = 3, LCM = 420" },
    { title: "Prove: √2 is irrational", steps: ["Assume √2 = p/q (co-prime, q≠0)", "2 = p²/q² ⇒ p² = 2q² ⇒ p is even", "p = 2r ⇒ 4r² = 2q² ⇒ q² = 2r² ⇒ q is even", "Both p and q even — contradicts co-prime!", "∴ √2 is irrational"], answer: "Proved by contradiction" },
  ],
  notes: [
    "<b>Real Numbers</b> = Rational + Irrational, everything together.",
    "<b>Euclid's Division Lemma:</b> a = bq + r — repeat division to find HCF.",
    "<b>FTA:</b> every composite = a unique product of primes.",
    "<b>HCF × LCM = a × b</b> — for 2 numbers only! (not for 3 numbers)",
    "<b>√2, √3, √5</b> are irrational — memorise the contradiction proof.",
    "<b>Terminating decimal</b> only when the denominator breaks into powers of 2 and 5.",
  ],
  quiz: [
    { q: "In Euclid's Division Lemma, what is the condition on r?", options: ["0 ≤ r < b", "0 < r ≤ b", "r > b", "r = b"], answer: 0, why: "The remainder is always smaller than the divisor, and zero or positive." },
    { q: "What is the HCF of 12 and 18?", options: ["2", "3", "6", "36"], answer: 2, why: "12=2²×3, 18=2×3² → HCF = 2×3 = 6." },
    { q: "HCF(a,b) × LCM(a,b) = ?", options: ["a + b", "a × b", "a − b", "a ÷ b"], answer: 1, why: "The golden relation for two positive integers." },
    { q: "Which number is irrational?", options: ["22/7", "3.1416", "√2", "0.101001… (terminating)"], answer: 2, why: "√2 can never be written in p/q form." },
    { q: "What kind of decimal expansion does 13/3125 have?", options: ["Terminating", "Non-terminating repeating", "Non-terminating non-repeating", "Cannot say"], answer: 0, why: "3125 = 5⁵ → only 2/5 powers → terminating." },
  ],
  pyq: ["Prove that √5 is irrational. (CBSE 2023, 3m)", "Find HCF and LCM of 336 and 54 by prime factorisation and verify HCF×LCM = a×b. (CBSE 2022, 3m)", "Show that 6 + √2 is irrational. (CBSE 2020, 3m)"],
},

"science-0-0": {
  slides: [
    { kicker: "Chapter 1 • Chemistry", title: "Chemical Reactions & Equations",
      points: ["When substances combine to form NEW substances = a chemical reaction", "Signs: colour change, gas evolved, heat/cold, sound, or precipitate", "Word equation → Skeleton → Balanced equation (3 steps!)"],
      formula: "Mg + O₂ → MgO  (skeleton) → 2Mg + O₂ → 2MgO" },
    { kicker: "Types 1–2", title: "Combination & Decomposition",
      points: ["COMBINATION: A + B → AB (Quicklime: CaO + H₂O → Ca(OH)₂)", "DECOMPOSITION: AB → A + B (CaCO₃ → CaO + CO₂, on heating)", "Memory trick: Combination = marriage, Decomposition = divorce"],
      formula: "CaCO₃ --heat--> CaO + CO₂↑" },
    { kicker: "Types 3–4", title: "Displacement & Double Displacement",
      points: ["DISPLACEMENT: A + BC → AC + B (Iron + CuSO₄ → FeSO₄ + Cu)", "DOUBLE: AB + CD → AD + CB (Na₂SO₄ + BaCl₂ → BaSO₄↓ + 2NaCl)", "Precipitation = turning from soluble to insoluble"],
      formula: "Fe + CuSO₄ → FeSO₄ + Cu" },
    { kicker: "Types 5–6", title: "Oxidation & Reduction (Redox)",
      points: ["OXIDATION = O gain / H loss • REDUCTION = O loss / H gain", "Both always happen together = a REDOX reaction", "CuO + H₂ → Cu + H₂O (CuO reduced, H₂ oxidised)"],
      formula: "OIL-RIG: Oxidation Is Loss, Reduction Is Gain (e⁻)" },
    { kicker: "Effects", title: "Corrosion & Rancidity",
      points: ["CORROSION: rusting of iron — Fe₂O₃·xH₂O (prevent by painting/galvanisation)", "RANCIDITY: spoiling of oils/fats — antioxidants + nitrogen flushing", "That is why chips packets are filled with N₂ gas!"],
      formula: "Rust = Fe₂O₃·xH₂O" },
    { kicker: "Balancing", title: "The 3-Step Balancing Formula",
      points: ["Step 1: start with the largest formula", "Step 2: metals first, then non-metals, H and O at the end", "Step 3: count atoms on both sides — equal?"],
      formula: "Atoms Left = Atoms Right (Law of Conservation)" },
    { kicker: "Revision", title: "Exam Checklist",
      points: ["All 5 reaction types + one example each, memorised", "Practise 5 balancing numericals", "Make a difference table: Corrosion vs Rancidity"],
      formula: "Ex 1: Q 3, 7, 11, 15" },
  ],
  mindmap: { central: "Chemical Reactions",
    branches: [
      { label: "Equations", color: "#1a73e8", children: ["Word equation", "Skeleton equation", "Balanced equation", "States: (s)(l)(g)(aq)"] },
      { label: "5 Types", color: "#146c2e", children: ["Combination A+B→AB", "Decomposition AB→A+B", "Displacement", "Double displacement", "Redox (Oxi+Red)"] },
      { label: "Signs", color: "#e37400", children: ["Colour change", "Gas evolved", "Heat / cooling", "Precipitate forms"] },
      { label: "Effects", color: "#b3261e", children: ["Corrosion (rust)", "Rancidity (oils spoil)", "Galvanisation", "Antioxidants + N₂"] },
    ]},
  flowchart: [
    { title: "Observe", desc: "Colour? Gas? Heat? Precipitate? = reaction happened" },
    { title: "Write word equation", desc: "Magnesium + Oxygen → Magnesium oxide" },
    { title: "Write formula (skeleton)", desc: "Mg + O₂ → MgO" },
    { title: "Balance", desc: "2Mg + O₂ → 2MgO — atoms equal?" },
    { title: "Identify the type", desc: "Combination? Displacement? Redox?", type: "decision" },
    { title: "Done — add states", desc: "2Mg(s) + O₂(g) → 2MgO(s)", type: "result" },
  ],
  formulas: [
    { name: "Quicklime slaking", expr: "CaO + H₂O → Ca(OH)₂ + heat" },
    { name: "Limestone heating", expr: "CaCO₃ → CaO + CO₂↑" },
    { name: "Iron + Copper sulphate", expr: "Fe + CuSO₄ → FeSO₄ + Cu" },
    { name: "Precipitation", expr: "Na₂SO₄ + BaCl₂ → BaSO₄↓ + 2NaCl" },
    { name: "Redox example", expr: "CuO + H₂ → Cu + H₂O" },
    { name: "Rust formula", expr: "4Fe + 3O₂ + xH₂O → 2Fe₂O₃·xH₂O" },
  ],
  diagrams: [
    { title: "Activity 1.1 — Burning magnesium ribbon", desc: "Burn a magnesium ribbon → bright white light → white powder (MgO). Clean the ribbon with sandpaper before the reaction (to remove the oxide layer).", label: "Mg + O₂ → MgO" },
    { title: "Activity 1.3 — Iron nail in CuSO₄", desc: "Keep an iron nail in blue CuSO₄ solution for 20 min → solution turns light green (FeSO₄), brown coating (Cu) on the nail. Proof of displacement.", label: "Fe + CuSO₄ → FeSO₄ + Cu" },
    { title: "Electrolysis of water", desc: "Add a little H₂SO₄ to water and pass current → H₂ (double) at cathode, O₂ at anode. A decomposition reaction.", label: "2H₂O → 2H₂ + O₂" },
  ],
  notes: [
    "<b>Chemical reaction</b> = formation of new substances; signs: colour, gas, heat, precipitate.",
    "<b>Balanced equation</b> is a must — Law of Conservation of Mass (Lavoisier).",
    "<b>5 types:</b> Combination, Decomposition, Displacement, Double displacement, Redox.",
    "<b>Oxidation</b> = O gain/H loss; <b>Reduction</b> = O loss/H gain.",
    "<b>Corrosion:</b> rust on Fe (Fe₂O₃·xH₂O) — stop it by painting, oiling, galvanisation.",
    "<b>Rancidity:</b> oily food spoils — antioxidants, airtight packing, N₂ flushing.",
  ],
  quiz: [
    { q: "What type of reaction is CaO + H₂O → Ca(OH)₂?", options: ["Decomposition", "Combination", "Displacement", "Redox"], answer: 1, why: "Two reactants join into one product = combination." },
    { q: "In Fe + CuSO₄ → FeSO₄ + Cu, what is Fe doing?", options: ["Getting reduced", "Displacing Cu", "Forming a precipitate", "Nothing"], answer: 1, why: "More reactive Fe pushes Cu out of the solution." },
    { q: "Balanced equations are based on which law?", options: ["Gravitation", "Conservation of Mass", "Reflection", "Ohm's law"], answer: 1, why: "Matter is neither created nor destroyed — Lavoisier." },
    { q: "Which gas is filled in chips packets?", options: ["Oxygen", "Hydrogen", "Nitrogen", "CO₂"], answer: 2, why: "N₂ is inert — it prevents rancidity." },
    { q: "In CuO + H₂ → Cu + H₂O, which got oxidised?", options: ["CuO", "H₂", "Cu", "H₂O"], answer: 1, why: "H₂ gained oxygen (H₂→H₂O) = oxidation." },
  ],
  pyq: ["What is rancidity? Write two methods to prevent it. (CBSE 2023, 2m)", "Balance: FeSO₄ → Fe₂O₃ + SO₂ + SO₃ and name the reaction type. (CBSE 2022, 3m)", "Give one example each of combination and displacement reaction. (CBSE 2020, 2m)"],
},

"sst-0-1": {
  slides: [
    { kicker: "History Ch.2 • Nationalism in India", title: "Nationalism in India (1915–1947)",
      points: ["Gandhiji returned from South Africa in 1915 — with the new weapon of satyagraha", "3 big movements: Non-Cooperation (1920) → Civil Disobedience (1930) → Quit India (1942)", "Every movement = cause + events + result (the golden exam formula)"],
      formula: "Satyagraha = Truth + Non-violence" },
    { kicker: "1915–1919", title: "The Beginning: 3 Small Satyagrahas",
      points: ["1916 Champaran (Bihar) — for indigo farmers", "1917 Kheda (Gujarat) — crop failure, rent relief", "1918 Ahmedabad — mill workers' wages", "1919: Rowlatt Act + Jallianwala Bagh (13 April) — the nation was shaken"] },
    { kicker: "1920–22", title: "Non-Cooperation Movement",
      points: ["Khilafat + Swaraj = Hindu-Muslim unity", "Burnt foreign cloth, left schools-colleges, boycotted elections", "1922 Chauri Chaura (UP) — after violence, Gandhiji withdrew the movement"],
      formula: "1920 → 1922 (Chauri Chaura)" },
    { kicker: "1930–34", title: "Civil Disobedience — Dandi March",
      points: ["12 March 1930: Gandhiji left Sabarmati for Dandi with 78 followers", "6 April: made salt and broke the law — 240 miles, 24 days!", "Thousands of women joined • 1931 Gandhi-Irwin Pact • 2nd Round Table failed"],
      formula: "Dandi March: 12 Mar → 6 Apr 1930" },
    { kicker: "1942", title: "Quit India — 'Do or Die'",
      points: ["8 August 1942, Bombay: 'Quit India' + 'Do or Die'", "All leaders arrested in one night — yet the movement went on", "Parallel governments formed (Ballia-UP, Satara, Midnapore)"],
      formula: "'Do or Die' — 8 Aug 1942" },
    { kicker: "Sense of Belonging", title: "How Did Nationalism Spread?",
      points: ["United struggle + cultural symbols (Bharat Mata, Vande Mataram)", "History was rewritten — folklore, songs, flags", "But: Dalits (Ambedkar) and Muslims (Jinnah) raised their own questions too"],
      formula: "Imagined community — one dream, one nation" },
    { kicker: "Revision", title: "Exam Checklist",
      points: ["3 movements: dates + cause + 2 events + result — make a table", "Dandi March and Quit India carry sure-shot 5 marks", "Map: Champaran, Kheda, Dandi, Chauri Chaura, Jallianwala Bagh"],
      formula: "Memorise the timeline: 1919-20-22-30-31-42" },
  ],
  timeline: [
    { y: "1915", t: "Gandhiji returned to India from South Africa" },
    { y: "1919", t: "Rowlatt Act • 13 April: Jallianwala Bagh massacre" },
    { y: "1920", t: "Non-Cooperation + Khilafat Movement began" },
    { y: "1922", t: "Chauri Chaura incident — movement withdrawn" },
    { y: "1929", t: "Lahore Session — 'Purna Swaraj' declared (26 Jan 1930)" },
    { y: "1930", t: "Dandi March (12 Mar–6 Apr) — Civil Disobedience began" },
    { y: "1931", t: "Gandhi-Irwin Pact • 2nd Round Table Conference" },
    { y: "1942", t: "Quit India Movement — 'Do or Die' (8 Aug)" },
  ],
  mindmap: { central: "Nationalism in India",
    branches: [
      { label: "Satyagraha", color: "#1a73e8", children: ["Champaran 1916", "Kheda 1917", "Ahmedabad 1918", "Rowlatt 1919"] },
      { label: "Non-Cooperation", color: "#146c2e", children: ["1920–22", "Khilafat + Swaraj", "Boycott foreign goods", "Chauri Chaura ends it"] },
      { label: "Civil Disobedience", color: "#e37400", children: ["Dandi March 1930", "Broke the salt law", "Women joined in", "Gandhi-Irwin Pact"] },
      { label: "Quit India", color: "#b3261e", children: ["8 Aug 1942", "'Do or Die'", "Leaders arrested", "Parallel governments"] },
    ]},
  flowchart: [
    { title: "Cause", desc: "Rowlatt Act, Jallianwala, prices, Khilafat issue" },
    { title: "Movement begins", desc: "Gandhiji's call — satyagraha, boycott, march" },
    { title: "Mass participation", desc: "Farmers, workers, women, students all joined" },
    { title: "Government response?", desc: "Arrests / firing / compromise?", type: "decision" },
    { title: "Result", desc: "New law, or withdrawal, or a step toward freedom", type: "result" },
  ],
  notes: [
    "<b>1919:</b> Rowlatt Act (arrest without trial) + Jallianwala Bagh (Gen. Dyer).",
    "<b>Non-Cooperation (1920–22):</b> with Khilafat; withdrawn after Chauri Chaura.",
    "<b>Civil Disobedience (1930):</b> Dandi March 12 Mar–6 Apr; broke the salt law.",
    "<b>Quit India (1942):</b> 8 Aug Bombay; 'Do or Die'; leaders jailed, yet it went on.",
    "<b>Sense of collective belonging:</b> built through symbols, folklore, history, flags.",
    "<b>Map points:</b> Champaran, Kheda, Ahmedabad, Amritsar, Chauri Chaura, Dandi, Bombay.",
  ],
  quiz: [
    { q: "When did Gandhiji return from South Africa?", options: ["1915", "1919", "1920", "1930"], answer: 0, why: "He reached India in January 1915." },
    { q: "When did the Jallianwala Bagh massacre happen?", options: ["13 April 1918", "13 April 1919", "15 Aug 1919", "26 Jan 1920"], answer: 1, why: "13 April 1919, on Baisakhi, in Amritsar." },
    { q: "Why was Non-Cooperation withdrawn?", options: ["Funds over", "Chauri Chaura violence", "Leaders fell ill", "British agreed"], answer: 1, why: "In Feb 1922 a police station was burnt at Chauri Chaura (UP)." },
    { q: "How long was the Dandi March?", options: ["100 miles", "150 miles", "240 miles", "500 miles"], answer: 2, why: "Sabarmati to Dandi, 24 days, 240 miles." },
    { q: "Which movement gave the slogan 'Do or Die'?", options: ["Non-Cooperation", "Civil Disobedience", "Quit India"], answer: 2, why: "Given by Gandhiji on 8 Aug 1942 in Bombay." },
  ],
  pyq: ["Why did Gandhiji decide to withdraw the Non-Cooperation Movement? (CBSE 2023, 3m)", "Describe the Dandi March and its significance. (CBSE 2022, 5m)", "How did cultural symbols help in creating nationalism? (CBSE 2020, 3m)"],
},

"english-0-0": {
  slides: [
    { kicker: "Prose 1 • G.L. Fuentes", title: "A Letter to God",
      points: ["Lencho — a hardworking farmer with blind faith in God", "A hailstorm destroyed his crop → he wrote a letter to GOD!", "Theme: Faith vs Reality — and irony"],
      formula: "Faith can move mountains" },
    { kicker: "Story 1", title: "Lencho's Hope",
      points: ["Rain = 'new coins' — the crop is his only wealth", "Big drops = 'ten-cent pieces', small ones = 'five-cent pieces'", "Personification: rain from the north-east, towards his field"],
      formula: "'The field of ripe corn with its flowers…'" },
    { kicker: "Story 2", title: "The Storm and Ruin",
      points: ["Hail fell for an hour — field, trees, everything turned white", "'The hail has left nothing' — not a single leaf survived", "But Lencho did not break: 'God will provide!' — that is his character"],
      formula: "Disaster → Despair → Faith" },
    { kicker: "Story 3", title: "The Letter to God",
      points: ["He asked for 100 pesos — to sow again and feed his family", "Wrote 'God' on the envelope — everyone at the post office was amazed!", "The postmaster laughed, then melted — collected money (70 pesos)"],
      formula: "100 pesos asked → 70 received" },
    { kicker: "Ending", title: "Irony — the Biggest Twist",
      points: ["Lencho counted 70 pesos → angry not at GOD, but suspicious of the POST OFFICE!", "Second letter: 'send the remaining 30, but NOT through the post office — they are crooks!'", "Those who helped were called thieves — the best example of situational irony"],
      formula: "Helpers = 'crooks'  (Irony!)" },
    { kicker: "Exam", title: "Exam Checklist",
      points: ["Character sketch of Lencho (faithful, hardworking, innocent, stubborn)", "Irony in the story — sure-shot 3 marks", "Theme: blind faith — right or wrong? (opinion question)"],
      formula: "Q: Lencho's faith — strength or weakness?" },
  ],
  mindmap: { central: "A Letter to God",
    branches: [
      { label: "Characters", color: "#1a73e8", children: ["Lencho — faithful farmer", "Wife — supportive", "Postmaster — kind, witty", "Postmen — helpers"] },
      { label: "Plot", color: "#146c2e", children: ["Hope (rain)", "Disaster (hail)", "Letter (100 pesos)", "Help (70 pesos)", "Irony (crooks!)"] },
      { label: "Themes", color: "#e37400", children: ["Blind faith in God", "Human kindness", "Irony of life", "Hope vs reality"] },
      { label: "Devices", color: "#9334e6", children: ["Irony (ending)", "Personification (rain-coins)", "Metaphor (locusts-hail)", "Symbolism (letter)"] },
    ]},
  flowchart: [
    { title: "Hope", desc: "Rain arrived — Lencho is happy, 'new coins!'" },
    { title: "Disaster", desc: "Hailstorm — the whole crop destroyed" },
    { title: "The letter", desc: "Wrote to God for 100 pesos" },
    { title: "Help", desc: "The postmaster sent 70 pesos" },
    { title: "Lencho's reaction?", desc: "Gratitude or suspicion?", type: "decision" },
    { title: "Irony!", desc: "Called the post office 'crooks'!", type: "result" },
  ],
  words: [
    { w: "downpour", m: "heavy rainfall", u: "The downpour destroyed the crops." },
    { w: "hailstorm", m: "storm of hailstones", u: "The hailstorm lasted for an hour." },
    { w: "amiable", m: "friendly, good-natured", u: "The postmaster was an amiable fellow." },
    { w: "conscience", m: "inner sense of right and wrong", u: "Tapping the letter on his desk, his conscience pricked him." },
    { w: "bother", m: "to trouble or disturb", u: "Don't bother God with small complaints." },
    { w: "crooks", m: "cheats, dishonest people", u: "Lencho called the post office employees crooks." },
  ],
  notes: [
    "<b>Author:</b> G.L. Fuentes (Mexican writer) — a story of innocent faith.",
    "<b>Lencho:</b> hardworking, God-fearing, stubborn — faith is his strength + weakness.",
    "<b>Postmaster:</b> kind-hearted — laughed first, then helped (70 pesos).",
    "<b>Irony:</b> helpers called 'crooks' — the soul of the story, a 3-mark question.",
    "<b>Message:</b> Faith gives courage; human kindness exists quietly.",
  ],
  quiz: [
    { q: "How many pesos did Lencho ask God for?", options: ["50", "70", "100", "1000"], answer: 2, why: "100 pesos — for sowing + family survival." },
    { q: "How many pesos did the postmaster send?", options: ["100", "70", "30", "50"], answer: 1, why: "He could collect 70 from his salary + friends." },
    { q: "What destroyed the crop?", options: ["Flood", "Hailstorm", "Locusts", "Drought"], answer: 1, why: "An hour of hailstones finished everything." },
    { q: "What did Lencho call the post office people?", options: ["Angels", "Crooks", "Friends", "Brothers"], answer: 1, why: "30 pesos were short → he suspected them. Pure irony!" },
    { q: "What is the main theme of the story?", options: ["Revenge", "Blind faith in God", "War", "Travel"], answer: 1, why: "Lencho's unshaken faith is the soul of the story." },
  ],
  pyq: ["What is the irony in 'A Letter to God'? (CBSE 2023, 3m)", "Character sketch of Lencho. (CBSE 2022, 3m)", "Why did Lencho write a second letter to God? (CBSE 2020, 3m)"],
},

"sst-0-3": {
  slides: [
    { kicker: "History Ch.4 • The Age of Industrialisation", title: "Before the Industrial Revolution",
      points: ["Production happened at home — artisans, guilds and merchants controlled trade", "In England factories came first, machines arrived slowly", "Proto-industrialisation: merchants gave work to countryside families"],
      formula: "Hand labour → Steam power → Factory" },
    { kicker: "Britain", title: "Why Was Change Slow in Britain?",
      points: ["Machines were costly — human labour was cheap and easily available", "Seasonal industries needed flexible workers, not fixed machines", "Handmade goods stayed popular — the upper classes loved craft finish", "James Watt's improved steam engine (1781) spread only slowly"],
      formula: "1781: Watt's improved steam engine" },
    { kicker: "Workers", title: "Life of the Workers",
      points: ["Long hours, low wages, crowded slums — no housing or security", "Seasonal unemployment: no work for months after the busy season", "Workers feared machines and broke them — food riots and protests"],
      formula: "Labour was abundant, wages were low" },
    { kicker: "India", title: "Industrialisation in the Colonies — India",
      points: ["Indian textiles ruled world markets until the mid-1700s", "Manchester goods flooded India while tariffs crushed Indian weavers", "Weavers lost work — many became labourers or migrated to cities"],
      formula: "Manchester in, Indian weavers out" },
    { kicker: "Factories in India", title: "Factories Come Up in India",
      points: ["1854: first cotton mill in Bombay • 1855: first jute mill in Bengal", "1912: Tata Iron and Steel (TISCO) at Jamshedpur", "Early entrepreneurs: Dwarkanath Tagore, Dinshaw Petit, J.N. Tata", "Workers came from villages — the jobber recruited and housed them"],
      formula: "1854 Bombay • 1855 Bengal • 1912 TISCO" },
    { kicker: "Growth", title: "Small Units Survived Too",
      points: ["Small-scale units dominated — handloom survived alongside mills", "The fly shuttle and new looms helped weavers compete", "Advertisements created markets — labels, calendars, images of gods"],
      formula: "Hand + machine grew together" },
    { kicker: "Revision", title: "Exam Checklist",
      points: ["Britain: why slow? (cost of machines, cheap labour, taste)", "India: fall of textiles + rise of factories (1854 / 1855 / 1912)", "Sure-shot: condition of weavers + early entrepreneurs + jobber"],
      formula: "Dates: 1781 • 1854 • 1855 • 1912" },
  ],
  timeline: [
    { y: "1730s", t: "Earliest factories coming up in England" },
    { y: "1781", t: "James Watt patents the improved steam engine" },
    { y: "1854", t: "First cotton mill set up in Bombay" },
    { y: "1855", t: "First jute mill set up in Bengal" },
    { y: "1912", t: "Tata Iron and Steel Company starts at Jamshedpur" },
    { y: "1920s", t: "Handloom revival with the fly shuttle; goods boycotted" },
  ],
  notes: [
    "<b>Proto-industrialisation:</b> merchants offered work to rural families before factories existed.",
    "<b>Slow mechanisation:</b> machines were expensive, labour was cheap, handmade goods stayed fashionable.",
    "<b>Steam engine:</b> Newcomen's engine was improved by James Watt (patent 1781).",
    "<b>Workers:</b> long hours, low wages, slums, seasonal joblessness, fear of machines.",
    "<b>Fall of Indian textiles:</b> Manchester imports + British tariffs destroyed weavers' livelihoods.",
    "<b>Indian factories:</b> cotton (1854 Bombay), jute (1855 Bengal), steel (1912 TISCO Jamshedpur).",
    "<b>Jobber:</b> the contractor who recruited village workers and controlled their jobs.",
    "<b>Small scale survived:</b> fly shuttle looms + advertisements kept handloom alive.",
  ],
  quiz: [
    { q: "Where and when was India's first cotton mill set up?", options: ["Bengal, 1855", "Bombay, 1854", "Ahmedabad, 1861", "Kanpur, 1860"], answer: 1, why: "The first cotton mill came up in Bombay in 1854." },
    { q: "James Watt patented the improved steam engine in…", options: ["1764", "1776", "1781", "1800"], answer: 2, why: "Watt's improved engine was patented in 1781." },
    { q: "Who was the 'jobber' in Indian factories?", options: ["A machine operator", "The contractor who recruited workers", "A mill owner", "A British officer"], answer: 1, why: "The jobber recruited village workers and controlled their employment." },
    { q: "How did the fly shuttle help weavers?", options: ["It needed no worker", "It raised productivity and helped handloom compete with mills", "It ran on steam", "It made only carpets"], answer: 1, why: "The fly shuttle raised output, so handloom could survive beside mills." },
    { q: "Why did Indian textiles decline in the 1800s?", options: ["No cotton in India", "Manchester imports + tariffs on Indian goods", "Weavers went on strike", "Cloth went out of fashion"], answer: 1, why: "Cheap Manchester cloth flooded India while Indian exports faced heavy duties." },
  ],
},

"sst-3-4": {
  slides: [
    { kicker: "Economics Ch.5 • Consumer Rights", title: "Why Do Consumers Need Rights?",
      points: ["Markets exploit: duplicate goods, wrong weights, unfair prices", "Sellers know more than buyers — information is unequal", "A people's movement + law now protects buyers in India"],
      formula: "Informed consumer = protected consumer" },
    { kicker: "COPRA 1986", title: "Consumer Protection Act (COPRA)",
      points: ["Passed in 1986 — gave rights + special courts for complaints", "Amended in 2019: e-commerce covered, bigger penalties", "Applies to goods AND services"],
      formula: "COPRA: 1986 → 2019 (amended)" },
    { kicker: "Rights", title: "Your 6 Rights as a Consumer",
      points: ["Safety, Information, Choice and Representation (being heard)", "Redressal (compensation) + Consumer Education", "Learn each right with one real example"],
      formula: "6 rights: Safety • Info • Choice • Voice • Redress • Learn" },
    { kicker: "Redressal", title: "3-Tier Redressal System",
      points: ["District Commission → State Commission → National Commission", "No lawyer needed; small fee; decision in about 90–150 days", "Faulty goods replaced + compensation for loss"],
      formula: "District → State → National" },
    { kicker: "Duties", title: "Duties of a Smart Consumer",
      points: ["Check MRP, expiry date and quality marks before buying", "ISI (industrial goods) • Agmark (food) • Hallmark (gold)", "Always take the bill — no bill, no complaint", "Complain in writing; approach the consumer forum if ignored"],
      formula: "Bill + Awareness = Power" },
    { kicker: "Revision", title: "Exam Checklist",
      points: ["COPRA 1986 + 2019 amendment (e-commerce)", "6 rights with one example each — a fixed question", "3-tier order + ISI / Agmark / Hallmark marks", "24 December is National Consumer Day"],
      formula: "24 December: National Consumer Day" },
  ],
  notes: [
    "<b>Exploitation:</b> duplicates, adulteration, wrong measures, hidden charges, false ads.",
    "<b>COPRA 1986:</b> rights + 3-tier courts; 2019 amendment covers online shopping.",
    "<b>6 rights:</b> safety, information, choice, representation, redressal, education.",
    "<b>Redressal tiers:</b> District → State → National Commission; quick, cheap, no lawyer needed.",
    "<b>Quality marks:</b> ISI for appliances, Agmark for food, Hallmark for gold, FSSAI for packed food.",
    "<b>Consumer duties:</b> check labels, compare prices, take the bill, complain in writing.",
    "<b>E-commerce:</b> return policies and seller details are now legally required.",
    "<b>Remember:</b> National Consumer Day is celebrated on 24 December.",
  ],
  quiz: [
    { q: "COPRA, India's main consumer law, was passed in…", options: ["1976", "1986", "1996", "2006"], answer: 1, why: "The Consumer Protection Act was passed in 1986." },
    { q: "Which of these is NOT a consumer right?", options: ["Right to safety", "Right to information", "Right to free goods", "Right to redressal"], answer: 2, why: "There is no 'right to free goods' — the 6 rights cover safety, info, choice, voice, redress and education." },
    { q: "Correct order of the redressal system?", options: ["National → State → District", "District → State → National", "State → District → National", "District → National → State"], answer: 1, why: "Complaints rise from District to State to National Commission." },
    { q: "The Agmark seal is found on…", options: ["Gold jewellery", "Electrical appliances", "Food and farm products", "Medicines"], answer: 2, why: "Agmark certifies food and agricultural products." },
    { q: "What is the first thing to do when cheated by a seller?", options: ["Fight with the seller", "File a written complaint with the bill as proof", "Post on social media only", "Do nothing"], answer: 1, why: "A written complaint with the bill is the valid first step; forums come next." },
  ],
},
};
