import type { QuizQ } from "./types";

/* Extra conceptual MCQ packs merged into every chapter quiz.
   Original questions; answer = index of correct option. Key: chapterKey. */
export const EXTRA_QUIZ: Record<string, QuizQ[]> = {
 "maths-0-0": [
  { q: "The decimal expansion of p/q terminates when q (in lowest form) is of the form:", options: ["2^m 5^n", "2^m 3^n", "3^m 5^n", "any number"], answer: 0, why: "Only powers of 2 and 5 in the denominator give terminating decimals." },
  { q: "HCF of two numbers is 9, LCM is 360 and one number is 45. The other is:", options: ["72", "80", "60", "90"], answer: 0, why: "Other = (HCF x LCM)/45 = 3240/45 = 72." },
  { q: "Two coprime numbers have LCM equal to:", options: ["their product", "their HCF", "1", "the smaller number"], answer: 0, why: "Coprime means HCF 1, so LCM = product." },
  { q: "sqrt(2) is:", options: ["irrational", "rational", "a whole number", "terminating"], answer: 0, why: "Classic proof by contradiction shows it is irrational." },
  { q: "The largest number dividing 70 and 125 leaving remainders 5 and 8 is:", options: ["13", "5", "65", "117"], answer: 0, why: "HCF of (70-5)=65 and (125-8)=117 is 13." },
 ],
 "maths-0-1": [
  { q: "A quadratic polynomial can have at most how many zeroes?", options: ["2", "1", "3", "0"], answer: 0 },
  { q: "If alpha and beta are zeroes of x^2 - 5x + 6, then alpha + beta =", options: ["5", "-5", "6", "-6"], answer: 0, why: "Sum = -b/a = 5." },
  { q: "For the same polynomial, alpha x beta =", options: ["6", "5", "-6", "1"], answer: 0, why: "Product = c/a = 6." },
  { q: "A polynomial with sum of zeroes 3 and product 2 is:", options: ["x^2 - 3x + 2", "x^2 + 3x + 2", "x^2 - 2x + 3", "2x^2 - 3x + 1"], answer: 0, why: "x^2 - (sum)x + (product)." },
  { q: "If the graph of a polynomial does not cut the x-axis, its number of zeroes is:", options: ["0", "1", "2", "3"], answer: 0 },
 ],
 "maths-0-2": [
  { q: "A pair of linear equations with a unique solution represents:", options: ["intersecting lines", "parallel lines", "coincident lines", "circles"], answer: 0 },
  { q: "x + y = 5 and x - y = 1 give:", options: ["x=3, y=2", "x=2, y=3", "x=4, y=1", "no solution"], answer: 0 },
  { q: "Parallel lines mean the pair has:", options: ["no solution", "one solution", "infinite solutions", "two solutions"], answer: 0 },
  { q: "kx + 2y = 3 and 2x + 4y = 5 have no solution when k =", options: ["1", "2", "4", "0"], answer: 0, why: "k/2 = 2/4 ≠ 3/5 gives k = 1." },
  { q: "Coincident lines give:", options: ["infinitely many solutions", "no solution", "one solution", "negative solution"], answer: 0 },
 ],
 "maths-0-3": [
  { q: "The roots of x^2 - 4 = 0 are:", options: ["2 and -2", "4 and -4", "2 only", "0 and 4"], answer: 0 },
  { q: "The discriminant of x^2 + 4x + 4 is:", options: ["0", "16", "8", "-16"], answer: 0, why: "16 - 16 = 0 (equal roots)." },
  { q: "A quadratic has equal roots when:", options: ["D = 0", "D > 0", "D < 0", "D = 1"], answer: 0 },
  { q: "If D > 0 the roots are:", options: ["two distinct real", "equal", "not real", "zero"], answer: 0 },
  { q: "Sum of roots of 2x^2 - 6x + 3 = 0 is:", options: ["3", "-3", "6", "3/2"], answer: 0, why: "-b/a = 6/2 = 3." },
 ],
 "maths-0-4": [
  { q: "The nth term of 2, 5, 8, ... is:", options: ["3n - 1", "3n + 1", "2n + 3", "n + 3"], answer: 0 },
  { q: "If a = 7 and d = 3, then a10 =", options: ["34", "37", "30", "40"], answer: 0, why: "7 + 9x3 = 34." },
  { q: "Sum of the first 10 natural numbers:", options: ["55", "50", "45", "60"], answer: 0, why: "10x11/2." },
  { q: "The common difference of 7, 4, 1, ... is:", options: ["-3", "3", "-4", "4"], answer: 0 },
  { q: "An AP has a = 2, d = 0. Its 100th term is:", options: ["2", "0", "200", "100"], answer: 0 },
 ],
 "maths-0-5": [
  { q: "The ratio of areas of two similar triangles equals:", options: ["square of side ratio", "side ratio", "cube of side ratio", "half of side ratio"], answer: 0 },
  { q: "In triangle ABC, DE || BC with AD/DB = 1/2. Then AE/EC =", options: ["1/2", "2", "1/3", "3"], answer: 0, why: "Thales theorem: equal ratios." },
  { q: "Two triangles with equal corresponding angles are similar by:", options: ["AA", "SSS", "SAS", "ASA"], answer: 0 },
  { q: "Sides of similar triangles are in 2:3, so areas are in:", options: ["4:9", "2:3", "8:27", "9:4"], answer: 0 },
  { q: "A right triangle with legs 6 and 8 has hypotenuse:", options: ["10", "14", "12", "48"], answer: 0, why: "36+64=100." },
 ],
 "maths-0-6": [
  { q: "Distance between (0,0) and (3,4) is:", options: ["5", "7", "12", "25"], answer: 0 },
  { q: "Midpoint of (2,4) and (6,8) is:", options: ["(4,6)", "(8,12)", "(2,2)", "(3,5)"], answer: 0 },
  { q: "Any point on the x-axis has:", options: ["y = 0", "x = 0", "x = y", "x + y = 0"], answer: 0 },
  { q: "The section formula with ratio 1:1 gives the:", options: ["midpoint", "origin", "centroid", "vertex"], answer: 0 },
  { q: "The distance formula is:", options: ["sqrt((x2-x1)^2 + (y2-y1)^2)", "(x2-x1)+(y2-y1)", "(x2-x1)(y2-y1)", "sqrt(x1+x2)"], answer: 0 },
 ],
 "maths-0-7": [
  { q: "sin 30° =", options: ["1/2", "1", "sqrt3/2", "0"], answer: 0 },
  { q: "cos 60° =", options: ["1/2", "sqrt3/2", "1", "2"], answer: 0 },
  { q: "tan 45° =", options: ["1", "0", "1/2", "not defined"], answer: 0 },
  { q: "sin^2 t + cos^2 t =", options: ["1", "0", "2", "depends on t"], answer: 0 },
  { q: "If tan t = 1 (t acute), then t =", options: ["45°", "30°", "60°", "90°"], answer: 0 },
 ],
 "maths-0-8": [
  { q: "The angle of elevation is measured:", options: ["upward from horizontal", "downward from horizontal", "from the vertical", "between two towers"], answer: 0 },
  { q: "A tower's shadow equals its height. The sun's elevation is:", options: ["45°", "30°", "60°", "90°"], answer: 0, why: "tan = 1." },
  { q: "The angle of depression is measured:", options: ["downward from horizontal", "upward from horizontal", "from the ground", "inside the triangle"], answer: 0 },
  { q: "For a 30° elevation, height/distance =", options: ["1/sqrt3", "sqrt3", "1", "1/2"], answer: 0 },
  { q: "The line of sight joins:", options: ["eye and object", "ground and tower", "two objects", "shadow and sun"], answer: 0 },
 ],
 "maths-0-9": [
  { q: "From an external point, a circle has how many tangents?", options: ["2", "1", "0", "3"], answer: 0 },
  { q: "The tangent at a point is perpendicular to the:", options: ["radius", "chord", "diameter only", "secant"], answer: 0 },
  { q: "From a point ON the circle, tangents possible:", options: ["1", "2", "0", "infinite"], answer: 0 },
  { q: "Tangents PA and PB from P are:", options: ["equal", "unequal", "parallel", "perpendicular"], answer: 0 },
  { q: "A point inside the circle gives how many tangents?", options: ["0", "1", "2", "3"], answer: 0 },
 ],
 "maths-0-10": [
  { q: "Area of a sector with angle θ (degrees):", options: ["(θ/360)πr^2", "θπr^2", "(θ/180)πr^2", "2πrθ"], answer: 0 },
  { q: "Arc length for angle θ:", options: ["(θ/360)2πr", "(θ/360)πr^2", "πrθ", "2πr"], answer: 0 },
  { q: "Area of a circle of radius 7 (π=22/7):", options: ["154", "44", "49", "196"], answer: 0 },
  { q: "Circumference 44 cm means radius:", options: ["7", "14", "22", "11"], answer: 0, why: "2πr=44." },
  { q: "Area of a segment = sector minus:", options: ["triangle", "circle", "radius", "arc"], answer: 0 },
 ],
 "maths-0-11": [
  { q: "Volume of a cylinder:", options: ["πr^2h", "2πrh", "(1/3)πr^2h", "4πr^2"], answer: 0 },
  { q: "Total surface area of a sphere:", options: ["4πr^2", "(4/3)πr^3", "2πr^2", "πr^2"], answer: 0 },
  { q: "Volume of a cone:", options: ["(1/3)πr^2h", "πr^2h", "(2/3)πr^3", "πr^3"], answer: 0 },
  { q: "Two cubes of side 2 joined end to end have volume:", options: ["16", "8", "12", "24"], answer: 0, why: "8+8." },
  { q: "Melting and recasting conserves:", options: ["volume", "surface area", "radius", "height"], answer: 0 },
 ],
 "maths-0-12": [
  { q: "Mean of 2, 4, 6 is:", options: ["4", "6", "3", "12"], answer: 0 },
  { q: "Median of 1, 3, 5, 7 is:", options: ["4", "5", "3", "16"], answer: 0, why: "(3+5)/2." },
  { q: "The mode is the value with:", options: ["highest frequency", "lowest frequency", "middle position", "largest size"], answer: 0 },
  { q: "The empirical relation is:", options: ["3 Median = Mode + 2 Mean", "Mean = Mode + Median", "2 Mean = 3 Mode", "Median = Mean + Mode"], answer: 0 },
  { q: "Class mark of 10-20 is:", options: ["15", "10", "20", "5"], answer: 0 },
 ],
 "maths-0-13": [
  { q: "The probability of a sure event is:", options: ["1", "0", "1/2", "-1"], answer: 0 },
  { q: "P(E) + P(not E) =", options: ["1", "0", "2", "1/2"], answer: 0 },
  { q: "A die is thrown. P(getting a number > 4) =", options: ["1/3", "1/6", "2/3", "1/2"], answer: 0, why: "5,6 -> 2/6." },
  { q: "Two coins tossed together. P(two heads) =", options: ["1/4", "1/2", "1/3", "3/4"], answer: 0 },
  { q: "Probability always lies:", options: ["between 0 and 1", "below 0", "above 1", "between -1 and 1"], answer: 0 },
 ],
 "science-0-0": [
  { q: "Fe + CuSO4 -> FeSO4 + Cu is a:", options: ["displacement reaction", "decomposition", "neutralisation", "combination"], answer: 0 },
  { q: "Balancing equations is based on:", options: ["law of conservation of mass", "law of motion", "Boyle's law", "Ohm's law"], answer: 0 },
  { q: "2Mg + O2 -> 2MgO is a:", options: ["combination reaction", "displacement", "double displacement", "decomposition"], answer: 0 },
  { q: "Heating CaCO3 gives CaO + CO2. The type is:", options: ["decomposition", "combination", "displacement", "precipitation"], answer: 0 },
  { q: "Rusting of iron is an example of:", options: ["oxidation", "reduction only", "neutralisation", "distillation"], answer: 0 },
 ],
 "science-0-1": [
  { q: "The pH of a neutral solution is:", options: ["7", "0", "14", "1"], answer: 0 },
  { q: "Acid + base gives:", options: ["salt + water", "only salt", "only water", "gas + salt"], answer: 0 },
  { q: "NaHCO3 is commonly called:", options: ["baking soda", "washing soda", "caustic soda", "lime"], answer: 0 },
  { q: "Blue litmus turns red in:", options: ["an acid", "a base", "pure water", "salt solution"], answer: 0 },
  { q: "The approximate pH of lemon juice is:", options: ["2", "7", "9", "12"], answer: 0 },
 ],
 "science-0-2": [
  { q: "The most reactive metal among these is:", options: ["sodium", "iron", "copper", "silver"], answer: 0 },
  { q: "Ionic compounds generally have:", options: ["high melting points", "low melting points", "no melting point", "liquid state"], answer: 0 },
  { q: "The metal liquid at room temperature:", options: ["mercury", "sodium", "iron", "aluminium"], answer: 0 },
  { q: "An amphoteric oxide is:", options: ["Al2O3", "Na2O", "CaO", "MgO"], answer: 0 },
  { q: "At the top of the reactivity series is:", options: ["potassium", "gold", "copper", "lead"], answer: 0 },
 ],
 "science-0-3": [
  { q: "The number of covalent bonds in CH4 is:", options: ["4", "1", "2", "8"], answer: 0 },
  { q: "The functional group of ethanol is:", options: ["-OH", "-COOH", "-CHO", "-Cl"], answer: 0 },
  { q: "The next member after CH4 in its homologous series is:", options: ["C2H6", "C2H4", "C2H2", "CH3OH"], answer: 0 },
  { q: "Saturated hydrocarbons contain:", options: ["only single bonds", "double bonds", "triple bonds", "no bonds"], answer: 0 },
  { q: "CH3COOH is named:", options: ["ethanoic acid", "methanoic acid", "propanoic acid", "ethanol"], answer: 0 },
 ],
 "science-0-4": [
  { q: "Photosynthesis takes place in the:", options: ["chloroplast", "mitochondria", "nucleus", "ribosome"], answer: 0 },
  { q: "Glucose breakdown using oxygen is:", options: ["aerobic respiration", "anaerobic", "fermentation", "transpiration"], answer: 0 },
  { q: "The human heart has how many chambers?", options: ["4", "2", "3", "5"], answer: 0 },
  { q: "The gas released during photosynthesis:", options: ["oxygen", "carbon dioxide", "nitrogen", "hydrogen"], answer: 0 },
  { q: "Villi are found in the:", options: ["small intestine", "stomach", "heart", "kidney"], answer: 0 },
 ],
 "science-0-5": [
  { q: "A neuron is a:", options: ["nerve cell", "muscle cell", "blood cell", "bone cell"], answer: 0 },
  { q: "The plant hormone that promotes growth toward light:", options: ["auxin", "insulin", "thyroxine", "cytokinin only"], answer: 0 },
  { q: "The centre of a reflex action is the:", options: ["spinal cord", "heart", "lungs", "kidney"], answer: 0 },
  { q: "Insulin regulates:", options: ["blood sugar", "oxygen", "calcium", "water"], answer: 0 },
  { q: "The largest part of the human brain is the:", options: ["cerebrum", "cerebellum", "medulla", "pons"], answer: 0 },
 ],
 "science-0-6": [
  { q: "The male gamete in humans is the:", options: ["sperm", "ovum", "zygote", "embryo"], answer: 0 },
  { q: "Hydra reproduces asexually by:", options: ["budding", "fission", "fragmentation", "spore loss"], answer: 0 },
  { q: "Fertilisation in humans occurs in the:", options: ["oviduct", "uterus", "ovary", "cervix"], answer: 0 },
  { q: "Amoeba divides by:", options: ["binary fission", "budding", "regeneration", "pollination"], answer: 0 },
  { q: "DNA copying happens during:", options: ["reproduction", "digestion", "excretion", "respiration"], answer: 0 },
 ],
 "science-0-7": [
  { q: "The father of genetics is:", options: ["Mendel", "Darwin", "Newton", "Bohr"], answer: 0 },
  { q: "In F2 of Tt x Tt, tall : dwarf =", options: ["3:1", "1:1", "1:3", "9:7"], answer: 0 },
  { q: "The sex chromosomes in a human male are:", options: ["XY", "XX", "YY", "XO"], answer: 0 },
  { q: "The trait that expresses in F1 is called:", options: ["dominant", "recessive", "hidden", "mutant"], answer: 0 },
  { q: "Humans have how many pairs of chromosomes?", options: ["23", "46", "22", "24"], answer: 0, why: "23 pairs = 46 total." },
 ],
 "science-0-8": [
  { q: "Rear-view mirrors in vehicles are:", options: ["convex", "concave", "plane", "cylindrical"], answer: 0 },
  { q: "A plane mirror forms a:", options: ["virtual, erect image", "real image", "inverted image", "magnified real image"], answer: 0 },
  { q: "Light bends on refraction because its ___ changes:", options: ["speed", "colour", "frequency", "amplitude"], answer: 0 },
  { q: "The unit of lens power is the:", options: ["dioptre", "watt", "ohm", "lumen"], answer: 0 },
  { q: "A concave mirror is a ___ mirror:", options: ["converging", "diverging", "plane", "diffusing"], answer: 0 },
 ],
 "science-0-9": [
  { q: "The image in the human eye forms on the:", options: ["retina", "cornea", "iris", "pupil"], answer: 0 },
  { q: "The near point of a normal eye is:", options: ["25 cm", "25 m", "2.5 cm", "infinity"], answer: 0 },
  { q: "Myopia is corrected with a:", options: ["concave lens", "convex lens", "bifocal lens", "plane lens"], answer: 0 },
  { q: "The blue sky is due to:", options: ["scattering of light", "reflection", "dispersion at night", "refraction only"], answer: 0 },
  { q: "Splitting of white light by a prism is called:", options: ["dispersion", "reflection", "scattering", "absorption"], answer: 0 },
 ],
 "science-0-10": [
  { q: "The unit of resistance is the:", options: ["ohm", "volt", "ampere", "watt"], answer: 0 },
  { q: "V = IR is the statement of:", options: ["Ohm's law", "Newton's law", "Faraday's law", "Hooke's law"], answer: 0 },
  { q: "In series combination, resistances:", options: ["add up", "divide", "stay same", "become zero"], answer: 0 },
  { q: "The SI unit of electric power is the:", options: ["watt", "joule", "volt", "ohm"], answer: 0 },
  { q: "Current is measured in:", options: ["amperes", "volts", "ohms", "coulombs per metre"], answer: 0 },
 ],
 "science-0-11": [
  { q: "Magnetic field lines emerge from the:", options: ["north pole", "south pole", "middle", "wire"], answer: 0 },
  { q: "A generator converts:", options: ["mechanical to electrical energy", "electrical to mechanical", "heat to light", "light to heat"], answer: 0 },
  { q: "An electric motor converts:", options: ["electrical to mechanical energy", "mechanical to electrical", "chemical to light", "sound to electric"], answer: 0 },
  { q: "A fuse protects a circuit from:", options: ["overloading", "under-voltage", "magnetism", "friction"], answer: 0 },
  { q: "The right-hand thumb rule relates:", options: ["current and its magnetic field", "force and mass", "heat and light", "voltage and power"], answer: 0 },
 ],
 "science-0-12": [
  { q: "The ozone layer protects us from:", options: ["UV radiation", "oxygen", "rain", "wind"], answer: 0 },
  { q: "Producers in an ecosystem are:", options: ["green plants", "lion", "fungi", "worms"], answer: 0 },
  { q: "The 10% law concerns:", options: ["energy transfer between trophic levels", "water cycle", "ozone loss", "soil erosion"], answer: 0 },
  { q: "A biodegradable item is:", options: ["paper", "plastic", "glass", "polythene"], answer: 0 },
  { q: "Every food chain starts with a:", options: ["producer", "carnivore", "decomposer", "parasite"], answer: 0 },
 ],
};
