/* Science — NCERT Class 10 (jesc1), chapters 2–13 (ch.1 Chemical Reactions is in builtin).
   Keys: science-0-x. Framework/quiz in English. */
import type { ChapterDetail } from "./types";

export const SCIENCE: Record<string, ChapterDetail> = {

"science-0-1": {
  slides: [
    { kicker: "Science Ch.2 • Chemistry", title: "Acids, Bases and Salts",
      points: ["Acids taste sour, turn blue litmus red — release H⁺ (H₃O⁺) ions in water", "Bases taste bitter, turn red litmus blue — release OH⁻ ions", "Neutralisation: acid + base → salt + water", "Indicators: litmus, methyl orange, phenolphthalein + olfactory (onion, vanilla)"], formula: "Acid + Base → Salt + Water" },
    { kicker: "The pH Scale", title: "0 to 14 — Measure of Strength",
      points: ["pH < 7 acidic • 7 neutral • > 7 basic", "Strong acids: HCl, H₂SO₄, HNO₃ (fully ionise); weak: CH₃COOH, H₂CO₃", "Strong bases: NaOH, KOH; weak: NH₄OH", "Lower pH = stronger acid; higher pH = stronger base"], formula: "pH < 7 acid • 7 neutral • > 7 base" },
    { kicker: "Salts", title: "Everyday Salt Chemistry",
      points: ["Common salt NaCl → chlor-alkali process gives NaOH + Cl₂ + H₂", "Baking soda NaHCO₃ — mild base: antacid, baking powder", "Washing soda Na₂CO₃·10H₂O — removes permanent hardness of water", "Plaster of Paris CaSO₄·½H₂O — sets into hard gypsum with water"], formula: "2NaCl + 2H₂O → 2NaOH + Cl₂ + H₂" },
    { kicker: "pH in Life", title: "Why pH Matters Daily",
      points: ["Tooth decay starts when mouth pH drops below 5.5 — brush after meals", "Indigestion → antacid (Mg(OH)₂ / NaHCO₃) neutralises excess HCl", "Acid rain (pH < 5.6) corrodes marble & kills aquatic life", "Plants grow best at soil pH 6–8; acidic soil is treated with quicklime"], formula: "Mg(OH)₂ + 2HCl → MgCl₂ + 2H₂O" },
  ],
  mindmap: { central: "Acids, Bases & Salts",
    branches: [
      { label: "Indicators", color: "#1a73e8", children: ["Litmus: acid→red, base→blue", "Phenolphthalein: base→pink", "Methyl orange: acid→red/pink", "Olfactory: onion, vanilla"] },
      { label: "pH Scale", color: "#e37400", children: ["0–14 range", "Tooth decay < 5.5", "Acid rain < 5.6", "Blood ≈ 7.4"] },
      { label: "Reactions", color: "#146c2e", children: ["Acid + metal → H₂", "Acid + carbonate → CO₂", "Neutralisation", "Acid + base oxide → salt + water"] },
      { label: "Important Salts", color: "#9334e6", children: ["NaCl — common salt", "NaHCO₃ — baking soda", "Na₂CO₃·10H₂O — washing soda", "CaOCl₂ — bleaching powder", "CaSO₄·½H₂O — Plaster of Paris"] },
    ] },
  flowchart: [
    { title: "Base in the flask", desc: "NaOH + 2 drops of phenolphthalein → pink" },
    { title: "Add acid drop by drop", desc: "dilute HCl from the burette, keep swirling", type: "decision" },
    { title: "Endpoint", desc: "pink colour just disappears — no excess base left" },
    { title: "Neutralisation complete", desc: "salt (NaCl) + water formed", type: "result" },
  ],
  formulas: [
    { name: "Neutralisation", expr: "Acid + Base → Salt + Water" },
    { name: "Acid + Metal", expr: "2HCl + Zn → ZnCl₂ + H₂↑" },
    { name: "Acid + Carbonate", expr: "Na₂CO₃ + 2HCl → 2NaCl + H₂O + CO₂↑" },
    { name: "Chlor-alkali (brine electrolysis)", expr: "2NaCl + 2H₂O → 2NaOH + Cl₂ + H₂" },
    { name: "Bleaching powder", expr: "Ca(OH)₂ + Cl₂ → CaOCl₂ + H₂O" },
    { name: "Baking soda on heating", expr: "2NaHCO₃ → Na₂CO₃ + H₂O + CO₂" },
    { name: "Antacid action", expr: "Mg(OH)₂ + 2HCl → MgCl₂ + 2H₂O" },
  ],
  diagrams: [
    { title: "pH Scale", desc: "0–14 scale: battery acid ≈ 1, lemon ≈ 2.2, stomach acid ≈ 1.5–3, pure water 7, blood ≈ 7.4, soap ≈ 10, drain cleaner ≈ 14", label: "Lower pH = stronger acid" },
    { title: "Conduction test", desc: "Acid/base solutions glow the bulb (free ions); glucose and alcohol solutions do not — they do not ionise", label: "Acids conduct, covalent compounds do not" },
  ],
  notes: [
    "Acids produce <b>H⁺ ions only in aqueous solution</b> — that is why dry HCl gas does not turn litmus red.",
    "Olfactory indicators like <b>onion and vanilla</b> lose their smell in a basic solution — helpful for visually impaired students.",
    "Plaster of Paris + water → gypsum: <b>CaSO₄·½H₂O + 1½H₂O → CaSO₄·2H₂O</b> — an exothermic setting reaction.",
    "Water of crystallisation: blue <b>CuSO₄·5H₂O</b> turns white on heating and blue again when water is added back.",
    "Strong acid + weak base → acidic salt (NH₄Cl); weak acid + strong base → basic salt (Na₂CO₃, CH₃COONa).",
  ],
  quiz: [
    { q: "A solution turns red litmus blue. Its pH is likely to be:", options: ["4", "1", "10", "5"], answer: 2, why: "Only a basic solution turns red litmus blue; pH 10 is basic." },
    { q: "Dilute HCl reacts with sodium carbonate to give:", options: ["H₂", "O₂", "CO₂", "SO₂"], answer: 2, why: "Acid + carbonate → salt + water + carbon dioxide." },
    { q: "The chlor-alkali process produces:", options: ["NaOH, Cl₂ and H₂", "NaCl, H₂ and O₂", "NaOH, HCl and H₂O", "Na₂CO₃, Cl₂ and H₂"], answer: 0, why: "Electrolysis of brine: Cl₂ at anode, H₂ at cathode, NaOH remains in solution." },
  ],
  pyq: [
    "A white powder is added while baking breads and cakes to make them soft and spongy. Name the powder and write its reaction on heating. (CBSE 2023, 3m)",
    "Why does tooth decay start when the pH of the mouth is lower than 5.5? How can it be prevented? (CBSE 2022, 2m)",
    "What is the chemical name and formula of washing soda? How is it prepared? (CBSE 2020, 3m)",
  ],
},

"science-0-2": {
  slides: [
    { kicker: "Science Ch.3 • Chemistry", title: "Metals and Non-metals",
      points: ["Metals: lustrous, malleable, ductile, sonorous, good conductors of heat & electricity", "Famous exceptions: iodine (shiny non-metal), graphite (conducting non-metal), mercury (liquid metal), sodium (soft metal)", "Non-metals: brittle, non-sonorous, poor conductors (except graphite)", "Metals form cations (+), non-metals form anions (−)"], formula: "Metal → loses e⁻ • Non-metal → gains e⁻" },
    { kicker: "Reactivity", title: "The Reactivity Series",
      points: ["K > Na > Ca > Mg > Al > Zn > Fe > Pb > (H) > Cu > Hg > Ag > Au", "Displacement: a more reactive metal pushes out a less reactive one from its salt solution", "K, Na, Ca react with cold water; Mg with hot water/steam; Zn, Fe with steam only; Cu, Ag, Au never", "Least reactive metals (Au, Pt) are found free in nature"], formula: "K Na Ca Mg Al Zn Fe Pb H Cu Hg Ag Au" },
    { kicker: "Extraction", title: "From Ore to Metal",
      points: ["Ionic compounds: high melting points, conduct electricity when molten or dissolved", "Roasting: sulphide ore + O₂ → oxide (2ZnS + 3O₂ → 2ZnO + 2SO₂)", "Calcination: carbonate ore → oxide + CO₂ (ZnCO₃ → ZnO + CO₂)", "Highly reactive metals (Na, Al) need electrolytic reduction; then electrolytic refining purifies"], formula: "Roast/calcine → reduce → refine" },
    { kicker: "Corrosion & Alloys", title: "Protecting Metals",
      points: ["Rust = hydrated iron(III) oxide — needs BOTH air and moisture", "Prevention: painting, oiling, galvanisation (zinc coating), alloying, electroplating", "Alloys: brass (Cu+Zn), bronze (Cu+Sn), solder (Pb+Sn), stainless steel (Fe+Cr+Ni)", "Amalgam = alloy with mercury; alloying lowers reactivity & improves strength"], formula: "Thermite: Fe₂O₃ + 2Al → 2Fe + Al₂O₃ + heat" },
  ],
  mindmap: { central: "Metals & Non-metals",
    branches: [
      { label: "Physical props", color: "#1a73e8", children: ["Malleable, ductile, sonorous", "Exceptions: iodine, graphite, mercury"] },
      { label: "Reactivity series", color: "#c5221f", children: ["K Na Ca Mg Al Zn Fe Pb", "(H) Cu Hg Ag Au", "Displacement reactions", "K/Na/Ca + cold water"] },
      { label: "Extraction", color: "#e37400", children: ["Concentration of ore", "Roasting (sulphides)", "Calcination (carbonates)", "Reduction → refining"] },
      { label: "Corrosion & Alloys", color: "#146c2e", children: ["Rust needs air + moisture", "Galvanisation (Zn)", "Brass, bronze, solder", "Thermite welding"] },
    ] },
  flowchart: [
    { title: "Concentrate the ore", desc: "remove gangue — froth flotation / hydraulic washing" },
    { title: "Convert to oxide", desc: "roasting (sulphide ores) or calcination (carbonate ores)" },
    { title: "Reduce the oxide", desc: "heat with C/CO (Zn, Fe, Pb) or electrolysis (Na, Al)", type: "decision" },
    { title: "Refine the metal", desc: "electrolytic refining — pure metal deposits at the cathode", type: "result" },
  ],
  formulas: [
    { name: "Roasting", expr: "2ZnS + 3O₂ → 2ZnO + 2SO₂" },
    { name: "Calcination", expr: "ZnCO₃ → ZnO + CO₂" },
    { name: "Thermite reaction", expr: "Fe₂O₃ + 2Al → 2Fe + Al₂O₃ + heat" },
    { name: "Sodium + water", expr: "2Na + 2H₂O → 2NaOH + H₂" },
    { name: "Displacement", expr: "Fe + CuSO₄ → FeSO₄ + Cu" },
  ],
  diagrams: [
    { title: "Electrolytic refining", desc: "Thick impure metal = anode, thin pure strip = cathode, acidified CuSO₄ = electrolyte; metal dissolves from the anode and deposits on the cathode; insoluble impurities settle as anode mud", label: "Cathode: pure • Anode: impure" },
    { title: "Displacement in action", desc: "An iron nail dipped in blue CuSO₄ solution gets a brown copper coating and the solution turns green (FeSO₄)", label: "Fe is above Cu in the series" },
  ],
  notes: [
    "Learn the series with a mnemonic — <b>K Na Ca Mg Al Zn Fe Pb (H) Cu Hg Ag Au</b>.",
    "Ionic compounds are hard crystalline lattices — strong electrostatic forces give <b>high melting points</b>; ions are free only when molten/dissolved.",
    "Aqua regia (3 HCl : 1 HNO₃) is the only aqueous mixture that dissolves <b>gold and platinum</b>.",
    "Amphoteric oxides: <b>Al₂O₃ and ZnO</b> react with both acids and bases.",
    "Galvanised iron stays protected even when scratched because <b>zinc is more reactive</b> and corrodes first (sacrificial protection).",
  ],
  quiz: [
    { q: "Which metal is usually found in its free state in nature?", options: ["Sodium", "Gold", "Iron", "Zinc"], answer: 1, why: "Gold is least reactive, so it rarely forms compounds." },
    { q: "Galvanisation is the coating of iron with:", options: ["Tin", "Chromium", "Zinc", "Copper"], answer: 2, why: "Zinc protects iron sacrificially even after scratches." },
    { q: "The thermite reaction is used to:", options: ["Paint rails", "Weld broken machine parts and rails", "Galvanise iron", "Refine copper"], answer: 1, why: "It produces molten iron from Fe₂O₃ + Al — perfect for welding." },
  ],
  pyq: [
    "Why do ionic compounds have high melting points and conduct electricity in the molten state? (CBSE 2023, 2m)",
    "Differentiate between roasting and calcination with one example each. (CBSE 2022, 3m)",
    "Name the ores of mercury and aluminium and describe how aluminium ore is concentrated. (CBSE 2020, 3m)",
  ],
},

"science-0-3": {
  slides: [
    { kicker: "Science Ch.4 • Chemistry", title: "Carbon and its Compounds",
      points: ["Carbon (Z = 6): tetravalent — forms 4 covalent bonds", "Catenation: C–C bonds make chains and rings → millions of compounds", "Allotropes: diamond (hardest, non-conductor), graphite (soft, conducts — free electron), fullerene C₆₀", "Covalent compounds: low melting/boiling points, poor conductors"], formula: "Covalent bond = shared pair of electrons" },
    { kicker: "Families", title: "Homologous Series",
      points: ["Alkanes CₙH₂ₙ₊₂ (CH₄, C₂H₆…), Alkenes CₙH₂ₙ (C₂H₄), Alkynes CₙH₂ₙ₋₂ (C₂H₂)", "Adjacent members differ by –CH₂– (mass difference 14 u)", "Members show gradation in physical properties and similar chemical properties", "Naming: meth-, eth-, prop-, but-, pent- + -ane/-ene/-yne"], formula: "CH₄ → C₂H₆ → C₃H₈ (+CH₂ each step)" },
    { kicker: "Functional Groups", title: "Versatility of Carbon Chains",
      points: ["–OH alcohol (ethanol C₂H₅OH) • –COOH carboxylic acid (ethanoic acid CH₃COOH)", "–CHO aldehyde • –CO– ketone • –X haloalkane", "–C=C– and –C≡C– give unsaturation (decolourise bromine water)", "Functional group decides chemical behaviour"], formula: "Ethanol C₂H₅OH • Ethanoic acid CH₃COOH" },
    { kicker: "Soap Science", title: "Soaps and Detergents",
      points: ["Soap = Na/K salt of a long-chain fatty acid (e.g. sodium stearate C₁₇H₃₅COONa)", "Micelle: hydrophobic tails trap oil; hydrophilic heads face water → dirt lifted", "Hard water: Ca²⁺/Mg²⁺ make insoluble scum with soap; detergents avoid this", "Soaps are biodegradable; many detergents are not"], formula: "Saponification: ester + NaOH → soap + alcohol" },
  ],
  mindmap: { central: "Carbon & its Compounds",
    branches: [
      { label: "Bonding", color: "#1a73e8", children: ["Covalent bonds", "Tetravalency", "Catenation", "Allotropes: diamond, graphite, C₆₀"] },
      { label: "Series", color: "#e37400", children: ["Alkanes CₙH₂ₙ₊₂", "Alkenes CₙH₂ₙ", "Alkynes CₙH₂ₙ₋₂", "+CH₂ = next member"] },
      { label: "Functional groups", color: "#146c2e", children: ["–OH alcohol", "–CHO aldehyde", "–COOH acid", "–CO– ketone", "–C=C–, –C≡C–"] },
      { label: "Ethanol & Acid", color: "#9334e6", children: ["Na → H₂", "Dehydration → ethene", "Esterification (sweet smell)", "CH₃COOH + NaHCO₃ → CO₂"] },
      { label: "Soap", color: "#c5221f", children: ["Micelle", "Hard water → scum", "Tail hydrophobic", "Head hydrophilic"] },
    ] },
  flowchart: [
    { title: "Soap meets water", desc: "molecules surround greasy dirt; tails stick into the oil" },
    { title: "Micelle forms", desc: "oil droplet trapped inside, heads facing the water", type: "decision" },
    { title: "Rinse", desc: "water pulls the hydrophilic heads — the micelle lifts off the cloth" },
    { title: "Dirt removed", desc: "dirt stays suspended in water and washes away", type: "result" },
  ],
  formulas: [
    { name: "Combustion of ethanol", expr: "C₂H₅OH + 3O₂ → 2CO₂ + 3H₂O + heat" },
    { name: "Ethanol + sodium", expr: "2C₂H₅OH + 2Na → 2C₂H₅ONa + H₂" },
    { name: "Dehydration (443 K, conc. H₂SO₄)", expr: "C₂H₅OH → C₂H₄ + H₂O" },
    { name: "Esterification", expr: "CH₃COOH + C₂H₅OH ⇌ CH₃COOC₂H₅ + H₂O" },
    { name: "Saponification", expr: "CH₃COOC₂H₅ + NaOH → CH₃COONa + C₂H₅OH" },
    { name: "Acid + bicarbonate", expr: "CH₃COOH + NaHCO₃ → CH₃COONa + H₂O + CO₂" },
  ],
  diagrams: [
    { title: "Micelle formation", desc: "Soap molecules arrange with hydrophobic tails pointing into the oily dirt and hydrophilic heads outward — a spherical cluster (micelle) that stays suspended in water", label: "Tail loves oil • Head loves water" },
  ],
  notes: [
    "Graphite conducts: each carbon bonds to only 3 others, leaving <b>one free delocalised electron</b>; layers slide → lubricant.",
    "Ethanol → ethene by <b>dehydration with hot concentrated H₂SO₄ at 443 K</b>.",
    "Esters are sweet-smelling and used in <b>perfumes and food flavourings</b>; hydrolysing an ester with NaOH gives soap.",
    "Hydrogenation: unsaturated vegetable oil + H₂ (Ni catalyst, 473 K) → vanaspati ghee — the same chemistry hides harmful <b>trans fats</b> in partial hydrogenation.",
    "Denatured alcohol = ethanol + methanol + dye/poison — made unfit for drinking.",
    "Ethanoic acid is a weak acid; it turns litmus red but reacts slowly compared to dilute HCl.",
  ],
  quiz: [
    { q: "The bond in ethyne (C₂H₂) between the carbon atoms is:", options: ["Single", "Double", "Triple", "Ionic"], answer: 2, why: "H–C≡C–H — one σ and two π bonds." },
    { q: "Which pair belongs to the same homologous series?", options: ["CH₄ and C₂H₄", "C₂H₆ and C₃H₈", "C₂H₄ and C₂H₆", "CH₄ and CH₃OH"], answer: 1, why: "Both are alkanes differing by one –CH₂– unit." },
    { q: "Soaps are ineffective in hard water because they form:", options: ["Lather", "Micelles", "Scum with Ca²⁺/Mg²⁺", "Esters"], answer: 2, why: "Calcium/magnesium salts of fatty acids are insoluble — that is scum." },
  ],
  pyq: [
    "Both diamond and graphite are allotropes of carbon, yet only graphite conducts electricity. Explain. (CBSE 2023, 2m)",
    "What is a homologous series? Write the first three members of the alkanes. (CBSE 2022, 3m)",
    "Explain the cleansing action of soap with a labelled diagram of a micelle. (CBSE 2020, 5m)",
  ],
},

"science-0-4": {
  slides: [
    { kicker: "Science Ch.5 • Biology", title: "Life Processes",
      points: ["The processes that keep living beings alive: nutrition, respiration, transportation, excretion (+ control & reproduction)", "Autotrophic nutrition = photosynthesis in green plants (chlorophyll + sunlight)", "Heterotrophic: holozoic (amoeba, humans), saprophytic (fungi on dead matter), parasitic (Cuscuta, ticks, leech)", "Amoeba: pseudopodia engulf food → food vacuole → diffusion of nutrients"], formula: "6CO₂ + 6H₂O → C₆H₁₂O₆ + 6O₂" },
    { kicker: "Nutrition", title: "The Human Digestive System",
      points: ["Mouth: salivary amylase converts starch → maltose", "Stomach: HCl (pH ≈ 1.5) activates pepsin; mucus protects the lining", "Small intestine: bile (liver) emulsifies fats & makes medium alkaline; pancreatic juice (trypsin, amylase, lipase)", "Villi (finger-like) maximise absorption; large intestine absorbs water"], formula: "Bile = emulsifier + alkaline medium" },
    { kicker: "Respiration", title: "Releasing Energy from Food",
      points: ["Aerobic: glucose + O₂ → CO₂ + H₂O + 38 ATP (mitochondria)", "Anaerobic in yeast: glucose → ethanol + CO₂ + 2 ATP (fermentation)", "Anaerobic in muscles: glucose → lactic acid (cramps!) + energy", "Breathing vs respiration: breathing is gas exchange; respiration is energy release"], formula: "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + 38 ATP" },
    { kicker: "Transport & Excretion", title: "Heart, Vessels and Nephrons",
      points: ["Heart: 4 chambers, double circulation, valves prevent backflow; left ventricle has the thickest wall", "Blood: RBC (haemoglobin, no nucleus), WBC (defence), platelets (clotting), plasma; lymph drains extra fluid", "Plants: xylem — water & minerals (transpiration pull); phloem — food (translocation, needs ATP)", "Excretion: nephron = glomerulus (filtration) → selective reabsorption → urine; kidney failure → dialysis"], formula: "Filtration → selective reabsorption → urine" },
  ],
  mindmap: { central: "Life Processes",
    branches: [
      { label: "Nutrition", color: "#146c2e", children: ["Photosynthesis", "Amoeba (food vacuole)", "Human: amylase, pepsin, bile, villi"] },
      { label: "Respiration", color: "#c5221f", children: ["Aerobic: 38 ATP", "Yeast: ethanol + CO₂", "Muscle: lactic acid", "Breakdown of glucose first step"] },
      { label: "Transportation", color: "#1a73e8", children: ["Double circulation", "Xylem: transpiration pull", "Phloem: translocation (ATP)", "Lymph"] },
      { label: "Excretion", color: "#e37400", children: ["Nephron — functional unit", "Glomerulus filters", "Selective reabsorption", "Dialysis"] },
    ] },
  flowchart: [
    { title: "Mouth", desc: "teeth grind; salivary amylase digests starch" },
    { title: "Stomach", desc: "HCl + pepsin digest proteins into smaller peptides" },
    { title: "Small intestine", desc: "bile + pancreatic + intestinal juices complete digestion", type: "decision" },
    { title: "Absorption by villi", desc: "nutrients pass into blood", type: "result" },
    { title: "Large intestine", desc: "water absorbed; undigested residue egested" },
  ],
  formulas: [
    { name: "Photosynthesis", expr: "6CO₂ + 6H₂O →(light, chlorophyll) C₆H₁₂O₆ + 6O₂" },
    { name: "Aerobic respiration", expr: "C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + 38 ATP" },
    { name: "Anaerobic (yeast)", expr: "C₆H₁₂O₆ → 2C₂H₅OH + 2CO₂ + energy" },
    { name: "Anaerobic (muscle)", expr: "C₆H₁₂O₆ → 2 lactic acid + energy" },
  ],
  diagrams: [
    { title: "Human digestive system", desc: "Mouth → oesophagus → stomach → small intestine (duodenum + ileum with villi) → large intestine → rectum; liver and pancreas pour juices into the duodenum", label: "Small intestine ≈ 6 m — the longest part" },
    { title: "Nephron", desc: "Glomerulus in Bowman's capsule (filtration under pressure) → proximal tubule → loop of Henle → distal tubule → collecting duct → ureter → bladder", label: "99% of the filtrate is reabsorbed" },
    { title: "Human heart", desc: "Right atrium → right ventricle → lungs (pulmonary artery); oxygenated blood returns → left atrium → left ventricle → aorta to the body", label: "Double circulation: blood passes the heart twice per cycle" },
  ],
  notes: [
    "Photosynthesis happens in <b>chloroplasts</b>; CO₂ enters through stomata, whose guard cells control the opening.",
    "The <b>left ventricle</b> has the thickest muscular wall — it pumps blood to the entire body.",
    "Arteries carry blood away from the heart (usually oxygenated, thick walls); veins return it (valves, thin walls).",
    "Plants excrete through <b>stomata (O₂/CO₂), transpiration (water vapour)</b> and by storing wastes in leaves/bark/resin.",
    "Urea forms in the <b>liver</b> from protein metabolism and is removed by the kidneys.",
    "Lactic acid in muscles after heavy exercise causes cramps — cured by a hot water bath (improves circulation, oxygen supply).",
  ],
  quiz: [
    { q: "Which enzyme digests proteins in the stomach?", options: ["Amylase", "Trypsin", "Pepsin", "Lipase"], answer: 2, why: "Pepsin works in acidic pH ~1.5; trypsin acts later in the small intestine." },
    { q: "Lactic acid forms in muscles when:", options: ["O₂ supply is sufficient", "O₂ supply is deficient", "Glucose runs out", "Blood pH rises"], answer: 1, why: "Anaerobic respiration in muscle cells produces lactic acid — cramps." },
    { q: "Food (sucrose) is transported in plants through:", options: ["Xylem", "Phloem", "Stomata", "Cambium"], answer: 1, why: "Phloem translocates food using ATP — the translocation process." },
  ],
  pyq: [
    "Draw a labelled diagram of the human digestive system and state the role of the liver. (CBSE 2023, 5m)",
    "Why is the small intestine long and internally folded into villi? (CBSE 2022, 2m)",
    "How do plants transport water and minerals from roots to leaves against gravity? (CBSE 2020, 3m)",
  ],
},

"science-0-5": {
  slides: [
    { kicker: "Science Ch.6 • Biology", title: "Control and Coordination",
      points: ["Path: stimulus → receptor → sensory neuron → CNS → motor neuron → response (muscle/gland)", "CNS = brain + spinal cord; PNS = cranial + spinal nerves", "Neuron: dendrites (receive) → cell body → axon (impulse) → synapse (chemical gap)", "Reflex actions are fast & involuntary — the spinal cord decides instantly"], formula: "Reflex arc: receptor → spinal cord → muscle" },
    { kicker: "The Brain", title: "Command Centres",
      points: ["Forebrain: cerebrum (thinking, memory, voluntary action) + hypothalamus (hunger, thirst, sleep, temperature)", "Midbrain: involuntary — pupil reflex, head/eye movement", "Hindbrain: cerebellum (posture, balance), medulla (heartbeat, breathing, BP, vomiting)", "Protection: bony skull + cerebrospinal fluid (shock absorber)"], formula: "Medulla runs life; cerebellum runs balance" },
    { kicker: "Hormones", title: "Chemical Messengers",
      points: ["Thyroxine (thyroid, needs iodine) — iodine deficiency = goitre", "Insulin (pancreas) lowers blood sugar; deficiency = diabetes", "Adrenaline (adrenal) — emergency: heartbeat↑, breathing↑, digestion↓", "Growth hormone (pituitary — the master gland): too little = dwarfism, too much = gigantism", "Testosterone (testes) & oestrogen (ovaries) — puberty changes"], formula: "Feedback keeps hormone levels in balance" },
    { kicker: "Plants", title: "Coordination Without Nerves",
      points: ["Tropism (directional growth): phototropism (shoot +light), geotropism (root +gravity), hydrotropism, chemotropism (pollen tube)", "Nastic movement (non-directional, no growth): Mimosa leaves fold on touch", "Auxin bends the shoot tip toward light; gibberellin (stem growth), cytokinin (cell division), abscisic acid (wilting, inhibits growth)"], formula: "Auxin accumulates on the shady side → bend" },
  ],
  mindmap: { central: "Control & Coordination",
    branches: [
      { label: "Nervous system", color: "#1a73e8", children: ["Neuron & synapse", "Reflex arc", "CNS: brain + spinal cord", "PNS: nerves"] },
      { label: "Brain", color: "#9334e6", children: ["Cerebrum: thinking", "Hypothalamus: hunger/thirst", "Cerebellum: balance", "Medulla: involuntary"] },
      { label: "Hormones", color: "#c5221f", children: ["Thyroxine (goitre)", "Insulin (diabetes)", "Adrenaline (emergency)", "GH, testosterone, oestrogen"] },
      { label: "Plants", color: "#146c2e", children: ["Phototropism, geotropism", "Mimosa: nastic", "Auxin, gibberellin", "Cytokinin, abscisic acid"] },
    ] },
  flowchart: [
    { title: "Stimulus", desc: "your hand touches a hot pan" },
    { title: "Receptor", desc: "heat receptors in the skin fire an impulse" },
    { title: "Sensory neuron → spinal cord", desc: "relay neuron passes it on instantly", type: "decision" },
    { title: "Motor neuron → muscle", desc: "hand is pulled away before you consciously feel pain", type: "result" },
    { title: "Brain informed", desc: "you 'feel' the burn a moment later" },
  ],
  diagrams: [
    { title: "Neuron structure", desc: "Dendrites receive → cell body (nucleus) → axon insulated by a myelin sheath → nerve endings → synapse; neurotransmitters cross the synaptic gap", label: "Signal: electrical along the neuron, chemical across the synapse" },
    { title: "Human brain", desc: "Cerebrum (largest, thinking), cerebellum (balance/posture at the back-base), medulla (involuntary centres), hypothalamus below the cerebrum; spinal cord continues below", label: "Sketch the side view for exams" },
  ],
  notes: [
    "Reflex examples: <b>knee-jerk, blinking, coughing, sneezing, withdrawing from heat</b>.",
    "Use <b>iodised salt</b> — thyroxine needs iodine; its deficiency causes goitre.",
    "Insulin is a protein, so it must be <b>injected, not swallowed</b> (digestive enzymes would destroy it).",
    "Adrenaline + sympathetic nervous system together prepare <b>'fight or flight'</b> — an example of the two systems working as one.",
    "Root shows positive geotropism AND positive hydrotropism; shoot shows positive phototropism.",
    "Mimosa signal travels as an electrical impulse, then chemicals make cells lose water — leaves droop in seconds.",
  ],
  quiz: [
    { q: "Which part of the brain maintains posture and balance?", options: ["Cerebrum", "Cerebellum", "Medulla", "Hypothalamus"], answer: 1, why: "The cerebellum (hindbrain) coordinates voluntary movement, posture and balance." },
    { q: "The tiny gap between two neurons is the:", options: ["Axon", "Dendrite", "Synapse", "Nerve ending"], answer: 2, why: "Neurotransmitters cross the synapse chemically." },
    { q: "A shoot bends toward light because of:", options: ["Gibberellin", "Cytokinin", "Auxin", "Abscisic acid"], answer: 2, why: "Auxin moves to the shaded side → cells there elongate more → bend toward light." },
  ],
  pyq: [
    "Draw a labelled reflex arc and explain how a reflex action occurs. (CBSE 2023, 5m)",
    "Why is iodised salt advisable? Name the disease caused by iodine deficiency. (CBSE 2022, 2m)",
    "Compare nervous control with hormonal control for speed and duration of response. (CBSE 2020, 3m)",
  ],
},

"science-0-6": {
  slides: [
    { kicker: "Science Ch.7 • Biology", title: "How do Organisms Reproduce?",
      points: ["Reproduction is not essential for the individual's survival, but essential for the species", "Asexual (1 parent, clone): fission (amoeba), budding (yeast, hydra), fragmentation (spirogyra), regeneration (planaria), spore formation (rhizopus), vegetative propagation", "Sexual reproduction: 2 gametes fuse → variation → better survival in changing conditions", "Basic event: DNA copying — with small errors (variations) each generation"], formula: "Variation is the raw material of evolution" },
    { kicker: "Plants", title: "Sexual Reproduction in Flowering Plants",
      points: ["Stamen (male): anther (pollen) + filament; Carpel (female): stigma + style + ovary (ovules)", "Pollination: self and cross (wind, water, insects as agents)", "Pollen grain on stigma → pollen tube grows down the style (chemotropism) → male gamete + egg → zygote", "After fertilisation: ovule → seed, ovary → fruit; zygote → embryo"], formula: "Pollen (n) + Egg (n) → Zygote (2n)" },
    { kicker: "Humans", title: "The Human Reproductive System",
      points: ["Male: testes (in the scrotum — cooler, make sperm + testosterone), vas deferens, glands, urethra", "Female: ovaries (eggs + oestrogen), fallopian tube (fertilisation site), uterus (implantation)", "Placenta: villi-rich disc — food, O₂ and waste exchange between mother and embryo", "Gestation ≈ 9 months; puberty → menarche; menstrual cycle ≈ 28 days"], formula: "Placenta = the baby's lifeline" },
    { kicker: "Health", title: "Reproductive Health",
      points: ["Contraception: barrier (condom — also blocks STDs), hormonal pills, IUCD (Copper-T), surgical (vasectomy/tubectomy)", "STDs: bacterial — gonorrhoea, syphilis; viral — HIV, genital warts", "Avoid early pregnancy — health risks + life goals", "Sex determination & female foeticide are illegal (PCPNDT Act) — falling child-sex ratio is a serious concern"], formula: "Condom = only method that also stops STDs" },
  ],
  mindmap: { central: "Reproduction",
    branches: [
      { label: "Asexual", color: "#1a73e8", children: ["Fission — amoeba", "Budding — yeast, hydra", "Fragmentation — spirogyra", "Regeneration — planaria", "Spores — rhizopus", "Vegetative — potato eyes"] },
      { label: "Flower", color: "#e37400", children: ["Stamen & carpel", "Pollination", "Pollen tube", "Seed & fruit"] },
      { label: "Human", color: "#c5221f", children: ["Testes/ovaries", "Fallopian tube", "Placenta", "9-month gestation"] },
      { label: "Health", color: "#146c2e", children: ["Condom, pills, Copper-T", "Vasectomy/tubectomy", "HIV, gonorrhoea", "PCPNDT Act"] },
    ] },
  flowchart: [
    { title: "Pollination", desc: "pollen grain lands on a sticky stigma" },
    { title: "Pollen tube grows", desc: "down the style toward an ovule (chemotropism)" },
    { title: "Fertilisation", desc: "male gamete fuses with the egg inside the ovule", type: "decision" },
    { title: "Seed & fruit", desc: "zygote → embryo; ovule → seed; ovary → fruit", type: "result" },
  ],
  diagrams: [
    { title: "L.S. of a flower", desc: "Stamens (anther + filament) surround the carpel (stigma + style + ovary containing ovules)", label: "Bisexual flowers: hibiscus, mustard" },
    { title: "Human reproductive systems", desc: "Male: testes → epididymis → vas deferens → urethra. Female: ovary → fallopian tube → uterus → cervix → vagina", label: "Fertilisation happens in the fallopian tube" },
  ],
  notes: [
    "Vegetative propagation (rose, sugarcane, banana) preserves the parent's exact qualities — <b>banana and seedless grapes exist only because of it</b>.",
    "Regeneration is not reproduction — <b>planaria</b> regrows from pieces, but that is growth of a new individual only when it fully forms.",
    "The embryo draws nutrition through the <b>placenta</b>; its villi hugely increase the exchange surface.",
    "Condoms are the only contraceptive that <b>also prevents STDs</b> including HIV.",
    "Menopause (≈ 45–50 years) ends the female reproductive phase; menarche begins it.",
    "Why sexual reproduction dominates in complex organisms: <b>variations help species survive environmental change</b>.",
  ],
  quiz: [
    { q: "Rhizopus (bread mould) reproduces by:", options: ["Budding", "Spore formation", "Fragmentation", "Binary fission"], answer: 1, why: "Sporangia release spores that float in air and grow on moist bread." },
    { q: "In humans, fertilisation normally occurs in the:", options: ["Uterus", "Ovary", "Fallopian tube", "Vagina"], answer: 2, why: "Sperm meets the egg in the oviduct; the zygote then travels to the uterus." },
    { q: "Which contraceptive also protects against STDs?", options: ["Copper-T", "Oral pills", "Condom", "Tubectomy"], answer: 2, why: "The barrier method stops the exchange of body fluids." },
  ],
  pyq: [
    "What is vegetative propagation? Write two advantages of using it. (CBSE 2023, 3m)",
    "Trace the events in a flower from pollination to seed formation with a labelled L.S. diagram. (CBSE 2022, 5m)",
    "How does the embryo receive nourishment inside the mother's body? (CBSE 2020, 3m)",
  ],
},

"science-0-7": {
  slides: [
    { kicker: "Science Ch.8 • Biology", title: "Heredity",
      points: ["Heredity = transmission of traits via genes (DNA segments on chromosomes)", "Gregor Mendel chose garden pea (Pisum sativum): 7 pairs of contrasting traits, self-pollinating, fast", "Alleles: TT (homozygous tall), Tt (heterozygous tall), tt (dwarf); genotype vs phenotype", "Monohybrid cross TT × tt → F₁ all Tt (tall) → F₂ 3 tall : 1 dwarf"], formula: "Monohybrid: phenotype 3:1, genotype 1:2:1" },
    { kicker: "Mendel's Laws", title: "Three Rules of Inheritance",
      points: ["Law of dominance: F₁ shows only the dominant allele", "Law of segregation: the two alleles separate during gamete formation — each gamete carries one (purity of gametes)", "Law of independent assortment: dihybrid cross gives 9:3:3:1 — traits are inherited independently", "Test cross: cross with the recessive parent to reveal an unknown genotype"], formula: "Dihybrid (TtYy × TtYy) → 9:3:3:1" },
    { kicker: "Sex Determination", title: "Who Decides Boy or Girl?",
      points: ["Humans: 23 pairs of chromosomes = 22 pairs autosomes + 1 pair sex chromosomes", "Female: XX • Male: XY — the father's sperm (X or Y) decides the sex, 50–50", "In some reptiles, temperature (not chromosomes) decides sex — biology has many systems"], formula: "XX = girl • XY = boy" },
    { kicker: "Evolution", title: "From Variation to New Species",
      points: ["Acquired traits are NOT inherited — only changes in germ-cell DNA pass on", "Darwin: natural selection — variations + competition + survival of the fittest", "Homologous organs (forelimb: human, bat, whale) = common ancestry; analogous (bird wing vs butterfly wing) = similar function only", "Fossils: deeper = older; wild cabbage → cabbage, cauliflower, broccoli, kohlrabi by artificial selection"], formula: "Speciation = isolation + drift + selection" },
  ],
  mindmap: { central: "Heredity & Evolution",
    branches: [
      { label: "Mendel", color: "#1a73e8", children: ["Pea plant, 7 traits", "Monohybrid 3:1", "Dihybrid 9:3:3:1", "Test cross"] },
      { label: "Terms", color: "#e37400", children: ["Gene, allele", "Genotype vs phenotype", "Dominant/recessive", "Homozygous/heterozygous"] },
      { label: "Sex determination", color: "#c5221f", children: ["22 + XX/XY", "Father decides", "50–50 chance"] },
      { label: "Evolution", color: "#146c2e", children: ["Natural selection", "Homologous vs analogous", "Fossils & dating", "Artificial selection"] },
    ] },
  flowchart: [
    { title: "Parents", desc: "TT (pure tall) × tt (pure dwarf)" },
    { title: "F₁ generation", desc: "all Tt — tall, because T is dominant" },
    { title: "F₁ self-pollination", desc: "Tt × Tt — alleles segregate", type: "decision" },
    { title: "F₂ generation", desc: "TT : Tt : tt = 1 : 2 : 1 → 3 tall : 1 dwarf", type: "result" },
  ],
  diagrams: [
    { title: "Punnett square (Tt × Tt)", desc: "Gametes T, t across the top and side: TT, Tt, Tt, tt — genotypic ratio 1:2:1, phenotypic 3:1", label: "Draw the 4-box square in exams" },
  ],
  notes: [
    "Mendel's method: <b>one trait at a time, true-breeding parents, large counts, statistics</b> — that's why he succeeded where others failed.",
    "Each human gamete carries <b>23 chromosomes</b> (half); fertilisation restores 46.",
    "Acquired traits (biceps from gym) change only body cells — <b>not the germ cells</b>, so children do not inherit them.",
    "Evolution is not progress toward 'better' — it is <b>generation of diversity by adaptation</b>.",
    "Artificial selection of wild cabbage gave: <b>cabbage (leaves), cauliflower (flower buds), broccoli (arrested flowers), kohlrabi (swollen stem)</b>.",
    "Mendel's 1866 paper was rediscovered in 1900 (de Vries, Correns, Tschermak) — science was finally ready for it.",
  ],
  quiz: [
    { q: "The F₂ phenotypic ratio of a monohybrid cross is:", options: ["1:2:1", "3:1", "9:3:3:1", "1:1"], answer: 1, why: "3 tall : 1 dwarf; 1:2:1 is the genotypic ratio." },
    { q: "Tt is crossed with tt. What fraction of offspring is dwarf?", options: ["0", "1/4", "1/2", "3/4"], answer: 2, why: "Tt × tt → Tt, Tt, tt, tt — half dwarf." },
    { q: "The wing of a bat and the wing of a butterfly are:", options: ["Homologous", "Analogous", "Vestigial", "Fossilised"], answer: 1, why: "Same function, totally different structure and origin → analogy." },
  ],
  pyq: [
    "Explain Mendel's monohybrid cross with a Punnett square and give the F₂ ratios. (CBSE 2023, 5m)",
    "Why are traits acquired during an individual's lifetime not inherited? (CBSE 2022, 2m)",
    "What are fossils? How do they provide evidence for evolution? (CBSE 2020, 3m)",
  ],
},

"science-0-8": {
  slides: [
    { kicker: "Science Ch.9 • Physics", title: "Light — Reflection and Refraction",
      points: ["Laws of reflection: ∠i = ∠r; image in a plane mirror: virtual, erect, same size, laterally inverted", "Concave mirror (converging): torches, headlights, shaving & dentist mirrors, solar furnaces", "Convex mirror (diverging): rear-view mirrors — erect, diminished, wider field of view", "New Cartesian convention: measure from pole/O; distances against incident light are negative"], formula: "1/v + 1/u = 1/f • m = −v/u" },
    { kicker: "Mirrors", title: "Image Table (Concave)",
      points: ["Object at ∞ → real point image at F", "Beyond C → between F and C, real, inverted, diminished", "At C → at C, same size, real inverted", "Between P and F → virtual, erect, magnified (shaving mirror)", "Convex mirror ALWAYS → virtual, erect, diminished"], formula: "f = R/2" },
    { kicker: "Refraction", title: "When Light Changes Medium",
      points: ["Light bends because its speed changes: v = c/n", "Refractive index: air ≈ 1, water 1.33, glass ≈ 1.5, diamond 2.42", "Rarer → denser: ray bends toward the normal (and vice versa)", "Glass slab: emergent ray parallel to incident ray with lateral displacement; n = sin i / sin r"], formula: "n = c/v = sin i / sin r" },
    { kicker: "Lenses", title: "Convex, Concave and Power",
      points: ["Convex (converging): magnifying glass, projectors, corrects hypermetropia", "Concave (diverging): peepholes, corrects myopia", "Lens formula: 1/v − 1/u = 1/f; magnification m = v/u", "Power P = 1/f (f in metres), unit dioptre (D); lenses in contact: P = P₁ + P₂"], formula: "P = 1/f • 1/v − 1/u = 1/f" },
  ],
  mindmap: { central: "Light: Reflection & Refraction",
    branches: [
      { label: "Reflection", color: "#1a73e8", children: ["∠i = ∠r", "Plane mirror image", "Concave uses", "Convex = rear-view"] },
      { label: "Mirror maths", color: "#e37400", children: ["1/v + 1/u = 1/f", "m = −v/u", "f = R/2", "Sign convention"] },
      { label: "Refraction", color: "#146c2e", children: ["n = c/v", "Snell's law", "Glass slab: lateral shift", "Apparent depth"] },
      { label: "Lenses", color: "#9334e6", children: ["1/v − 1/u = 1/f", "m = v/u", "P = 1/f (dioptre)", "P = P₁ + P₂"] },
    ] },
  formulas: [
    { name: "Mirror formula", expr: "1/v + 1/u = 1/f" },
    { name: "Mirror magnification", expr: "m = −v/u = h′/h" },
    { name: "Focal length & radius", expr: "f = R/2" },
    { name: "Refractive index", expr: "n = c/v" },
    { name: "Snell's law", expr: "n₂₁ = sin i / sin r" },
    { name: "Lens formula", expr: "1/v − 1/u = 1/f" },
    { name: "Lens magnification", expr: "m = v/u = h′/h" },
    { name: "Power of lens", expr: "P = 1/f (f in m) dioptre" },
  ],
  examples: [
    { title: "Concave mirror: object at 20 cm, f = 15 cm",
      steps: ["u = −20 cm, f = −15 cm (concave)", "1/v = 1/f − 1/u = −1/15 + 1/20 = −1/60", "v = −60 cm (60 cm in front of the mirror)", "m = −v/u = −(−60)/(−20) = −3"],
      answer: "Real, inverted image, 3× magnified, 60 cm from the mirror" },
    { title: "Convex lens: object at 30 cm, f = 10 cm",
      steps: ["u = −30 cm, f = +10 cm", "1/v = 1/f + 1/u = 1/10 − 1/30 = 1/15", "v = +15 cm (real, on the other side)", "m = v/u = 15/(−30) = −0.5"],
      answer: "Real, inverted, half-size image at 15 cm" },
    { title: "Refractive index of glass",
      steps: ["Speed of light in glass v = 2 × 10⁸ m/s", "n = c/v = (3 × 10⁸)/(2 × 10⁸)"],
      answer: "n = 1.5" },
  ],
  diagrams: [
    { title: "Ray diagrams — concave mirror", desc: "Object beyond C → image between F and C (real, small); object at C → image at C (same size); object between F and P → virtual, erect, magnified behind the mirror", label: "Learn the 3 standard rays: parallel→through F, through C→back, through F→parallel" },
    { title: "Refraction through a glass slab", desc: "Ray bends toward the normal on entering, away on leaving; the emergent ray is parallel to the incident ray with a lateral displacement", label: "∠i = ∠e (emergent)" },
  ],
  notes: [
    "Concave mirror uses: <b>headlight reflectors, shaving mirrors, dentists' mirrors, solar cookers</b>; convex: <b>rear-view mirrors</b>.",
    "Sign convention: distances measured from the <b>pole/optical centre</b>, along incident light direction negative; heights above the axis positive.",
    "Magnification sign: <b>− means inverted (real)</b>, + means erect (virtual) — for mirrors.",
    "Refractive index of a medium is always ≥ 1 because nothing travels faster than light in vacuum.",
    "Refraction explains: a straw looks bent in water, the pool floor seems raised, stars twinkle, days appear longer.",
  ],
  quiz: [
    { q: "A convex mirror is used as a rear-view mirror because it:", options: ["Gives a magnified image", "Always gives an erect, diminished image with a wide field of view", "Forms real images", "Has a very short focal length"], answer: 1, why: "Diminished, erect, virtual image → a much larger area is visible." },
    { q: "The SI unit of the power of a lens is:", options: ["Watt", "Metre", "Dioptre", "Joule"], answer: 2, why: "P = 1/f(in m); the unit is dioptre (D)." },
    { q: "A ray of light travelling from air into glass bends:", options: ["Away from the normal", "Toward the normal", "Along the surface", "It does not bend"], answer: 1, why: "Glass is optically denser (n = 1.5) — the speed drops, so the ray bends toward the normal." },
  ],
  pyq: [
    "An object is placed 30 cm from a concave mirror of focal length 20 cm. Find the position, size and nature of the image. (CBSE 2023, 3m)",
    "Write the sign conventions used for reflection by spherical mirrors. (CBSE 2022, 3m)",
    "The speed of light in a medium is 2/3 of its speed in vacuum. Find the refractive index. (CBSE 2020, 2m)",
  ],
},

"science-0-9": {
  slides: [
    { kicker: "Science Ch.10 • Physics", title: "The Human Eye and the Colourful World",
      points: ["Path of light: cornea (most refraction) → pupil (iris controls size) → eye lens → retina (inverted image) → optic nerve → brain", "Ciliary muscles change the lens's focal length = power of accommodation", "Least distance of distinct vision (near point) = 25 cm", "Retina has rods (dim light) and cones (colour)"], formula: "Thicker lens → shorter f → focus on near objects" },
    { kicker: "Defects", title: "Myopia, Hypermetropia, Presbyopia",
      points: ["Myopia (near-sighted): image forms before the retina — elongated eyeball/excess curvature; fix with a CONCAVE lens", "Hypermetropia (far-sighted): image forms behind the retina — short eyeball; fix with a CONVEX lens", "Presbyopia: ageing ciliary muscles + hardening lens → bifocal lenses (also reading glasses)", "Astigmatism: irregular curvature → cylindrical lens"], formula: "Myopia: − lens • Hypermetropia: + lens" },
    { kicker: "Dispersion", title: "White Light = 7 Colours",
      points: ["A prism splits white light into VIBGYOR — violet deviates most, red least", "Different colours have different refractive indices in glass (n_violet > n_red)", "Newton recombined the spectrum with a second prism → white light", "Rainbow: dispersion + internal reflection inside raindrops — visible with your back to the sun"], formula: "n(violet) > n(red) → violet bends most" },
    { kicker: "Atmosphere", title: "Twinkling, Sunrise and Blue Skies",
      points: ["Twinkling stars: atmospheric refraction makes starlight fluctuate; planets (extended sources) barely twinkle", "Advanced sunrise & delayed sunset ≈ 2 minutes each — refraction near the horizon", "Tyndall effect: colloidal dust scatters a beam, making it visible", "Blue sky: short wavelengths scatter most; red sunsets: long path scatters blue away; danger signals are red because red scatters least"], formula: "Rayleigh: scattering ∝ 1/λ⁴" },
  ],
  mindmap: { central: "Human Eye & Colourful World",
    branches: [
      { label: "Eye", color: "#1a73e8", children: ["Cornea, pupil, lens", "Ciliary muscles", "Retina: rods & cones", "Near point 25 cm"] },
      { label: "Defects", color: "#c5221f", children: ["Myopia → concave", "Hypermetropia → convex", "Presbyopia → bifocal", "Astigmatism → cylindrical"] },
      { label: "Dispersion", color: "#e37400", children: ["Prism → VIBGYOR", "Violet bends most", "Rainbow", "Recombination → white"] },
      { label: "Scattering", color: "#146c2e", children: ["Tyndall effect", "Blue sky", "Red sunset", "Stars twinkle"] },
    ] },
  formulas: [
    { name: "Power of corrective lens", expr: "P = 1/f (f in m), unit dioptre" },
    { name: "Rayleigh scattering", expr: "scattering ∝ 1/λ⁴" },
  ],
  examples: [
    { title: "Myopia correction — far point 1.5 m",
      steps: ["The lens must image distant objects (∞) at the far point, 1.5 m", "u = −∞, v = −1.5 m", "1/f = 1/v − 1/u = −1/1.5 − 0", "P = 1/f = −0.67 D"],
      answer: "Concave lens of power ≈ −0.67 D" },
  ],
  diagrams: [
    { title: "Myopia vs Hypermetropia", desc: "Myopic eye: rays converge in front of the retina → concave lens diverges them onto it. Hypermetropic eye: rays would focus behind → convex lens converges them earlier", label: "My = too strong → weaken it" },
    { title: "Dispersion through a prism", desc: "White light enters, splits into VIBGYOR: red deviated least, violet most; the coloured band is the spectrum", label: "Draw the prism with the red ray on top" },
    { title: "Structure of the eye", desc: "Cornea, iris, pupil, eye lens held by ciliary muscles, vitreous humour, retina with rods & cones, optic nerve", label: "Image on the retina is real, inverted, diminished" },
  ],
  notes: [
    "The <b>cornea</b> provides most of the refraction; the lens only fine-tunes the focus.",
    "Accommodation weakens with age (ciliary muscles, lens stiffens) → <b>presbyopia</b>; bifocals: upper half for distance, lower for reading.",
    "Planets do not twinkle much — they are <b>extended sources</b> (many point sources), so variations average out.",
    "Danger signals are red because red <b>scatters the least</b> — visible from far through fog.",
    "On the Moon (no atmosphere) the sky is <b>black</b> — no scattering at all.",
    "Rainbow needs the sun <b>behind you</b>: light enters a raindrop, refracts, reflects internally, and exits split into colours.",
  ],
  quiz: [
    { q: "A student cannot read the blackboard from the last bench. The defect and correction are:", options: ["Hypermetropia, convex lens", "Myopia, concave lens", "Presbyopia, bifocal", "Astigmatism, cylindrical lens"], answer: 1, why: "Distant objects blur → myopia → diverging (concave) lens." },
    { q: "In dispersion by a prism, the colour deviated most is:", options: ["Red", "Yellow", "Green", "Violet"], answer: 3, why: "Violet has the shortest wavelength and the highest refractive index." },
    { q: "The clear sky appears blue because:", options: ["Air absorbs other colours", "Air itself is blue", "Shorter wavelengths scatter more", "Blue light travels fastest"], answer: 2, why: "Scattering ∝ 1/λ⁴ — blue light is scattered all around the sky." },
  ],
  pyq: [
    "A person cannot see objects beyond 2 m clearly. Name the defect and the corrective lens with calculation. (CBSE 2023, 3m)",
    "Why does the sky appear dark to an astronaut on the Moon? (CBSE 2022, 2m)",
    "Explain the formation of a rainbow with a diagram. (CBSE 2020, 3m)",
  ],
},

"science-0-10": {
  slides: [
    { kicker: "Science Ch.11 • Physics", title: "Electricity",
      points: ["Charge Q (coulomb); current I = Q/t (ampere) — 1 A = 1 C/s", "Potential difference V = W/Q (volt = joule/coulomb)", "Ohm's law (at constant temperature): V ∝ I → V = IR", "Ammeter in series (very low resistance); voltmeter in parallel (very high resistance)"], formula: "V = IR • I = Q/t" },
    { kicker: "Resistance", title: "What Controls R?",
      points: ["R ∝ length l; R ∝ 1/area A → R = ρl/A", "Resistivity ρ (Ω·m) is a material property — metals low, insulators huge, alloys higher than pure metals", "Metal resistivity rises with temperature", "Heating elements use nichrome: high resistivity + high melting point + no oxidation"], formula: "R = ρl/A" },
    { kicker: "Circuits", title: "Series vs Parallel",
      points: ["Series: same current everywhere; Rs = R₁ + R₂ + R₃; voltage divides", "Parallel: same voltage across each; 1/Rp = 1/R₁ + 1/R₂ + 1/R₃; current divides", "Parallel equivalent is SMALLER than the smallest resistor", "House wiring is parallel — every appliance gets the full 220 V"], formula: "Series adds R • parallel adds 1/R" },
    { kicker: "Heating & Power", title: "From Heat to Bills",
      points: ["Joule's law of heating: H = I²Rt", "Power P = VI = I²R = V²/R (watt)", "Commercial energy: 1 unit = 1 kWh = 3.6 × 10⁶ J", "Applications: heaters, geysers, toasters; bulb filament = tungsten (high MP, glows white); fuse = low-MP wire that melts to break the circuit"], formula: "H = I²Rt • P = VI" },
  ],
  mindmap: { central: "Electricity",
    branches: [
      { label: "Basics", color: "#1a73e8", children: ["I = Q/t", "V = W/Q", "Ohm's law V = IR", "Ammeter series / voltmeter parallel"] },
      { label: "Resistance", color: "#e37400", children: ["R = ρl/A", "Resistivity Ω·m", "Alloys for heaters", "Semiconductors: ρ falls with T"] },
      { label: "Circuits", color: "#146c2e", children: ["Series: Rs = sum", "Parallel: 1/Rp = sum of 1/R", "House wiring = parallel"] },
      { label: "Power & heat", color: "#c5221f", children: ["H = I²Rt", "P = VI = I²R = V²/R", "1 kWh = 3.6 × 10⁶ J", "Fuse & MCB"] },
    ] },
  formulas: [
    { name: "Current", expr: "I = Q/t" },
    { name: "Ohm's law", expr: "V = IR" },
    { name: "Resistance of a conductor", expr: "R = ρl/A" },
    { name: "Series resistance", expr: "Rs = R₁ + R₂ + R₃" },
    { name: "Parallel resistance", expr: "1/Rp = 1/R₁ + 1/R₂ + 1/R₃" },
    { name: "Joule's law of heating", expr: "H = I²Rt" },
    { name: "Electric power", expr: "P = VI = I²R = V²/R" },
    { name: "Energy unit", expr: "1 kWh = 3.6 × 10⁶ J" },
  ],
  examples: [
    { title: "Parallel combination on a 6 V battery",
      steps: ["R₁ = 6 Ω and R₂ = 3 Ω in parallel", "1/Rp = 1/6 + 1/3 = 1/2 → Rp = 2 Ω (smaller than both ✓)", "I = V/R = 6/2 = 3 A"],
      answer: "Rp = 2 Ω; total current = 3 A" },
    { title: "Monthly electricity bill",
      steps: ["2 kW geyser, 2 h daily, 30 days", "Energy = P × t = 2 × 2 × 30 = 120 kWh", "Cost at ₹6/unit = 120 × 6"],
      answer: "₹720 per month" },
    { title: "Heat produced in a resistor",
      steps: ["I = 5 A, R = 4 Ω, t = 10 min = 600 s", "H = I²Rt = 25 × 4 × 600 = 60,000 J"],
      answer: "H = 6 × 10⁴ J = 60 kJ" },
  ],
  diagrams: [
    { title: "Ohm's law circuit", desc: "Battery → ammeter in series → rheostat + resistor R → voltmeter in parallel across R; change current with the rheostat and record V–I pairs", label: "V–I graph: a straight line through the origin (slope = R)" },
    { title: "Series vs parallel wiring", desc: "Series: one loop, resistors in a chain; parallel: resistors connected between the same two nodes, multiple paths for current", label: "Parallel → each branch gets the full voltage" },
  ],
  notes: [
    "1 A ≈ <b>6.25 × 10¹⁸ electrons</b> per second (e = 1.6 × 10⁻¹⁹ C).",
    "A straight V–I line = <b>ohmic conductor</b> at constant temperature; a bulb filament curves (heating changes R).",
    "Wires use <b>copper/aluminium</b> (low ρ); heaters use <b>nichrome</b> (high ρ, high MP).",
    "The fuse wire has high resistance and a <b>low melting point</b> — excess current melts it and breaks the circuit.",
    "In series, the same current flows but voltage divides; that's why series bulbs glow dimmer.",
    "Switches and fuses always go in the <b>live wire</b>.",
  ],
  quiz: [
    { q: "Resistors 2 Ω, 3 Ω and 6 Ω are in parallel. The equivalent resistance is:", options: ["11 Ω", "6 Ω", "1 Ω", "0.5 Ω"], answer: 2, why: "1/Rp = 1/2 + 1/3 + 1/6 = 1 → Rp = 1 Ω." },
    { q: "A bulb draws 0.5 A at 220 V. Its power is:", options: ["44 W", "110 W", "440 W", "1100 W"], answer: 1, why: "P = VI = 220 × 0.5 = 110 W." },
    { q: "1 kWh equals:", options: ["3.6 × 10³ J", "3.6 × 10⁶ J", "1000 J", "3600 J"], answer: 1, why: "1000 W × 3600 s = 3.6 × 10⁶ J." },
  ],
  pyq: [
    "Draw a circuit to verify Ohm's law using a battery, rheostat, ammeter and voltmeter. (CBSE 2023, 3m)",
    "Why are tungsten and nichrome chosen for bulb filaments and heating elements respectively? (CBSE 2022, 2m)",
    "An electric device of 1.5 kW runs 8 h/day for 30 days at ₹6 per unit — calculate the bill. (CBSE 2020, 3m)",
  ],
},

"science-0-11": {
  slides: [
    { kicker: "Science Ch.12 • Physics", title: "Magnetic Effects of Electric Current",
      points: ["Oersted: a current-carrying wire deflects a nearby compass — current produces a magnetic field", "Right-hand thumb rule: thumb = current, curled fingers = field direction", "Field lines: closed loops, NEVER intersect (two directions at one point is impossible)", "Solenoid: long coil → uniform field inside, behaves like a bar magnet; + soft iron core = electromagnet"], formula: "Current → magnetic field (Oersted)" },
    { kicker: "Force", title: "Motor Effect (Left Hand)",
      points: ["A current-carrying conductor in a magnetic field feels a force — Fleming's LEFT-hand rule: thumb force, forefinger field, middle finger current", "Electric motor: electrical → mechanical energy", "Split-ring commutator reverses current direction every half rotation → continuous rotation", "Uses: fans, mixers, washing machines, EVs"], formula: "Left hand = motor (FBI)" },
    { kicker: "Induction", title: "Generator Effect (Right Hand)",
      points: ["Faraday: moving a magnet/coil changes the field → induced current, no battery needed", "Fleming's RIGHT-hand rule: thumb motion, forefinger field, middle finger induced current", "Generator: mechanical → electrical energy", "Slip rings → AC (direction reverses); split rings → DC; Indian AC = 50 Hz"], formula: "Right hand = generator" },
    { kicker: "At Home", title: "Domestic Circuits",
      points: ["220 V supply: live (red/brown) + neutral (black/blue) + earth (green)", "Earth wire connects metal bodies to the ground — saves us from shocks", "Fuse/MCB on the live wire trips on short circuit (live touches neutral) or overload (too many high-power appliances)", "All appliances wired in PARALLEL — each gets full voltage & independent switching"], formula: "Earth = safety • fuse = protection" },
  ],
  mindmap: { central: "Magnetism & Current",
    branches: [
      { label: "Field", color: "#1a73e8", children: ["Right-hand thumb rule", "Closed loops, never cross", "Solenoid", "Electromagnet"] },
      { label: "Force", color: "#c5221f", children: ["Fleming's left hand", "Electric motor", "Split-ring commutator", "Fans, mixers, EVs"] },
      { label: "Induction", color: "#e37400", children: ["Faraday's discovery", "Fleming's right hand", "Generator AC/DC", "50 Hz in India"] },
      { label: "Domestic", color: "#146c2e", children: ["Live/neutral/earth", "Fuse & MCB", "Short circuit", "Parallel wiring"] },
    ] },
  flowchart: [
    { title: "Current in a conductor + magnetic field", desc: "place a current-carrying conductor between magnet poles" },
    { title: "LEFT-hand rule", desc: "a force pushes the conductor — motor: electrical → mechanical", type: "result" },
    { title: "Move a conductor in a field", desc: "or change the field near a coil" },
    { title: "RIGHT-hand rule", desc: "current is induced — generator: mechanical → electrical", type: "result" },
  ],
  diagrams: [
    { title: "Field lines of a bar magnet", desc: "Lines leave the north pole and enter the south pole outside the magnet; inside, they run S→N — every line is a closed loop", label: "Closer lines = stronger field" },
    { title: "Domestic wiring", desc: "Pole → main fuse → meter → main switch → distribution board; separate 15 A (geyser, AC) and 5 A (bulbs, fans) circuits, all appliances in parallel with an earth connection", label: "Green = earth • Red/brown = live • Black/blue = neutral" },
  ],
  notes: [
    "Field lines never intersect — at a crossing a compass would need <b>two directions at once</b>.",
    "Electromagnet = <b>solenoid + soft iron core</b>: cranes, electric bells, relays — magnetism on demand.",
    "Mnemonic <b>FBI</b>: <b>F</b>orce-thumb, <b>B</b>(field)-forefinger, <b>I</b>-middle finger — left for motors, right for generators.",
    "AC is used for grids because transformers can step it up/down, cutting transmission losses.",
    "Earthing works: if live touches a metal body, the earth wire gives a <b>low-resistance path</b> → huge current → fuse blows → user saved.",
    "Overloading = drawing more current than the wiring rating; short circuit = live meets neutral directly.",
  ],
  quiz: [
    { q: "The direction of induced current is given by:", options: ["Fleming's left-hand rule", "Fleming's right-hand rule", "Right-hand thumb rule", "Ampere's rule"], answer: 1, why: "Right hand → induction (generator); left hand → force (motor)." },
    { q: "Domestic appliances are wired in:", options: ["Series", "Parallel", "Series-parallel alternately", "Does not matter"], answer: 1, why: "Parallel: full 220 V for each appliance and independent switching." },
    { q: "In standard house wiring, the earth wire is:", options: ["Red", "Black", "Green", "Blue"], answer: 2, why: "Green = earth; red/brown = live; black/blue = neutral." },
  ],
  pyq: [
    "State Fleming's left-hand rule and explain the working of an electric motor with a diagram. (CBSE 2023, 5m)",
    "What is a solenoid? Draw the magnetic field around a current-carrying solenoid. (CBSE 2022, 3m)",
    "Why is an electric fuse essential in domestic circuits? (CBSE 2020, 2m)",
  ],
},

"science-0-12": {
  slides: [
    { kicker: "Science Ch.13 • Eco", title: "Our Environment",
      points: ["Ecosystem = biotic (producers, consumers, decomposers) + abiotic (light, water, soil, temperature)", "Producers (green plants) trap solar energy; consumers: herbivores → 1°, 2°, 3° carnivores", "Decomposers (bacteria, fungi) break dead matter → nutrients recycled", "Food chain: grass → grasshopper → frog → snake → eagle; food web = many interlinked chains"], formula: "Only ~10% energy passes to the next level" },
    { kicker: "Energy Flow", title: "10% Law & Biomagnification",
      points: ["Energy flow is UNIDIRECTIONAL: sun → producers → consumers → heat lost", "Each trophic level keeps ~10% — hence food chains have only 4–5 steps", "Biomagnification: non-biodegradable poisons (DDT, mercury) rise in concentration up the chain — top carnivores worst hit", "Ozone-depleting CFCs came from refrigerators, ACs and sprays"], formula: "DDT at top of the chain can be millions × higher" },
    { kicker: "Ozone", title: "Earth's UV Shield",
      points: ["O₃ forms high in the atmosphere: UV splits O₂ → O + O₂ → O₃", "CFCs release chlorine atoms that destroy ozone molecules", "The Antarctic 'ozone hole' triggered action", "Montreal Protocol (1987): global CFC phase-out — the ozone layer is now recovering"], formula: "O₂ --UV→ O + O → O₃" },
    { kicker: "Waste", title: "5 R's of Waste Management",
      points: ["Biodegradable: peels, paper, cloth, leaves; Non-biodegradable: plastic, glass, metal, DDT", "Segregate at source: wet (green) vs dry (blue) bins", "Composting & vermicomposting (red worms, 3–4 weeks)", "5 R's: Refuse, Reduce, Reuse, Repurpose, Recycle — minimum to landfill"], formula: "Segregate → compost → recycle" },
  ],
  mindmap: { central: "Our Environment",
    branches: [
      { label: "Ecosystem", color: "#146c2e", children: ["Biotic + abiotic", "Producers/consumers", "Decomposers recycle"] },
      { label: "Food chain/web", color: "#1a73e8", children: ["Trophic levels", "10% law", "Unidirectional flow", "Max 4–5 steps"] },
      { label: "Ozone", color: "#e37400", children: ["UV shield", "CFCs destroy O₃", "Montreal Protocol 1987"] },
      { label: "Waste", color: "#c5221f", children: ["Biodegradable vs not", "5 R's", "Composting", "Biomagnification"] },
    ] },
  flowchart: [
    { title: "Sun", desc: "1,00,000 J of energy reaching producers" },
    { title: "Producers (plants)", desc: "store ~10,000 J in their tissues" },
    { title: "Herbivores", desc: "get ~1,000 J", type: "decision" },
    { title: "Top carnivores", desc: "barely ~10 J — too little to support another level", type: "result" },
  ],
  diagrams: [
    { title: "Grassland food web", desc: "Grass → insects/rat → frog/snake → hawk, all interconnected; removing one species ripples through the whole web", label: "More links = more stability" },
  ],
  notes: [
    "Without decomposers the Earth would be buried in dead matter — <b>they complete the nutrient cycle</b>.",
    "The 10% law explains why <b>top carnivores are rare</b> and need huge territories.",
    "Biomagnification of DDT made <b>eagle eggshells thin</b> — a classic exam example.",
    "The <b>Montreal Protocol (1987)</b> is the most successful environmental treaty ever.",
    "Vermicomposting: red worms convert kitchen waste into rich manure in 3–4 weeks.",
    "Ozone is a pollutant at ground level but a shield in the stratosphere — same molecule, different place!",
  ],
  quiz: [
    { q: "Which of these is a decomposer?", options: ["Grass", "Frog", "Fungi", "Eagle"], answer: 2, why: "Fungi decompose dead organic matter into simpler substances." },
    { q: "Only about 10% of energy passes between trophic levels because:", options: ["Energy is destroyed", "It is lost as heat + life processes", "Producers waste it", "Consumers refuse to eat"], answer: 1, why: "Energy is never destroyed — it is lost as heat and used up in respiration." },
    { q: "The ozone hole was mainly caused by:", options: ["CO₂", "CFCs", "CH₄", "SO₂"], answer: 1, why: "CFCs release chlorine atoms that break O₃ molecules apart." },
  ],
  pyq: [
    "Construct a food chain with five trophic levels from a grassland ecosystem. (CBSE 2023, 2m)",
    "What is biomagnification? Explain with DDT in an aquatic food chain. (CBSE 2022, 3m)",
    "Why are decomposers important for the ecosystem? (CBSE 2020, 2m)",
  ],
},

};
