/* Science topic-wise MCQ bank — NCERT Class 10, all chapters.
   Mirrors the SST bank: every question carries `topic` (the NCERT sub-heading
   it is set from) so students can practise topic by topic, and `exam: true`
   marks questions that are repeatedly asked / most expected in board exams.
   Facts, values and reactions are from the NCERT text. */
import type { QuizQ } from "./types";

export const SCI_MCQ: Record<string, QuizQ[]> = {

/* ============ CH 1 — CHEMICAL REACTIONS AND EQUATIONS ============ */
"science-0-0": [
  { topic: "Balancing Equations", exam: true, q: "A chemical equation is balanced to satisfy:", options: ["Law of conservation of mass", "Law of constant proportions", "Law of multiple proportions", "Avogadro's law"], answer: 0, why: "Mass of reactants must equal mass of products — atoms are neither created nor destroyed." },
  { topic: "Types of Reactions", exam: true, q: "2Mg + O2 → 2MgO is an example of:", options: ["Decomposition", "Combination", "Displacement", "Double displacement"], answer: 1, why: "Two or more substances combine to form a single product — combination (also oxidation, exothermic)." },
  { topic: "Types of Reactions", exam: true, q: "Heating calcium carbonate gives calcium oxide and carbon dioxide. This is:", options: ["Endothermic decomposition", "Exothermic decomposition", "Displacement", "Neutralisation"], answer: 0, why: "Energy is absorbed to break CaCO3 — thermal decomposition, endothermic." },
  { topic: "Types of Reactions", exam: true, q: "On heating ferrous sulphate crystals, the smell of burning sulphur comes from:", options: ["SO2 and SO3", "H2S", "CO2", "NO2"], answer: 0, why: "2FeSO4 → Fe2O3 + SO2↑ + SO3↑; the gases smell of burning sulphur." },
  { topic: "Types of Reactions", exam: true, q: "When lead nitrate is heated, the brown gas evolved is:", options: ["Oxygen", "Nitrogen dioxide", "Nitric oxide", "Ammonia"], answer: 1, why: "2Pb(NO3)2 → 2PbO + 4NO2↑ (brown) + O2↑." },
  { topic: "Displacement", q: "Iron nails in copper sulphate solution turn the solution green because:", options: ["Copper displaces iron", "Iron displaces copper", "Sulphate reacts with iron", "Water reacts with iron"], answer: 1, why: "Fe is more reactive than Cu: Fe + CuSO4 → FeSO4 (green) + Cu." },
  { topic: "Redox", exam: true, q: "In CuO + H2 → Cu + H2O, the substance oxidised and the substance reduced are:", options: ["H2 oxidised, CuO reduced", "CuO oxidised, H2 reduced", "Both oxidised", "Both reduced"], answer: 0, why: "H2 gains oxygen (oxidised); CuO loses oxygen (reduced) — a redox reaction." },
  { topic: "Everyday Chemistry", exam: true, q: "Respiration is a:", options: ["Endothermic process", "Exothermic oxidation process", "Reduction process", "Neutralisation process"], answer: 1, why: "Glucose + O2 → CO2 + H2O + energy; food is oxidised and energy is released." },
  { topic: "Everyday Chemistry", exam: true, q: "Fats and oils become rancid. Rancidity can be prevented by:", options: ["Adding antioxidants or flushing packs with nitrogen", "Exposing to sunlight", "Keeping in moist air", "Adding water"], answer: 0, why: "Rancidity is oxidation of fats; antioxidants and N2 packing stop the oxidation." },
  { topic: "Everyday Chemistry", q: "Silver articles turn black on exposure to air due to formation of:", options: ["AgCl", "Ag2S", "AgNO3", "Ag2O only"], answer: 1, why: "Silver reacts with H2S in air to form black Ag2S — corrosion of silver." },
  { topic: "Displacement", exam: true, q: "The gas evolved when dilute HCl is added to zinc granules, which burns with a pop sound, is:", options: ["Oxygen", "Carbon dioxide", "Hydrogen", "Chlorine"], answer: 2, why: "Zn + 2HCl → ZnCl2 + H2↑; hydrogen burns with a characteristic pop." },
  { topic: "Balancing Equations", q: "The white precipitate formed when sodium chloride is added to silver nitrate solution is:", options: ["AgCl", "NaNO3", "AgNO3", "NaCl"], answer: 0, why: "AgNO3 + NaCl → AgCl↓ (white) + NaNO3 — double displacement (precipitation)." },
  { topic: "Types of Reactions", q: "The reaction H2 + Cl2 → 2HCl is best described as:", options: ["Photochemical combination", "Thermal decomposition", "Displacement", "Precipitation"], answer: 0, why: "Hydrogen and chlorine combine in sunlight to form one product — photochemical combination." },
  { topic: "Everyday Chemistry", q: "Freshly prepared slaked lime is used for whitewashing; the shiny finish appears due to formation of:", options: ["CaO", "CaCO3", "Ca(OH)2", "CaCl2"], answer: 1, why: "Ca(OH)2 reacts with CO2 in air to form a thin layer of CaCO3, giving the shine." },
],

/* ============ CH 2 — ACIDS, BASES AND SALTS ============ */
"science-0-1": [
  { topic: "Indicators", exam: true, q: "Which of these is an olfactory indicator?", options: ["Litmus", "Onion", "Phenolphthalein", "Methyl orange"], answer: 1, why: "Onion (and vanilla) change their smell in a base — useful for visually impaired students." },
  { topic: "Indicators", exam: true, q: "Phenolphthalein in a basic solution turns:", options: ["Colourless", "Pink", "Red", "Yellow"], answer: 1, why: "Colourless in acid/neutral, pink in base." },
  { topic: "Reactions of Acids", exam: true, q: "Dry HCl gas does not change the colour of dry litmus paper because:", options: ["HCl is not an acid", "No H+ (H3O+) ions form without water", "Litmus needs heat", "HCl is a weak acid"], answer: 1, why: "Acids show acidic behaviour only in aqueous solution — ions form only in water." },
  { topic: "Reactions of Acids", exam: true, q: "The gas evolved when an acid reacts with a metal, and which burns with a pop sound, is:", options: ["Oxygen", "Hydrogen", "Carbon dioxide", "Nitrogen"], answer: 1, why: "Acid + metal → salt + H2↑; hydrogen pops with a burning splint." },
  { topic: "pH in Daily Life", exam: true, q: "Tooth decay starts when the pH of the mouth falls below:", options: ["7", "6.5", "5.5", "4"], answer: 2, why: "Below pH 5.5 the tooth enamel (calcium phosphate) starts corroding; brush after meals." },
  { topic: "pH in Daily Life", exam: true, q: "The acid produced in our stomach which helps digestion is:", options: ["Sulphuric acid", "Acetic acid", "Hydrochloric acid", "Citric acid"], answer: 2, why: "Stomach glands secrete HCl; excess causes indigestion, treated with antacids." },
  { topic: "Important Salts", exam: true, q: "Baking soda is:", options: ["Na2CO3", "NaHCO3", "NaCl", "NaOH"], answer: 1, why: "Sodium hydrogen carbonate — mild base, used in baking powder and antacids." },
  { topic: "Important Salts", exam: true, q: "Washing soda, used to remove permanent hardness of water, is:", options: ["Na2CO3·10H2O", "NaHCO3·10H2O", "CaSO4·2H2O", "CuSO4·5H2O"], answer: 0, why: "Sodium carbonate decahydrate, obtained from the chlor-alkali product NaOH + CO2 route." },
  { topic: "Important Salts", exam: true, q: "Plaster of Paris is obtained by heating gypsum to:", options: ["373 K", "100 K", "500 K", "1200 K"], answer: 0, why: "At 373 K gypsum loses 3/2 water molecules: CaSO4·2H2O → CaSO4·½H2O." },
  { topic: "Important Salts", exam: true, q: "Bleaching powder is produced by the action of chlorine on:", options: ["NaOH", "Dry slaked lime Ca(OH)2", "Washing soda", "Quicklime"], answer: 1, why: "Ca(OH)2 + Cl2 → CaOCl2 + H2O; used for bleaching and disinfecting water." },
  { topic: "Chlor-alkali", exam: true, q: "Electrolysis of brine (chlor-alkali process) gives:", options: ["NaOH, Cl2, H2", "Na, Cl2, O2", "NaCl, H2O", "Na2CO3, Cl2"], answer: 0, why: "2NaCl + 2H2O → 2NaOH + Cl2 (anode) + H2 (cathode)." },
  { topic: "pH in Daily Life", q: "Acid rain is said to occur when the pH of rain is:", options: ["Below 5.6", "Exactly 7", "Above 7", "Between 6 and 7"], answer: 0, why: "Normal rain pH ≈ 5.6; lower pH (from SO2/NOx) is acid rain, harmful to aquatic life." },
  { topic: "Salts & Hydrolysis", q: "The salt formed from a strong acid and a weak base (e.g. HCl + NH4OH) is:", options: ["Neutral", "Acidic (NH4Cl)", "Basic", "Amphoteric"], answer: 1, why: "NH4Cl solution is acidic (pH < 7); strong acid + weak base → acidic salt." },
  { topic: "Water of Crystallisation", exam: true, q: "Blue copper sulphate crystals turn white on heating because:", options: ["They lose water of crystallisation", "They gain oxygen", "Copper evaporates", "They absorb heat colour"], answer: 0, why: "CuSO4·5H2O loses water to become white anhydrous CuSO4; adding water restores blue." },
],

/* ============ CH 3 — METALS AND NON-METALS ============ */
"science-0-2": [
  { topic: "Physical Properties", exam: true, q: "The metal that is liquid at room temperature is:", options: ["Sodium", "Mercury", "Iron", "Magnesium"], answer: 1, why: "Mercury is liquid at room temperature; among non-metals, bromine is liquid." },
  { topic: "Physical Properties", q: "The non-metal that shows lustre (shiny appearance) is:", options: ["Sulphur", "Iodine", "Oxygen", "Phosphorus"], answer: 1, why: "Iodine crystals are lustrous — an exception among non-metals." },
  { topic: "Reactivity Series", exam: true, q: "Which metal reacts with steam but NOT with cold water?", options: ["Sodium", "Calcium", "Iron", "Potassium"], answer: 2, why: "Na, K, Ca attack cold water; iron reacts only with steam: 3Fe + 4H2O → Fe3O4 + 4H2." },
  { topic: "Amphoteric Oxides", exam: true, q: "Which pair of oxides is amphoteric?", options: ["Na2O and K2O", "Al2O3 and ZnO", "CO2 and SO2", "MgO and CaO"], answer: 1, why: "Al2O3 and ZnO react with both acids and bases to give salt and water." },
  { topic: "Ionic Compounds", exam: true, q: "Ionic compounds have high melting points because:", options: ["They are covalent", "Strong electrostatic attraction between ions", "They contain water", "They are metallic"], answer: 1, why: "Large energy is needed to break the strong inter-ionic forces." },
  { topic: "Ionic Compounds", exam: true, q: "Ionic compounds conduct electricity in:", options: ["Solid state", "Molten state", "Neither", "Only in gas state"], answer: 1, why: "In molten/aqueous state ions become free to move and carry charge." },
  { topic: "Extraction of Metals", exam: true, q: "Metals of high reactivity (Na, K, Al) are extracted by:", options: ["Simple heating", "Reduction with carbon", "Electrolytic reduction", "Displacement by iron"], answer: 2, why: "Their oxides are too stable; electrolysis of molten compounds is used." },
  { topic: "Extraction of Metals", exam: true, q: "Roasting is used for:", options: ["Carbonate ores", "Sulphide ores", "Oxide ores", "Chloride ores"], answer: 1, why: "Roasting = heating sulphide ores in excess air; calcination = carbonate ores in limited air." },
  { topic: "Extraction of Metals", exam: true, q: "In the thermite reaction used for welding rails, iron oxide is reduced by:", options: ["Carbon", "Aluminium", "Hydrogen", "Copper"], answer: 1, why: "Fe2O3 + 2Al → 2Fe + Al2O3 + heat; molten iron welds the joint." },
  { topic: "Corrosion & Prevention", exam: true, q: "Galvanisation protects iron from rusting by coating it with:", options: ["Tin", "Copper", "Zinc", "Chromium"], answer: 2, why: "A zinc layer prevents air and moisture from reaching the iron surface." },
  { topic: "Alloys", exam: true, q: "Brass is an alloy of:", options: ["Cu + Zn", "Cu + Sn", "Fe + C", "Al + Cu"], answer: 0, why: "Brass = copper + zinc; bronze = copper + tin; steel = iron + carbon." },
  { topic: "Aqua Regia", exam: true, q: "Aqua regia, which dissolves gold and platinum, is a mixture of:", options: ["HCl : HNO3 in 3 : 1", "HCl : HNO3 in 1 : 3", "H2SO4 : HNO3 in 3 : 1", "HCl : H2SO4 in 1 : 1"], answer: 0, why: "Freshly mixed concentrated HCl and HNO3 in 3:1 ratio dissolves even noble metals." },
  { topic: "Refining", q: "In electrolytic refining of copper, the impure metal is made the:", options: ["Cathode", "Anode", "Electrolyte", "Container"], answer: 1, why: "Impure copper anode dissolves; pure copper deposits on the cathode." },
  { topic: "Corrosion", q: "The green coating on copper articles left in moist air is:", options: ["CuO", "Basic copper carbonate CuCO3·Cu(OH)2", "CuSO4", "CuCl2"], answer: 1, why: "Copper reacts with CO2 and moisture to form green basic copper carbonate." },
],

/* ============ CH 4 — CARBON AND ITS COMPOUNDS ============ */
"science-0-3": [
  { topic: "Covalent Bonding", exam: true, q: "Carbon forms covalent bonds because:", options: ["It can easily form C4+ ions", "It can easily form C4- ions", "Sharing electrons completes its octet; gaining/losing 4 electrons needs too much energy", "It is a metal"], answer: 2, why: "With 4 valence electrons, sharing (not ion formation) is the energetically feasible path." },
  { topic: "Versatile Nature", exam: true, q: "The property of carbon to form long chains and rings by bonding with its own atoms is:", options: ["Allotropy", "Catenation", "Isomerism", "Hydrogenation"], answer: 1, why: "Strong C–C bonds allow chains, branches and rings — the basis of organic chemistry." },
  { topic: "Hydrocarbons", exam: true, q: "The general formula of alkenes is:", options: ["CnH2n+2", "CnH2n", "CnH2n-2", "CnHn"], answer: 1, why: "One double bond removes two hydrogens from the alkane formula CnH2n+2." },
  { topic: "Isomerism", exam: true, q: "The number of possible structural isomers of butane (C4H10) is:", options: ["1", "2", "3", "4"], answer: 1, why: "n-butane (straight chain) and isobutane (branched)." },
  { topic: "Homologous Series", exam: true, q: "The difference in molecular mass between two successive members of a homologous series is:", options: ["12 u", "14 u", "16 u", "2 u"], answer: 1, why: "Successive members differ by a –CH2– unit = 12 + 2 = 14 u." },
  { topic: "Functional Groups", exam: true, q: "The functional group –COOH belongs to:", options: ["Alcohols", "Aldehydes", "Carboxylic acids", "Ketones"], answer: 2, why: "–COOH is the carboxyl group (e.g. ethanoic acid CH3COOH)." },
  { topic: "Reactions of Carbon Compounds", exam: true, q: "Oxidation of ethanol with alkaline KMnO4 (or acidified K2Cr2O7) gives:", options: ["Ethane", "Ethanoic acid", "Ethene", "Methane"], answer: 1, why: "CH3CH2OH → CH3COOH; the oxidising agents supply the oxygen." },
  { topic: "Reactions of Carbon Compounds", exam: true, q: "Hydrogenation of vegetable oils (unsaturated) to form vanaspati ghee uses the catalyst:", options: ["Iron", "Nickel", "Copper", "Zinc"], answer: 1, why: "Ni (or Pd/Pt) catalyses addition of H2 across the double bonds." },
  { topic: "Soaps & Detergents", exam: true, q: "Saponification is:", options: ["Ester + NaOH → soap + alcohol", "Acid + alcohol → ester", "Soap + HCl → fatty acid", "Oil + water"], answer: 0, why: "Base hydrolyses the ester (fat/oil) into soap (sodium salt of fatty acid) and glycerol." },
  { topic: "Soaps & Detergents", exam: true, q: "In a micelle, the arrangement of soap molecules is:", options: ["Ionic head inward, tail outward", "Hydrocarbon tail inward, ionic end outward", "Random", "Only heads"], answer: 1, why: "Tails dissolve in the grease droplet at the centre; ionic ends face the water, emulsifying the dirt." },
  { topic: "Soaps & Detergents", exam: true, q: "Soaps fail to clean well in hard water because they form an insoluble scum with:", options: ["Na+ and K+", "Ca2+ and Mg2+", "Cl- ions", "H+ ions"], answer: 1, why: "Calcium and magnesium salts of fatty acids precipitate as scum; detergents work in hard water." },
  { topic: "Allotropes", exam: true, q: "The allotrope of carbon that conducts electricity is:", options: ["Diamond", "Graphite", "Fullerene solid", "Charcoal"], answer: 1, why: "In graphite one valence electron per carbon is free to move between layers." },
  { topic: "Reactions of Carbon Compounds", q: "The gas evolved when ethanol reacts with sodium metal is:", options: ["Oxygen", "Hydrogen", "CO2", "Methane"], answer: 1, why: "2C2H5OH + 2Na → 2C2H5ONa + H2↑." },
  { topic: "Everyday Chemistry", q: "Denatured alcohol is:", options: ["Pure ethanol", "Ethanol mixed with methanol to make it unfit for drinking", "Ethanol + water 50%", "Acetic acid"], answer: 1, why: "Methanol (a poison) is added so industrial alcohol cannot be consumed." },
],

/* ============ CH 5 — PERIODIC CLASSIFICATION ============ */
"science-0-4": [
  { topic: "Modern Periodic Table", exam: true, q: "The modern periodic table is based on:", options: ["Atomic mass", "Atomic number", "Neutron number", "Density"], answer: 1, why: "Moseley showed atomic number is the fundamental property; properties repeat with Z." },
  { topic: "Modern Periodic Table", exam: true, q: "The number of groups and periods in the modern periodic table are:", options: ["7 groups, 18 periods", "18 groups, 7 periods", "8 groups, 7 periods", "18 groups, 8 periods"], answer: 1, why: "18 vertical groups and 7 horizontal periods." },
  { topic: "Early Attempts", exam: true, q: "Newlands' Law of Octaves was found applicable only up to:", options: ["Oxygen", "Calcium", "Cobalt", "Bromine"], answer: 1, why: "Beyond calcium the pattern broke down; only 56 elements were known then." },
  { topic: "Mendeleev", exam: true, q: "Mendeleev's 'eka-silicon' turned out to be the element:", options: ["Gallium", "Germanium", "Scandium", "Silicon"], answer: 1, why: "Eka-aluminium = gallium, eka-silicon = germanium — his gaps were filled exactly as predicted." },
  { topic: "Trends", exam: true, q: "Moving left to right across a period, atomic size:", options: ["Increases", "Decreases", "Stays same", "First increases then decreases"], answer: 1, why: "Nuclear charge increases while electrons enter the same shell, pulling them in." },
  { topic: "Trends", exam: true, q: "Moving down a group, metallic character:", options: ["Decreases", "Increases", "Stays same", "Becomes zero"], answer: 1, why: "Outer electrons are farther from the nucleus and are lost more easily." },
  { topic: "Trends", exam: true, q: "The largest atom in the third period is:", options: ["Na", "Cl", "Ar", "Si"], answer: 0, why: "Size decreases across a period, so sodium (leftmost) is the largest." },
  { topic: "Groups", q: "The most electronegative element, placed in group 17, is:", options: ["Chlorine", "Fluorine", "Iodine", "Bromine"], answer: 1, why: "Fluorine has the strongest pull for a shared pair of electrons." },
  { topic: "Valency", q: "Across a period, the valency of elements with respect to hydrogen/oxygen changes as:", options: ["1 to 4 then 0", "Constant 8", "0 to 8 steadily", "Always 1"], answer: 0, why: "Valence electrons rise 1→4, then atoms prefer gaining electrons to complete the octet, falling to 0 at noble gases." },
  { topic: "Position of Elements", q: "An element with electronic configuration 2, 8, 2 belongs to:", options: ["Period 2, group 2", "Period 3, group 2", "Period 3, group 16", "Period 2, group 16"], answer: 1, why: "Three shells = period 3; two valence electrons = group 2 (it is magnesium)." },
  { topic: "Hydrogen's Position", q: "Hydrogen's position is considered anomalous because:", options: ["It is a metal", "It resembles both alkali metals and halogens", "It is a noble gas", "It has no electron"], answer: 1, why: "Like group 1 it has one electron and forms +1; like halogens it needs one electron and forms diatomic molecules." },
],

/* ============ CH 6 — LIFE PROCESSES ============ */
"science-0-5": [
  { topic: "Nutrition — Photosynthesis", exam: true, q: "In green plants, photosynthesis takes place in:", options: ["Mitochondria", "Chloroplast", "Nucleus", "Ribosome"], answer: 1, why: "Chlorophyll in the chloroplast traps light energy to make glucose from CO2 and water." },
  { topic: "Nutrition — Human", exam: true, q: "The enzyme in saliva that begins digestion of starch is:", options: ["Pepsin", "Salivary amylase", "Trypsin", "Lipase"], answer: 1, why: "Salivary amylase breaks starch into simpler sugar in the mouth." },
  { topic: "Nutrition — Human", exam: true, q: "Pepsin acts efficiently only in an acidic medium; the acid is provided by:", options: ["Gastric glands (HCl)", "Saliva", "Bile", "Pancreatic juice"], answer: 0, why: "HCl from gastric glands creates the low pH needed for pepsin to digest proteins." },
  { topic: "Nutrition — Human", exam: true, q: "Digested food is absorbed mainly in the:", options: ["Stomach", "Small intestine (villi)", "Large intestine", "Oesophagus"], answer: 1, why: "Villi increase the surface area for absorption into the blood." },
  { topic: "Respiration", exam: true, q: "The energy currency of the cell is:", options: ["Glucose", "ATP", "DNA", "Chlorophyll"], answer: 1, why: "ATP releases energy on breaking its phosphate bond wherever the cell needs it." },
  { topic: "Respiration", exam: true, q: "In human muscle cells during heavy exercise, anaerobic respiration produces:", options: ["Ethanol and CO2", "Lactic acid", "Oxygen", "Starch"], answer: 1, why: "Lack of O2 forces glucose → lactic acid; its build-up causes cramps." },
  { topic: "Respiration", q: "Yeast carries out anaerobic respiration producing:", options: ["Ethanol + CO2", "Lactic acid", "Water + O2", "Urea"], answer: 0, why: "Fermentation: glucose → ethanol + CO2 + energy (used in brewing/baking)." },
  { topic: "Transportation", exam: true, q: "The chamber of the human heart with the thickest muscular wall is the:", options: ["Right atrium", "Left atrium", "Left ventricle", "Right ventricle"], answer: 2, why: "It pumps blood to the entire body, so it needs the greatest force." },
  { topic: "Transportation", exam: true, q: "Water and minerals move upward in plants through the:", options: ["Phloem", "Xylem", "Cortex", "Stomata"], answer: 1, why: "Xylem conducts water/minerals up; phloem translocates food both ways." },
  { topic: "Transportation", q: "The normal blood pressure of a healthy adult is about:", options: ["120/80 mm Hg", "80/120 mm Hg", "140/90 mm Hg", "110/70 mm Hg only"], answer: 0, why: "Systolic 120, diastolic 80 mm of mercury is taken as normal." },
  { topic: "Excretion", exam: true, q: "The structural and functional unit of the human kidney is the:", options: ["Neuron", "Nephron", "Alveolus", "Villus"], answer: 1, why: "Nephrons filter the blood and form urine." },
  { topic: "Excretion", q: "When kidneys fail, waste removal is done artificially by:", options: ["Dialysis", "Transfusion", "Transplantation only", "Catheter"], answer: 0, why: "Dialysis machines filter nitrogenous wastes from the blood." },
  { topic: "Nutrition — Photosynthesis", q: "The pores on leaves that allow gas exchange, guarded by guard cells, are:", options: ["Lenticels", "Stomata", "Root hairs", "Hydathodes"], answer: 1, why: "Guard cells swell or shrink with water to open/close the stomatal pore." },
],

/* ============ CH 7 — CONTROL AND COORDINATION ============ */
"science-0-6": [
  { topic: "Neuron", exam: true, q: "The correct path of an impulse in a neuron is:", options: ["Axon → cell body → dendrite", "Dendrite → cell body → axon → nerve ending", "Cell body → dendrite → axon", "Synapse → dendrite → axon"], answer: 1, why: "Signal is received at dendrites, integrated in the cell body and sent down the axon to the synapse." },
  { topic: "Reflex Action", exam: true, q: "The pathway from receptor to effector in a reflex is called the:", options: ["Neural cycle", "Reflex arc", "Synapse", "Hormonal path"], answer: 1, why: "Receptor → sensory neuron → spinal cord (relay) → motor neuron → effector muscle." },
  { topic: "Brain", exam: true, q: "Which part of the brain controls posture, balance and precision of voluntary actions?", options: ["Forebrain", "Cerebellum", "Medulla", "Hypothalamus"], answer: 1, why: "The cerebellum coordinates smooth, balanced muscular activity." },
  { topic: "Brain", exam: true, q: "Involuntary actions such as blood pressure, vomiting and salivation are controlled by the:", options: ["Cerebrum", "Medulla", "Cerebellum", "Cortex"], answer: 1, why: "The medulla in the hindbrain governs involuntary vital functions." },
  { topic: "Hormones", exam: true, q: "The 'emergency' hormone that prepares the body for fight or flight is:", options: ["Insulin", "Adrenaline", "Thyroxine", "Oestrogen"], answer: 1, why: "Adrenaline raises heart rate, breathing and blood flow to muscles in emergencies." },
  { topic: "Hormones", exam: true, q: "Deficiency of growth hormone in childhood causes:", options: ["Gigantism", "Dwarfism", "Goitre", "Diabetes"], answer: 1, why: "Growth hormone from the pituitary regulates body growth." },
  { topic: "Hormones", exam: true, q: "The hormone that lowers blood sugar level is:", options: ["Glucagon", "Insulin", "Adrenaline", "Thyroxine"], answer: 1, why: "Insulin from the pancreas helps cells take up glucose; its deficiency causes diabetes." },
  { topic: "Hormones", exam: true, q: "Iodine is essential for the synthesis of which hormone?", options: ["Insulin", "Thyroxine", "Adrenaline", "Testosterone"], answer: 1, why: "The thyroid needs iodine to make thyroxine; deficiency causes goitre." },
  { topic: "Coordination in Plants", exam: true, q: "The growth movement of a plant shoot towards light is:", options: ["Geotropism", "Phototropism", "Hydrotropism", "Chemotropism"], answer: 1, why: "Shoots grow towards light (positive phototropism); roots grow away from it." },
  { topic: "Coordination in Plants", exam: true, q: "The plant hormone that promotes cell division and is abundant in growing regions is:", options: ["Abscisic acid", "Cytokinin", "Auxin only", "Gibberellin only"], answer: 1, why: "Cytokinins promote cell division, e.g. in fruits and seeds." },
  { topic: "Coordination in Plants", q: "The coiling of a tendril around a support is caused by:", options: ["Auxin moving to the shaded/untouched side", "Gibberellin shrinking cells", "Abscisic acid", "Ethylene"], answer: 0, why: "Auxin distribution makes cells on the side away from contact grow faster, coiling the tendril." },
  { topic: "Neuron", q: "The gap where one neuron passes the signal to the next using chemicals is the:", options: ["Axon", "Synapse", "Dendrite", "Myelin"], answer: 1, why: "At the synapse, neurotransmitters carry the impulse across the gap." },
],

/* ============ CH 8 — HOW DO ORGANISMS REPRODUCE ============ */
"science-0-7": [
  { topic: "Asexual Reproduction", exam: true, q: "Budding is the mode of asexual reproduction in:", options: ["Amoeba", "Hydra", "Plasmodium", "Leishmania"], answer: 1, why: "A bud forms on Hydra's body, enlarges and detaches as a new individual." },
  { topic: "Asexual Reproduction", exam: true, q: "The bread mould Rhizopus reproduces asexually by:", options: ["Binary fission", "Spore formation", "Budding", "Fragmentation only"], answer: 1, why: "Spores in the sporangium germinate into new individuals under favourable conditions." },
  { topic: "Asexual Reproduction", q: "Vegetative propagation is seen in:", options: ["Rose and banana", "Mango and wheat", "Rice and maize", "Rose and mango"], answer: 0, why: "Rose (stem cutting) and banana (suckers) are propagated vegetatively; they also show why such plants fruit earlier." },
  { topic: "Sexual Reproduction — Flower", exam: true, q: "The male germ cells of a flower are carried in the:", options: ["Ovules", "Pollen grains", "Petals", "Sepals"], answer: 1, why: "Pollen grains from the anther carry the male gametes to the stigma." },
  { topic: "Sexual Reproduction — Flower", exam: true, q: "Fertilisation in a flower takes place in the:", options: ["Stigma", "Style", "Ovule (ovary)", "Anther"], answer: 2, why: "The pollen tube delivers male gametes to the ovule inside the ovary." },
  { topic: "Human Reproduction", exam: true, q: "In human males, the testes are located in the scrotum outside the body because:", options: ["Sperm formation needs a lower temperature", "More space is needed", "Hormones are made there only", "To protect them"], answer: 0, why: "Spermatogenesis requires 2–3°C below normal body temperature." },
  { topic: "Human Reproduction", exam: true, q: "The site of fertilisation in the human female is the:", options: ["Uterus", "Ovary", "Oviduct (fallopian tube)", "Cervix"], answer: 2, why: "The egg meets the sperm in the oviduct; the embryo then implants in the uterus." },
  { topic: "Human Reproduction", exam: true, q: "The embryo gets nutrition from the mother's blood through the:", options: ["Uterus wall", "Placenta", "Ovary", "Zygote"], answer: 1, why: "The placenta is the specialised tissue exchanging nutrients, gases and wastes." },
  { topic: "Reproductive Health", exam: true, q: "Which of these is a barrier method of contraception?", options: ["Copper-T", "Oral pills", "Condom", "Vasectomy"], answer: 2, why: "Condoms block sperm from meeting the egg and also protect against STDs." },
  { topic: "Reproductive Health", exam: true, q: "The sexually transmitted disease caused by a virus is:", options: ["Syphilis", "Gonorrhoea", "AIDS (HIV)", "Chlamydiasis"], answer: 2, why: "HIV is a virus; syphilis and gonorrhoea are bacterial." },
  { topic: "Significance of Reproduction", exam: true, q: "DNA copying during reproduction is important because it:", options: ["Keeps the body-size same", "Brings variation useful for survival", "Prevents ageing", "Produces energy"], answer: 1, why: "Small variations accumulate and help populations survive changed conditions." },
  { topic: "Puberty", q: "Which change is NOT a common sign of puberty in both boys and girls?", options: ["Growth of body hair", "Development of sex organs", "Onset of menstruation", "Emotional changes"], answer: 2, why: "Menstruation begins only in girls; the other changes occur in both sexes." },
],

/* ============ CH 9 — HEREDITY AND EVOLUTION ============ */
"science-0-8": [
  { topic: "Mendel's Experiments", exam: true, q: "In Mendel's monohybrid cross (Tt × Tt), the phenotypic ratio in F2 is:", options: ["1 : 1", "3 : 1", "9 : 3 : 3 : 1", "1 : 2 : 1"], answer: 1, why: "Three tall to one dwarf; genotypic ratio is 1 TT : 2 Tt : 1 tt." },
  { topic: "Mendel's Experiments", exam: true, q: "The 9 : 3 : 3 : 1 ratio in F2 is obtained in a:", options: ["Monohybrid cross", "Dihybrid cross", "Test cross", "Back cross"], answer: 1, why: "Two traits (e.g. seed shape and colour) assort independently in a dihybrid cross." },
  { topic: "Mendel's Experiments", q: "The trait that expresses itself even in the presence of an alternative factor is:", options: ["Recessive", "Dominant", "Hybrid", "Lethal"], answer: 1, why: "Dominant (T) masks recessive (t) in the Tt condition." },
  { topic: "Sex Determination", exam: true, q: "The sex of a human child is determined by:", options: ["The mother's egg", "The father's sperm", "The uterus", "Nutrition during pregnancy"], answer: 1, why: "Eggs carry only X; sperm carry X or Y — the fertilising sperm decides the sex." },
  { topic: "Inheritance", exam: true, q: "Which of these is an acquired (NOT inherited) trait?", options: ["Skin colour", "Eye colour", "Developed muscles of a wrestler", "Blood group"], answer: 2, why: "Acquired traits involve changes in non-reproductive tissues and cannot pass to the next generation." },
  { topic: "Evolution", exam: true, q: "Organs with the same basic structure but different functions (e.g. frog, lizard, bird forelimbs) are:", options: ["Analogous organs", "Homologous organs", "Vestigial organs", "Fossil organs"], answer: 1, why: "Same underlying design, different function — evidence of common ancestry (divergent evolution)." },
  { topic: "Evolution", exam: true, q: "Wings of a butterfly and wings of a bat are:", options: ["Homologous", "Analogous", "Vestigial", "Identical in structure"], answer: 1, why: "Different structures performing the same function — analogous (convergent evolution)." },
  { topic: "Evolution", exam: true, q: "Fossils found in deeper layers of the earth are:", options: ["Newer", "Older", "Of the same age", "Always mammals"], answer: 1, why: "Deeper strata were deposited earlier, so their fossils are older." },
  { topic: "Evolution", exam: true, q: "From wild cabbage, humans selected and produced cauliflower, broccoli, kale and kohlrabi. This is:", options: ["Natural selection", "Artificial selection", "Genetic drift", "Speciation"], answer: 1, why: "Human-directed selection of different parts of the same wild species." },
  { topic: "Evolution", q: "Which statement is CORRECT about evolution?", options: ["Humans evolved from chimpanzees", "Evolution always means progress", "Evolution is a gradual change over generations", "Only useful traits appear on demand"], answer: 2, why: "Evolution is descent with modification over generations; humans and chimps share a common ancestor." },
  { topic: "Speciation", q: "New species can arise when populations are:", options: ["Geographically isolated and genetically drifted", "Kept in the same field", "Fed identically", "Crossed every generation"], answer: 0, why: "Isolation stops gene flow; drift and selection then differentiate the populations." },
  { topic: "Inheritance", q: "A cross between TT and tt gives F1 plants that are:", options: ["All TT", "All Tt (tall)", "All tt", "Half TT half tt"], answer: 1, why: "Every F1 gets one T and one t — heterozygous and tall." },
],

/* ============ CH 10 — LIGHT: REFLECTION AND REFRACTION ============ */
"science-0-9": [
  { topic: "Spherical Mirrors", exam: true, q: "The focal length of a spherical mirror equals:", options: ["R", "R/2", "2R", "R/4"], answer: 1, why: "For small apertures, f = R/2." },
  { topic: "Spherical Mirrors", exam: true, q: "To get a virtual, erect and magnified image with a concave mirror, the object must be placed:", options: ["Beyond C", "At C", "Between F and C", "Between P and F"], answer: 3, why: "Inside the focus the concave mirror gives a virtual, erect, enlarged image — used in shaving mirrors." },
  { topic: "Spherical Mirrors", exam: true, q: "Rear-view mirrors in vehicles are convex because they:", options: ["Magnify objects", "Give a wider field of view with erect images", "Give real images", "Focus light"], answer: 1, why: "Convex mirrors always form erect, diminished images over a wide field." },
  { topic: "Sign Convention & Formula", exam: true, q: "The mirror formula is:", options: ["1/v + 1/u = 1/f", "v - u = f", "v × u = f", "1/v - 1/u = 1/f"], answer: 0, why: "1/v + 1/u = 1/f relates object distance, image distance and focal length." },
  { topic: "Refraction", exam: true, q: "A ray entering from a rarer to a denser medium bends:", options: ["Away from the normal", "Towards the normal", "Not at all", "Back completely"], answer: 1, why: "Light slows down in the denser medium, bending towards the normal." },
  { topic: "Refraction", exam: true, q: "The refractive index of glass is 1.5. The speed of light in glass is:", options: ["3 × 10^8 m/s", "2 × 10^8 m/s", "4.5 × 10^8 m/s", "1.5 × 10^8 m/s"], answer: 1, why: "v = c/n = 3×10^8 / 1.5 = 2×10^8 m/s." },
  { topic: "Lenses", exam: true, q: "A lens of power +2 D is a:", options: ["Concave lens of f = 0.5 m", "Convex lens of f = 0.5 m", "Convex lens of f = 2 m", "Concave lens of f = 2 m"], answer: 1, why: "Positive power = convex; f = 1/P = 1/2 = 0.5 m." },
  { topic: "Lenses", q: "The image formed by a concave lens is always:", options: ["Real and inverted", "Virtual, erect and diminished", "Virtual and magnified", "Real and diminished"], answer: 1, why: "A diverging lens can never form a real image of a real object." },
  { topic: "Everyday Refraction", q: "A pencil partly immersed in water appears bent at the surface because of:", options: ["Reflection", "Refraction", "Dispersion", "Scattering"], answer: 1, why: "Light from the submerged part bends on leaving water, shifting the apparent position." },
  { topic: "Everyday Refraction", q: "A swimming pool appears shallower than it really is due to:", options: ["Reflection of light", "Refraction of light", "Total absorption", "Diffraction"], answer: 1, why: "The apparent depth is less than real depth because rays bend away from the normal at the water surface." },
  { topic: "Magnification", exam: true, q: "The magnification produced by a spherical mirror is m = ", options: ["-v/u", "u/v", "f/u", "u×v"], answer: 0, why: "m = h'/h = -v/u for mirrors; a negative m means a real, inverted image." },
],

/* ============ CH 11 — HUMAN EYE AND COLOURFUL WORLD ============ */
"science-0-10": [
  { topic: "The Eye", exam: true, q: "The least distance of distinct vision for a normal adult eye is:", options: ["25 m", "25 cm", "2.5 cm", "Infinity"], answer: 1, why: "Objects closer than 25 cm cannot be seen clearly without strain." },
  { topic: "The Eye", exam: true, q: "The ability of the eye lens to adjust its focal length is called:", options: ["Dispersion", "Accommodation", "Persistence of vision", "Scattering"], answer: 1, why: "Ciliary muscles change the lens curvature to focus near and far objects." },
  { topic: "Defects of Vision", exam: true, q: "A person who cannot see distant objects clearly suffers from:", options: ["Hypermetropia", "Myopia", "Presbyopia", "Cataract"], answer: 1, why: "Myopia (near-sightedness): image forms in front of the retina; corrected with a concave lens." },
  { topic: "Defects of Vision", exam: true, q: "Hypermetropia is corrected using a:", options: ["Concave lens", "Convex lens", "Cylindrical lens", "Bifocal lens only"], answer: 1, why: "A convex lens converges light so the near object focuses on the retina." },
  { topic: "Defects of Vision", q: "The defect arising with age, requiring bifocal lenses, is:", options: ["Myopia", "Presbyopia", "Astigmatism", "Night blindness"], answer: 1, why: "Weakening accommodation with age; bifocals combine concave (distant) and convex (near) parts." },
  { topic: "Prism & Dispersion", exam: true, q: "The splitting of white light into seven colours by a prism is:", options: ["Reflection", "Dispersion", "Scattering", "Refraction only"], answer: 1, why: "Different colours bend by different amounts — VIBGYOR, violet most, red least." },
  { topic: "Atmospheric Refraction", exam: true, q: "Stars twinkle because of:", options: ["Dispersion in the eye", "Atmospheric refraction of starlight", "Reflection from clouds", "Their own flicker"], answer: 1, why: "Changing atmospheric layers keep shifting the apparent position and brightness of the point source." },
  { topic: "Atmospheric Refraction", exam: true, q: "The sun appears about 2 minutes early at sunrise (and late at sunset) due to:", options: ["Dispersion", "Atmospheric refraction", "Scattering", "Reflection"], answer: 1, why: "Refraction bends sunlight over the horizon, advancing the apparent sunrise." },
  { topic: "Scattering", exam: true, q: "The sky appears blue because:", options: ["Air scatters blue light more than red", "The sea reflects blue", "Ozone is blue", "The eye is more tired"], answer: 0, why: "Fine air particles scatter shorter (blue) wavelengths much more strongly." },
  { topic: "Scattering", exam: true, q: "Danger signals are red because red light is:", options: ["Scattered the most", "Scattered the least and travels farthest", "Absorbed fully", "Fastest in air"], answer: 1, why: "Longest visible wavelength scatters least, so red remains visible from far in fog/smoke." },
],

/* ============ CH 12 — ELECTRICITY ============ */
"science-0-11": [
  { topic: "Ohm's Law", exam: true, q: "Ohm's law states that:", options: ["V = IR", "V = I/R", "R = VI", "I = VR"], answer: 0, why: "Potential difference is directly proportional to current at constant temperature." },
  { topic: "Charge & Current", exam: true, q: "If a current of 2 A flows for 10 s, the charge that passes is:", options: ["5 C", "20 C", "0.2 C", "12 C"], answer: 1, why: "Q = I × t = 2 × 10 = 20 coulombs." },
  { topic: "Resistance", exam: true, q: "The resistance of a wire does NOT depend on its:", options: ["Length", "Area of cross-section", "Material", "Shape of the container"], answer: 3, why: "R = ρL/A — length, thickness and material (resistivity) decide it; the container is irrelevant." },
  { topic: "Resistivity", exam: true, q: "When a wire of resistivity ρ is cut into two equal halves, the resistivity of each half is:", options: ["ρ/2", "2ρ", "ρ", "ρ²"], answer: 2, why: "Resistivity is a property of the material, not of the dimensions." },
  { topic: "Combination of Resistors", exam: true, q: "Three resistors of 3 Ω each in series give an equivalent resistance of:", options: ["1 Ω", "3 Ω", "9 Ω", "27 Ω"], answer: 2, why: "Series: R = R1 + R2 + R3 = 9 Ω." },
  { topic: "Combination of Resistors", exam: true, q: "Two resistors of 4 Ω each connected in parallel give:", options: ["8 Ω", "2 Ω", "4 Ω", "16 Ω"], answer: 1, why: "1/R = 1/4 + 1/4 = 1/2 → R = 2 Ω." },
  { topic: "Domestic Circuits", exam: true, q: "In household wiring, appliances are connected in:", options: ["Series", "Parallel", "Both randomly", "Neither"], answer: 1, why: "Parallel gives each appliance the full voltage and independent switching." },
  { topic: "Heating Effect", exam: true, q: "The heat produced in a resistor is given by:", options: ["H = I²Rt", "H = IR²t", "H = V²Rt", "H = It/R"], answer: 0, why: "Joule's law of heating: H = I²Rt." },
  { topic: "Heating Effect", exam: true, q: "The heating element of an electric heater is made of:", options: ["Copper", "Nichrome", "Aluminium", "Silver"], answer: 1, why: "Nichrome has high resistivity and does not oxidise easily at high temperature." },
  { topic: "Safety", exam: true, q: "A fuse wire is connected in:", options: ["Parallel with the appliance", "Series in the live line", "Across the neutral", "Inside the appliance only"], answer: 1, why: "In series it melts on excess current and breaks the circuit." },
  { topic: "Electric Power", exam: true, q: "1 kilowatt-hour equals:", options: ["3.6 × 10^6 J", "3.6 × 10^3 J", "36 J", "3.6 J"], answer: 0, why: "1 kWh = 1000 W × 3600 s = 3.6 × 10^6 J — the commercial 'unit' of energy." },
  { topic: "Electric Power", exam: true, q: "An electric bulb rated 100 W at 220 V draws a current of about:", options: ["0.45 A", "2.2 A", "4.5 A", "0.22 A"], answer: 0, why: "I = P/V = 100/220 ≈ 0.45 A." },
  { topic: "Ohm's Law", q: "If the potential difference across a fixed resistor is doubled, the current:", options: ["Halves", "Doubles", "Stays same", "Becomes zero"], answer: 1, why: "I ∝ V for a constant resistance." },
],

/* ============ CH 13 — MAGNETIC EFFECTS OF CURRENT ============ */
"science-0-12": [
  { topic: "Magnetic Field", exam: true, q: "Magnetic field lines never intersect because:", options: ["They are too weak", "At an intersection the compass would point in two directions", "They repel each other", "They are circular"], answer: 1, why: "A single point cannot have two directions of the magnetic field." },
  { topic: "Field of a Current", exam: true, q: "The direction of the magnetic field around a straight current-carrying wire is given by:", options: ["Fleming's left-hand rule", "The right-hand thumb rule", "Lenz's law", "Faraday's law"], answer: 1, why: "Thumb along the current; curled fingers give the direction of field lines." },
  { topic: "Solenoid", exam: true, q: "The field inside a current-carrying solenoid is:", options: ["Zero", "Uniform (same at all points)", "Circular and varying", "Strongest outside"], answer: 1, why: "Parallel, equally spaced lines inside show a uniform field, like a bar magnet." },
  { topic: "Force on Conductor", exam: true, q: "The force on a current-carrying conductor in a magnetic field is maximum when the current is:", options: ["Parallel to the field", "Perpendicular to the field", "At 45°", "Zero"], answer: 1, why: "F is maximum when I ⊥ B; its direction is given by Fleming's left-hand rule." },
  { topic: "Motors & Generators", exam: true, q: "Fleming's left-hand rule is used to find the direction of force in a:", options: ["Generator", "Electric motor", "Fuse", "Resistor"], answer: 1, why: "Motors convert electrical energy to motion using the force on a current in a field." },
  { topic: "Electromagnetic Induction", exam: true, q: "Moving a magnet towards a coil produces an induced current. This phenomenon is:", options: ["Heating effect", "Electromagnetic induction", "Magnetisation", "Short circuit"], answer: 1, why: "A changing magnetic field induces a current — Faraday's discovery, the basis of generators." },
  { topic: "Electromagnetic Induction", exam: true, q: "The direction of induced current is given by:", options: ["Fleming's right-hand rule", "Fleming's left-hand rule", "Right-hand thumb rule", "Ohm's law"], answer: 0, why: "Right-hand rule: motion, field and induced current are mutually perpendicular." },
  { topic: "AC & DC", exam: true, q: "The frequency of AC supply in India is:", options: ["60 Hz", "50 Hz", "100 Hz", "25 Hz"], answer: 1, why: "Indian mains is 220 V, 50 Hz; the current reverses direction 100 times per second." },
  { topic: "Domestic Circuits", exam: true, q: "In a domestic circuit, the wire with green insulation is the:", options: ["Live wire", "Neutral wire", "Earth wire", "Fuse wire"], answer: 2, why: "Earth wire safely carries leakage current to the ground, preventing shocks." },
  { topic: "Domestic Circuits", exam: true, q: "A short circuit occurs when:", options: ["The fuse blows", "Live and neutral wires come into direct contact", "The earth wire is cut", "Appliances are in parallel"], answer: 1, why: "Direct live–neutral contact makes resistance nearly zero, so the current becomes dangerously high." },
  { topic: "Electromagnets", q: "The core of an electromagnet is usually made of:", options: ["Steel", "Soft iron", "Copper", "Aluminium"], answer: 1, why: "Soft iron gains and loses magnetism quickly, ideal for a controllable magnet." },
  { topic: "Field of a Current", q: "On increasing the current through a wire, the deflection of a nearby compass needle:", options: ["Decreases", "Increases", "Stays same", "Becomes zero"], answer: 1, why: "Field strength is proportional to current, so the needle deflects more." },
],
};
