/* SK Presidency Public School — Half Yearly Exam 2025-26, Class 10 SST (M.M. 80)
   Verbatim transcription of the school paper with full-marks model answers,
   NCERT-aligned (History: Nationalism in India / Nationalism in Europe;
   Polity: Power Sharing / Federalism / Democracy & Diversity;
   Economics: Development / Sectors / Money & Credit; Geo: Resources / Water). */

export interface SSTQ {
  n: string; /* printed number, e.g. "1", "29.I", "35.2", "37.a" */
  q: string;
  opts?: string[];
  ans: string;
  marks: number;
}

export const SST_PAPER_META = {
  school: "SK Presidency Public School",
  exam: "Half Yearly Examination 2025-26",
  cls: "Class 10",
  subject: "Social Science (SST)",
  mm: 80,
  time: "3 hours",
};

export const SST_SECTIONS: { label: string; blurb: string; qs: SSTQ[] }[] = [
  {
    label: "Section A — Multiple Choice Questions (20 x 1 = 20)",
    blurb: "Choose the correct option. Reason included for every answer.",
    qs: [
      { n: "1", q: "Which of the following subjects is included in the Union list?", opts: ["Defence", "Banking", "Communication", "All of these"], ans: "(d) All of these. Defence, banking and communication are all subjects of national importance, so all three figure in the Union List.", marks: 1 },
      { n: "2", q: "............... and ............... formed the Swaraj Party?", opts: ["C.R. Das & Motilal Nehru", "Jawahar Lal Nehru & Gandhiji", "Subhash Chandra Bose & Motilal Nehru", "None of these"], ans: "(a) C.R. Das & Motilal Nehru. After the Non-Cooperation Movement was withdrawn (1922), they formed the Swaraj Party (1923) to oppose British policy from within the councils.", marks: 1 },
      { n: "3", q: "The distinguishing feature of a federal government is", opts: ["National government gives some powers to the provincial governments.", "Power is distributed among the legislature, executive and judiciary.", "Elected officials exercise supreme power in the government.", "Governmental power is divided between different levels."], ans: "(d) Governmental power is divided between different levels. (Option b describes horizontal division of power, not federalism.)", marks: 1 },
      { n: "4", q: "Who proclaimed the dams as the temples of modern India?", opts: ["Dr. Rajendra Prasad", "Narendra Modi", "Bheem Rao Ambedkar", "None of these"], ans: "(d) None of these. It was Jawaharlal Nehru who called dams \u201cthe temples of modern India\u201d.", marks: 1 },
      { n: "5", q: "The word 'ethnic' signifies:", opts: ["different religions", "social division on shared culture", "a vicious conflict between opposite groups", "a careful calculation of gains and losses"], ans: "(b) Social division on shared culture. The term \u201cethnic\u201d signifies social division based on shared culture and common descent.", marks: 1 },
      { n: "6", q: "In India, seats are reserved for women in", opts: ["Lok Sabha", "Cabinets", "State Legislatures", "Panchayati Raj bodies"], ans: "(d) Panchayati Raj bodies. One-third of the total seats (and chairperson positions) in panchayats and municipalities are reserved for women.", marks: 1 },
      { n: "7", q: "Feminist movement are aimed at", opts: ["Liberty", "Equality", "Participation", "Power"], ans: "(b) Equality. Feminist movements seek equal rights and equal opportunities for women in education, work and politics.", marks: 1 },
      { n: "8", q: "Which one of the following is not a cause of communalism?", opts: ["Religion is taken as the basis of the nation", "When one religion is discriminated against other", "State has no official religion", "Demands of one religious group are formed in opposition to another"], ans: "(c) State has no official religion. A secular state with no official religion prevents communalism; the other three options breed it.", marks: 1 },
      { n: "9", q: "Which one of the following source meet the needs of loan of rural household in India to the maximum extent?", opts: ["Commercial Bank", "Co-Operative Societies", "Money Lender", "Businessman"], ans: "(c) Money Lender. Despite the spread of banks and cooperatives, informal credit \u2014 above all the village moneylender \u2014 still meets the largest single share of rural credit needs, at high interest rates.", marks: 1 },
      { n: "10", q: "The concept of \"sustainable development\" involves:", opts: ["Rapid industrialization without environmental concerns", "Balancing economic growth with ecological concerns", "Isolating a country from global trade", "Focusing solely on agricultural development"], ans: "(b) Balancing economic growth with ecological concerns, so that present needs are met without damaging the environment for future generations.", marks: 1 },
      { n: "11", q: "Which one of the following is the majority community in Sri Lanka?", opts: ["Sinhalas", "Indian Tamil", "Sri Lankan Tamil", "Christian"], ans: "(a) Sinhalas (about 74% of the population; Sri Lankan Tamils ~13%, Indian Tamils ~5%).", marks: 1 },
      { n: "12", q: "The value of all final goods and services produced within a country during a particular year is called.", opts: ["Gross Domestic Product", "Net Domestic Product", "National Product", "National Income"], ans: "(a) Gross Domestic Product (GDP).", marks: 1 },
      { n: "13", q: "Development of a country can generally be determined by", opts: ["Its per capita income", "Its average literacy level", "The health status of its people", "All of these"], ans: "(d) All of these. Per-capita income, literacy and health together indicate a country's level of development.", marks: 1 },
      { n: "14", q: "Which state has made rooftop rainwater harvesting structure compulsory to all the houses across the state?", opts: ["Kerala", "Karnataka", "Tamil Nadu", "Andhra Pradesh"], ans: "(c) Tamil Nadu \u2014 it is legally compulsory for every house to have a rooftop rainwater harvesting structure.", marks: 1 },
      { n: "15", q: "Which of the following is included in tertiary sector?", opts: ["Courier", "Fisherman", "Internet cafe", "a and c"], ans: "(d) a and c. Courier services and internet cafes provide services, not goods \u2014 hence tertiary. A fisherman belongs to the primary sector.", marks: 1 },
      { n: "16", q: "......... vertical division of power is.", opts: ["Power is shared among different organ of Govt.", "Power is shared among different pressure and group", "Power is shared among different social group", "Power is shared among different level of Govt."], ans: "(d) Power is shared among different levels of Govt. (Union \u2192 State \u2192 Local). Sharing among organs is the horizontal division.", marks: 1 },
      { n: "17", q: "In a federal system, what is the relationship between the central government and state governments?", opts: ["Central government has all the powers.", "State governments have all the powers.", "Both central and state governments share powers.", "All the financial powers are vested with the central government"], ans: "(c) Both central and state governments share powers, as divided by the Constitution (Union, State and Concurrent Lists).", marks: 1 },
      { n: "18", q: "In which of the following state is black soil found?", opts: ["Rajasthan", "Maharashtra", "Jharkhand", "Andhra Pradesh"], ans: "(b) Maharashtra. Black (regur) soil covers the Deccan trap belt \u2014 Maharashtra, Gujarat, parts of MP \u2014 and is ideal for cotton.", marks: 1 },
      { n: "19", q: "Which activities are typically categorized under the Primary sector of the Indian economy?", opts: ["Manufacturing and processing", "Agriculture and related activities", "Services and tourism", "Mining and quarrying only"], ans: "(b) Agriculture and related activities (also forestry, fishing, mining \u2014 activities that directly use natural resources).", marks: 1 },
      { n: "20", q: "Which of the following is not true about Indian Wildlife Protection Act?", opts: ["Implemented in 1972", "(torn in paper) It permits hunting/trade of protected species", "It includes project tiger", "(torn in paper)"], ans: "The NOT-true statement is the option claiming the Act permits hunting or trade of protected wildlife \u2014 the Act bans both. The visible statements are true: it was implemented in 1972, and Project Tiger (1973) was launched under it.", marks: 1 },
    ],
  },
  {
    label: "Section B — Very Short Answer Type (4 x 2 = 8)",
    blurb: "About 40 words each.",
    qs: [
      { n: "21", q: "Write a short note on Jallianwala bagh massacre.", ans: "On 13 April 1919, a large crowd gathered in Jallianwala Bagh, Amritsar \u2014 some to protest the arrest of Dr. Satyapal and Dr. Saifuddin Kitchlew, others unaware of the martial law. General Dyer blocked the only exit and ordered troops to fire on the unarmed crowd, killing hundreds including women and children. The massacre sparked strikes and violence across northern India and turned millions against British rule; Rabindranath Tagore renounced his knighthood in protest.", marks: 2 },
      { n: "22", q: "What is the importance of power sharing in democracy?", ans: "Power sharing (a) reduces the possibility of conflict between social groups, (b) prevents the tyranny of the majority, (c) ensures political stability, and (d) realises the democratic principle that people who are affected by governance must have a share in it \u2014 it is the very spirit of democracy.", marks: 2 },
      { n: "23", q: "Name two rainwater harvesting structure built in Rajasthan.", ans: "Khadin and Johad (earthen/check-dam structures that capture rainwater to recharge soil and groundwater). Tankas for storing drinking water are also acceptable.", marks: 2 },
      { n: "24", q: "Explain 'Narmada Bachao Andolan'?", ans: "Narmada Bachao Andolan is a mass movement of local villagers, farmers and environmentalists against the Sardar Sarovar Dam on the Narmada. It demanded proper rehabilitation of the roughly 2.5 lakh displaced families and highlighted the social and environmental cost of big dams; its pressure forced the government to make rehabilitation plans mandatory.", marks: 2 },
    ],
  },
  {
    label: "Section C — Short Answer Type (5 x 3 = 15)",
    blurb: "About 60 words each.",
    qs: [
      { n: "25", q: "Why did Non-Cooperation Movement gradually slow down in towns and cities?", ans: "(1) Khadi cloth was often more expensive than mass-produced British mill cloth, so the poor could not sustain the boycott. (2) Alternative Indian institutions (schools, colleges, courts) were too few \u2014 students and teachers drifted back to government institutions and lawyers returned to courts. (3) The economic boycott hurt traders and professionals. Without strong alternative institutions, enthusiasm in the cities faded.", marks: 3 },
      { n: "26", q: "What was the impact of First World War on India?", ans: "(1) Huge defence expenditure was financed by war loans and increased taxes \u2014 income tax was introduced and customs duties raised. (2) Prices nearly doubled between 1913 and 1918, hitting the common people hard. (3) Forced recruitment in villages and crop failures with the influenza epidemic caused acute hardship, while a few businessmen profited. This widespread anger strengthened the anti-British national movement.", marks: 3 },
      { n: "27", q: "What is Rainwater Harvesting? State the objectives of rainwater harvesting.", ans: "Rainwater harvesting is the technique of collecting and storing rainwater where it falls \u2014 on rooftops, tanks, ponds, check-dams \u2014 instead of letting it run off. Objectives: (1) meet increasing water demand, (2) reduce runoff and flooding, (3) recharge groundwater and raise the water table, (4) conserve soil moisture and check erosion, and (5) provide safe water in scarce regions.", marks: 3 },
      { n: "28", q: "What are Feminist movements? What are their major demands?", ans: "Feminist movements are political and social movements led for women's rights and equality with men. Major demands: equal pay for equal work; equal rights in law, property and education; equal access to jobs and careers; adequate representation in politics (reservation); and an end to discrimination, harassment and domestic violence.", marks: 3 },
      { n: "29.I", q: "Define the term of Credit and Collateral.", ans: "Credit is an agreement between a borrower and a lender in which the lender advances money against a promise of future repayment with interest. Collateral is an asset owned by the borrower \u2014 land, building, vehicle, livestock or bank deposits \u2014 that the lender keeps as security until the loan is repaid, and can take over if the borrower defaults.", marks: 1.5 },
      { n: "29.II", q: "Write the positive and negative role of credit.", ans: "Positive: credit lets farmers and small businesses invest in seeds, tools and enterprise, smooths consumption and helps set up new ventures \u2014 it boosts income and development when the return exceeds the interest. Negative: high-interest informal credit can trap the poor in a debt cycle; on crop failure or loss the borrower may lose the collateral (e.g. a farmer losing land), leaving him worse off than before.", marks: 1.5 },
    ],
  },
  {
    label: "Section D — Long Answer Type (4 x 5 = 20)",
    blurb: "About 120 words each. OR options answered separately.",
    qs: [
      { n: "30", q: "Mahatma Gandhi used Salt as a powerful symbol to unite the nation. Explain.", ans: "Salt was consumed by every Indian, rich and poor, so it touched every household. The government's salt tax and monopoly made the oppressive face of British rule visible in a daily necessity. Gandhi included abolition of the salt tax among his eleven demands; when ignored, he marched from Sabarmati to Dandi (12 March \u2013 6 April 1930, ~240 miles) with 78 volunteers and broke the law by making salt from sea water. This sparked the salt satyagraha nationwide \u2014 coastal villages made salt, boycotts spread, and people of every class, region and religion joined. Thus a humble crystal became the symbol that united the nation against colonial rule.", marks: 5 },
      { n: "30 OR", q: "What is average income? Why do you think average income is an important criteria for development?", ans: "Average income (per capita income) = total income of the country \u00f7 total population. It is important because total income alone says nothing about how well-off ordinary people are, and countries have different populations, so only per-head income allows comparison. Higher average income generally means people can afford better food, education and health, which is why it remains the key (though incomplete) yardstick of development.", marks: 5 },
      { n: "31", q: "Explain the difference between organized and unorganized sector.", ans: "Organized sector: establishments registered with the government; regular employment with job security; fixed working hours and overtime pay; benefits like provident fund, gratuity, paid leave and medical cover; regular monthly wages (e.g. government offices, factories, banks). Unorganized sector: small, scattered, unregistered units; irregular, low-paid work with no job security; no fixed hours, no leave or pension; easy exploitation of workers (e.g. agricultural labourers, street vendors, domestic help). Most workers in India are still in the unorganized sector, which is why labour protection there is a major concern.", marks: 5 },
      { n: "31 OR", q: "Describe any five features of Secularism in India.", ans: "(1) India has no official state religion. (2) Every citizen has the fundamental right to profess, practise and propagate any religion, or none. (3) The state may not discriminate against any citizen on grounds of religion. (4) The government can intervene in religion to enforce equality within religious communities \u2014 e.g. abolishing untouchability, reforming inheritance laws. (5) State policy treats all religious communities equally in law and public life \u2014 this separates India from a theocratic state and also from the strict 'wall of separation' model.", marks: 5 },
      { n: "32", q: "What do you know about the 'Bamboo-Drip Irrigation System'?", ans: "Bamboo-drip irrigation is a 200-year-old traditional system used in Meghalaya for betel leaf and black pepper cultivation. Water from perennial hilltop springs and streams is tapped and diverted through a network of bamboo pipes and channels, which reduce the flow to 20\u201380 drops per minute right at the base of the plant. It is cheap, wastes almost no water, works on steep slopes, and is built and managed entirely by farmers, who adjust the flow by changing pipe positions \u2014 a model of sustainable micro-irrigation.", marks: 5 },
      { n: "32 OR", q: "Describe how communities have conserved and protected forests and wildlife in India?", ans: "Communities protect forests through sacred groves (sarnas in Jharkhand/Chhattisgarh, devaris in Maharashtra) where no tree is cut; village patrolling committees that guard forests from outsiders; joint forest management, in which villages share responsibility and benefits with the forest department; and movements like Chipko, Appiko and Beej Bachao Andolan. Where communities have a direct stake \u2014 fodder, fuel, water \u2014 they enforce rules stricter than any law, and many community-protected forests are today denser than government-managed ones.", marks: 5 },
      { n: "33", q: "What is the status of women's representation in India's legislative bodies?", ans: "Women's representation in India's legislatures remains very low \u2014 the Lok Sabha has rarely crossed 10\u201315% women members and most state assemblies are below 10%, far behind several developing countries. In contrast, one-third reservation in panchayats and municipalities has brought over ten lakh women representatives into local bodies. The long-pending demand for 33% reservation in the Lok Sabha and assemblies (Women's Reservation Bill) was passed as the Nari Shakti Vandana Adhiniyam, 2023, but awaits implementation after a census \u2014 so at the top level Indian politics remains heavily male-dominated.", marks: 5 },
      { n: "33 OR", q: "Briefly trace the process of Unification of Italy.", ans: "Mid-19th century Italy was split into seven states, only Sardinia-Piedmont ruled by an Italian prince. Mazzini's Young Italy spread the idea of a united republic; the 1848 revolts failed. Then Chief Minister Cavour led the process: his diplomacy and alliance with France defeated Austrian forces in the north (1859). Meanwhile Garibaldi's Red Shirts freed South Italy and the Kingdom of Two Sicilies (1860) and handed them over. In 1861 Victor Emmanuel II was proclaimed king of united Italy. Thus unification came through ideas, war, diplomacy and popular armed action together.", marks: 5 },
    ],
  },
  {
    label: "Section E — Case Based Questions (3 x 4 = 12)",
    blurb: "Answers based on the given extracts.",
    qs: [
      { n: "34.1", q: "Why was 'Project Tiger' considered a significant step for Tiger Conservation?", ans: "Because it was India's first major species-conservation initiative (launched 1973): it set up dedicated tiger reserves, curbed poaching and protected tiger habitat, and succeeded in arresting \u2014 then reversing \u2014 the tiger's rapid decline.", marks: 1 },
      { n: "34.2", q: "What role did India play in the global tiger population?", ans: "India (with Nepal) provides habitat to about two-thirds of the world's tigers, making it the key country for the survival of the species; India's conservation model (Project Tiger) also inspired global tiger-conservation campaigns.", marks: 1 },
      { n: "34.3", q: "Mention any two major threats to the wildlife species.", ans: "Any two: (1) poaching and illegal trade \u2014 tiger bones and parts used in traditional medicines; (2) shrinking habitat due to deforestation and expanding human settlement; (3) depletion of prey base species.", marks: 2 },
      { n: "35.1", q: "What was the Gandhi-Irwin Pact?", ans: "An agreement signed on 5 March 1931 between Mahatma Gandhi and Viceroy Lord Irwin: Gandhi agreed to call off the Civil Disobedience Movement and attend the Second Round Table Conference; the government agreed to release all political prisoners imprisoned during the movement.", marks: 1 },
      { n: "35.2", q: "Why did Gandhiji go to London?", ans: "To attend the Second Round Table Conference and represent the Indian National Congress in talks on India's constitutional future, as per the Gandhi-Irwin Pact.", marks: 1 },
      { n: "35.3", q: "Why was Civil Disobedience Movement called off by Gandhiji?", ans: "The British responded with brutal repression \u2014 mass arrests and beatings of satyagrahis \u2014 and after the violence of 1922\u201330 Gandhi wanted to give negotiations a chance; so he signed the Gandhi-Irwin Pact and called off the movement to attend the Round Table Conference.", marks: 2 },
      { n: "36.1", q: "When was the use of English stopped for official purposes in India?", ans: "As per the Constitution, the use of English for official purposes was to stop in 1965. (In practice, after violent protests in non-Hindi states, English was allowed to continue alongside Hindi.)", marks: 1 },
      { n: "36.2", q: "Which other language was continued along with English for official purposes?", ans: "Hindi \u2014 the Centre agreed to continue English together with Hindi for official work.", marks: 2 },
      { n: "36.3", q: "Which state demanded the use of English to continue?", ans: "Tamil Nadu, where the anti-Hindi movement took a violent form.", marks: 1 },
    ],
  },
  {
    label: "Section F — Map Based Questions (5)",
    blurb: "Locate and label on the outline map of India.",
    qs: [
      { n: "37.a.I", q: "The place where the session of Indian National Congress occurred in 1920.", ans: "Calcutta (Kolkata), West Bengal \u2014 the special session of September 1920 that accepted the Non-Cooperation programme.", marks: 1 },
      { n: "37.a.II", q: "The place where Mahatma Gandhi broke Salt Law.", ans: "Dandi, on the Gujarat coast (Navsari district).", marks: 1 },
      { n: "37.b.1", q: "Hirakud (locate and label).", ans: "Hirakud Dam \u2014 on the Mahanadi river in Odisha (near Sambalpur), western Odisha on the map.", marks: 1 },
      { n: "37.b.2", q: "Tehri (locate and label).", ans: "Tehri Dam \u2014 in Uttarakhand, at the confluence of Bhagirathi and Bhilangana rivers (northern India).", marks: 1 },
      { n: "37.b.3", q: "Sardar Sarovar Dam (locate and label).", ans: "Sardar Sarovar Dam \u2014 on the Narmada river in Gujarat (near Rajpipla, south-east Gujarat).", marks: 1 },
      { n: "37.b.4", q: "Nagarjuna Sagar (locate and label).", ans: "Nagarjuna Sagar Dam \u2014 on the Krishna river at the Telangana\u2013Andhra Pradesh border (south-east of Hyderabad).", marks: 1 },
    ],
  },
];
