/* SST topic-wise MCQ bank — CIVICS / POLITICAL SCIENCE (Democratic Politics II).
   Chapters: 1 Power Sharing, 2 Federalism, 3 Gender, Religion and Caste.
   Topic-tagged per NCERT sub-heading. */
import type { QuizQ } from "./types";

const C1A = "Belgium and Sri Lanka";
const C1B = "Why Power Sharing is Desirable";
const C1C = "Forms of Power Sharing";

const C2A = "What is Federalism";
const C2B = "Union, State and Concurrent Lists";
const C2C = "Language Policy";
const C2D = "Centre-State Relations";
const C2E = "Decentralisation in India";

const C3A = "Gender and Politics";
const C3B = "Religion, Communalism and Politics";
const C3C = "Caste and Politics";

export const SST_MCQ_CIVICS: Record<string, QuizQ[]> = {

/* ============ CIVICS CHAPTER 1 ============ */
"sst-2-0": [
  { topic: C1A, q: "In Belgium, what percentage of the population lives in the Flemish region and speaks Dutch?", options: ["59 per cent", "40 per cent", "80 per cent", "20 per cent"], answer: 0, why: "Belgium has 59 per cent Dutch-speaking and 40 per cent French-speaking people, with 1 per cent German-speaking." },
  { topic: C1A, q: "In the Belgian capital Brussels, the French-speaking population is about:", options: ["80 per cent", "40 per cent", "20 per cent", "59 per cent"], answer: 0, why: "In Brussels, 80 per cent are French-speaking and 20 per cent Dutch-speaking." },
  { topic: C1A, q: "The Belgian leaders amended their constitution how many times between 1970 and 1993 to work out a power sharing arrangement?", options: ["Four times", "Once", "Ten times", "Twice"], answer: 0, why: "The arrangements ensured equal representation of Dutch and French speaking ministers." },
  { topic: C1A, q: "The community government in Belgium is elected by:", options: ["People belonging to one language community, wherever they live", "People of one religion", "Only the rich", "The central parliament"], answer: 0, why: "This government handles cultural, educational and language-related issues." },
  { topic: C1A, q: "Which Act of 1956 in Sri Lanka recognised Sinhala as the only official language?", options: ["The Official Language Act", "The Tamil Language Act", "The Buddhist Act", "The Federal Act"], answer: 0, why: "It disregarded Tamil, provoking the Sri Lankan Tamils." },
  { topic: C1A, q: "In Sri Lanka, Sinhala speakers are about:", options: ["74 per cent", "59 per cent", "18 per cent", "50 per cent"], answer: 0, why: "Tamils are about 18 per cent (13 per cent Sri Lankan Tamils and 5 per cent Indian Tamils)." },
  { topic: C1A, q: "What did the Sri Lankan Tamils demand by the 1980s?", options: ["An independent state called Tamil Eelam in the north and east", "A separate religion", "A new constitution", "Union with India"], answer: 0, why: "The demand led to a devastating civil war that ended in 2009." },
  { topic: C1A, q: "The belief that the majority community should be able to rule the country in whichever way it wants is called:", options: ["Majoritarianism", "Federalism", "Secularism", "Communalism"], answer: 0, why: "It disregards the wishes and needs of the minority, as seen in Sri Lanka." },
  { topic: C1A, q: "Which of the following was NOT a preferential policy adopted by the Sri Lankan government?", options: ["Equal status for Tamil as an official language", "Preference to Sinhala applicants for university positions", "Preference to Sinhala applicants for government jobs", "State protection and fostering of Buddhism"], answer: 0, why: "Tamil did NOT get equal status - that was exactly the Tamils' demand." },
  { topic: C1B, q: "Which of these is a PRUDENTIAL reason for power sharing?", options: ["It helps reduce the possibility of conflict between social groups", "It is the very spirit of democracy", "It respects the feelings of all citizens", "It is morally right"], answer: 0, why: "Prudential reasons stress beneficial consequences such as stability and better outcomes." },
  { topic: C1B, q: "Which of these is a MORAL reason for power sharing?", options: ["People have a right to be consulted on how they are governed", "It ensures political stability", "It prevents division of society", "It reduces administrative costs"], answer: 0, why: "Moral reasons emphasise power sharing as the very spirit of democracy." },
  { topic: C1B, q: "A legitimate government is one where:", options: ["Citizens acquire a stake in the system through participation", "One party rules for long", "Only the majority votes", "The army controls power"], answer: 0, why: "People should be consulted and have a share in decision making." },
  { topic: C1B, q: "Tyranny of the majority is best avoided by:", options: ["Power sharing among social groups", "Concentration of power in one organ", "Rule by one community", "Abolishing elections"], answer: 0, why: "Power sharing ensures that minorities also have a say." },
  { topic: C1C, q: "Power shared among the legislature, executive and judiciary is called:", options: ["Horizontal distribution of power", "Vertical distribution of power", "Community government", "Federal division"], answer: 0, why: "Each organ exercises different powers and keeps a check on the others." },
  { topic: C1C, q: "The system of checks and balances is a feature of which form of power sharing?", options: ["Horizontal distribution", "Vertical distribution", "Federal division", "Community government"], answer: 0, why: "No organ can exercise unlimited power; each checks the others." },
  { topic: C1C, q: "Power shared among governments at different levels is called:", options: ["Vertical distribution of power", "Horizontal distribution of power", "Community government", "Coalition government"], answer: 0, why: "The general government for the whole country and the governments at the provincial or regional level." },
  { topic: C1C, q: "In India, the Panchayati Raj is an example of:", options: ["Vertical distribution of power", "Horizontal distribution of power", "Community government", "Judicial review"], answer: 0, why: "Power is shared between the central, state and local levels." },
  { topic: C1C, q: "The Belgian community government is an example of:", options: ["Power sharing among different social groups", "Horizontal distribution", "Vertical distribution", "Power sharing among political parties"], answer: 0, why: "It gives representation to different linguistic communities." },
  { topic: C1C, q: "Which of these is a form of power sharing among political parties, pressure groups and movements?", options: ["Coalition governments", "Community government", "Judicial review", "Zila Parishad"], answer: 0, why: "In a democracy, power is shared among parties and pressure groups that influence decisions." },
  { topic: C1C, q: "Reserved constituencies are an example of power sharing with:", options: ["Socially weaker sections", "The judiciary", "Big business", "The army"], answer: 0, why: "They give representation to communities that would otherwise be left out." },
],

/* ============ CIVICS CHAPTER 2 ============ */
"sst-2-1": [
  { topic: C2A, q: "In a federal system of government there are:", options: ["Two or more levels of government", "Only one level of government", "Only the central government", "Only local bodies"], answer: 0, why: "A unitary system, in contrast, has only one level of government." },
  { topic: C2A, q: "Which of the following is NOT a feature of federalism?", options: ["The central government can unilaterally change the constitution", "Different levels govern the same citizens but have their own jurisdiction", "Courts have the power to interpret the constitution", "Sources of revenue for each level are specified"], answer: 0, why: "Fundamental provisions cannot be changed unilaterally by any one level." },
  { topic: C2A, q: "Coming together federations include:", options: ["USA, Australia and Switzerland", "India, Spain and Belgium", "India and Pakistan", "Sri Lanka and Nepal"], answer: 0, why: "Independent states came together to form a bigger unit, pooling sovereignty." },
  { topic: C2A, q: "India, Spain and Belgium are examples of:", options: ["Holding together federations", "Coming together federations", "Unitary states", "Confederations"], answer: 0, why: "In a holding together federation a large country divides power between the central government and constituent states." },
  { topic: C2A, q: "In India, the states enjoy different powers because:", options: ["States were created on the basis of language and culture, and some have special powers", "All states are exactly equal", "States have no powers", "Only union territories have power"], answer: 0, why: "Some units have special powers - for example Jammu and Kashmir had special status earlier, and states in the north-east have special provisions." },
  { topic: C2A, q: "Which of these countries is NOT a federal country?", options: ["China", "India", "USA", "Belgium"], answer: 0, why: "China is a unitary state; India, USA and Belgium are federal." },
  { topic: C2B, q: "Subjects of national importance such as defence, foreign affairs and currency are in the:", options: ["Union List", "State List", "Concurrent List", "Residuary List"], answer: 0, why: "Only the Union Government can legislate on Union List subjects." },
  { topic: C2B, q: "Police, trade and agriculture are subjects of the:", options: ["State List", "Union List", "Concurrent List", "Residuary List"], answer: 0, why: "State governments alone legislate on subjects in the State List." },
  { topic: C2B, q: "Education, forest, marriage and adoption are subjects of the:", options: ["Concurrent List", "Union List", "State List", "Residuary List"], answer: 0, why: "Both the Union and State governments can legislate, but if their laws conflict, the Union law prevails." },
  { topic: C2B, q: "Subjects like computer software which did not exist when the Constitution was made are called:", options: ["Residuary subjects", "Concurrent subjects", "Union subjects", "State subjects"], answer: 0, why: "The Union Government has the power to legislate on residuary subjects." },
  { topic: C2B, q: "If a Union law and a State law on a Concurrent subject conflict, then:", options: ["The Union law prevails", "The State law prevails", "Both are cancelled", "The Supreme Court writes a new law"], answer: 0, why: "This is laid down in the Constitution." },
  { topic: C2C, q: "How many languages are recognised as Scheduled Languages in the Indian Constitution?", options: ["22", "18", "14", "29"], answer: 0, why: "Besides Hindi there are 21 other languages in the Eighth Schedule." },
  { topic: C2C, q: "In India, the official language is:", options: ["Hindi, with English continuing along with it for official purposes", "Only English", "Only Sanskrit", "Only the state language"], answer: 0, why: "The use of English for official purposes was to stop in 1965, but non-Hindi speaking states demanded its continuation." },
  { topic: C2C, q: "The Indian language policy is a safeguard because:", options: ["Leaders did not impose Hindi on states where people spoke a different language", "It banned regional languages", "It made English the national language", "It abolished state languages"], answer: 0, why: "The flexibility of the language policy helped India avoid the kind of conflict Sri Lanka faced." },
  { topic: C2C, q: "The use of English for official purposes in India was scheduled to stop in which year?", options: ["1965", "1950", "1975", "1991"], answer: 0, why: "Non-Hindi speaking states demanded the continuation of English, and it continued along with Hindi." },
  { topic: C2D, q: "Which of the following has strengthened federalism in India since the 1990s?", options: ["The rise of regional parties and the era of coalition governments", "The banning of regional parties", "The abolition of state elections", "The end of the Planning Commission only"], answer: 0, why: "Coalition governments made the Union government more careful about respecting the powers of the states." },
  { topic: C2D, q: "How has the Constitution safeguarded the powers of the states?", options: ["By clearly dividing legislative powers through the three lists", "By giving all power to the Governor", "By abolishing state assemblies", "By allowing the Centre to dismiss states at will"], answer: 0, why: "Union, State and Concurrent Lists distribute legislative power between the Centre and the states." },
  { topic: C2D, q: "The role of which constitutional authority has been a source of tension between the Centre and the states?", options: ["The Governor", "The Chief Justice", "The Comptroller and Auditor General", "The Election Commissioner"], answer: 0, why: "Governors are appointed by the Central Government and have sometimes taken decisions that are seen as partisan." },
  { topic: C2E, q: "The third tier of Indian government was made mandatory by which amendments?", options: ["73rd and 74th Amendments, 1992", "42nd Amendment, 1976", "First Amendment, 1951", "101st Amendment, 2016"], answer: 0, why: "They made regular elections to local bodies constitutionally mandatory." },
  { topic: C2E, q: "The three tiers of Indian government are:", options: ["Union, State and Local", "Union, District and Village", "Centre, State and National", "Parliament, Assembly and Council"], answer: 0, why: "The local tier includes panchayats and municipalities." },
  { topic: C2E, q: "In the Panchayati Raj system, the elected body at the village level is the:", options: ["Gram Panchayat", "Zilla Parishad", "Panchayat Samiti", "Municipal Corporation"], answer: 0, why: "Gram Panchayat at village level, Panchayat Samiti or Block at block level and Zilla Parishad at district level." },
  { topic: C2E, q: "What share of seats in local bodies is reserved for women?", options: ["One-third", "One-half in all states", "One-tenth", "None"], answer: 0, why: "One-third of seats in panchayats and municipalities are reserved for women." },
  { topic: C2E, q: "Elections to local bodies are conducted by:", options: ["The State Election Commission", "The Election Commission of India", "The Governor's office", "The Zilla Parishad"], answer: 0, why: "An independent State Election Commission conducts panchayat and municipal elections." },
  { topic: C2E, q: "The State Finance Commission was created to:", options: ["Distribute state revenue between the state and local bodies", "Fix prices of crops", "Appoint governors", "Conduct the census"], answer: 0, why: "The 1992 amendments required state governments to share revenue and powers with local bodies." },
],

/* ============ CIVICS CHAPTER 3 ============ */
"sst-2-2": [
  { topic: C3A, q: "The sexual division of labour means that:", options: ["Women do all household work while men work outside the home", "Men and women share all work equally", "Only men work", "Only women work outside"], answer: 0, why: "Yet in reality women do all the household work and also work outside." },
  { topic: C3A, q: "Feminism means:", options: ["Awareness of sexual discrimination and the demand for equality", "Belief in male dominance", "Opposition to women voting", "Preference for male children"], answer: 0, why: "Feminist movements aim at enhancing the political and legal status of women." },
  { topic: C3A, q: "Which of these is an example of gender inequality in India?", options: ["Lower literacy rate among women than men", "Equal wages for equal work", "Equal property rights", "Higher female participation in legislatures"], answer: 0, why: "Parents prefer to spend on sons' education; women also get fewer highly paid jobs." },
  { topic: C3A, q: "Which law provides that equal wages should be paid to equal work?", options: ["Equal Remuneration Act, 1976", "Minimum Wages Act, 1948", "Factories Act, 1948", "Right to Education Act, 2009"], answer: 0, why: "Despite this, women are paid less in almost all work areas." },
  { topic: C3A, q: "The proportion of women in India's legislature has been:", options: ["Very low", "Very high", "Equal to men", "Exactly fifty per cent"], answer: 0, why: "India ranks among the lowest in the world in terms of women's representation in legislatures." },
  { topic: C3A, q: "What share of seats in local bodies is reserved for women in India?", options: ["One-third, and some states have raised it to one-half", "One-tenth", "None", "Two-thirds"], answer: 0, why: "This has resulted in about 10 lakh elected women representatives in rural and urban local bodies." },
  { topic: C3A, q: "Which of these is NOT a cause of gender inequality in India?", options: ["Equal access to education for boys and girls", "Preference for sons", "Undervaluation of women's work", "Lower wages for women"], answer: 0, why: "Equal access would REDUCE inequality - lack of it causes it." },
  { topic: C3A, q: "The feminist movement in India has helped improve the situation by:", options: ["Raising awareness about discrimination and demanding equality", "Banning women from work", "Reducing women's rights", "Stopping girls' education"], answer: 0, why: "It has shaped laws and public attitudes over the decades." },
  { topic: C3B, q: "Communalism means:", options: ["Believing that people who follow the same religion have common political interests", "Believing all religions are equal", "A secular approach to politics", "Separation of religion from politics"], answer: 0, why: "It becomes a problem when religion is seen as the basis of the nation." },
  { topic: C3B, q: "Communal politics takes which of the following forms?", options: ["All of these", "Everyday beliefs and prejudices", "Political mobilisation on religious lines", "Communal violence"], answer: 0, why: "Communalism can take many forms, from prejudice to violence and religion-based political parties." },
  { topic: C3B, q: "Which of the following is a feature of a SECULAR state like India?", options: ["The Constitution does not give special status to any religion", "There is an official state religion", "Religious discrimination is allowed", "Only one religion can be practised"], answer: 0, why: "Secularism is a foundational principle of the Indian Constitution." },
  { topic: C3B, q: "The Indian Constitution permits state intervention in religious matters in order to:", options: ["Ensure equality and end practices like untouchability", "Promote one religion", "Ban all religions", "Control personal beliefs"], answer: 0, why: "The state can intervene to ensure that the freedom of religion is not used to justify discrimination." },
  { topic: C3B, q: "What is the key difference between Indian secularism and that of some Western countries?", options: ["India allows state intervention in religion to ensure equality", "India has an official religion", "India bans all religion in public life", "India has no freedom of religion"], answer: 0, why: "Unlike some Western secularism, the Indian state may intervene in religious matters to protect equality." },
  { topic: C3B, q: "Which of these is an example of communal politics?", options: ["Voting along religious lines", "Voting on the basis of economic policy", "Debating education reform", "Discussing infrastructure"], answer: 0, why: "When political leaders appeal to religious identity to divide the electorate." },
  { topic: C3B, q: "Religious prejudices and stereotypes can lead to:", options: ["Division of society and communal violence", "National unity", "Economic growth", "Better secularism"], answer: 0, why: "Such beliefs often lead to the desire to dominate other communities." },
  { topic: C3C, q: "The caste system in India has traditionally been based on:", options: ["Hereditary occupational division", "Free choice of profession", "Wealth alone", "Education alone"], answer: 0, why: "Caste was based on exclusion and discrimination, and untouchability." },
  { topic: C3C, q: "In Indian elections, no parliamentary constituency has:", options: ["A clear majority of one single caste and community", "Any voters", "More than two candidates", "Any political party"], answer: 0, why: "Therefore every candidate and party needs to win the confidence of more than one caste and community." },
  { topic: C3C, q: "No party wins the votes of all voters of a caste. This shows that:", options: ["Voters have strong attachment to political parties and not only to their caste", "Caste has no role in politics", "Only caste matters", "Elections are meaningless"], answer: 0, why: "Caste is important in politics, but it is not the only factor." },
  { topic: C3C, q: "When political parties talk about caste, they try to:", options: ["Keep the caste composition of the electorate in mind while setting up candidates", "Abolish caste totally", "Ignore caste completely", "Select only upper castes"], answer: 0, why: "They also make promises to particular castes and communities." },
  { topic: C3C, q: "Politics also influences the caste system because:", options: ["Each caste tries to become bigger by incorporating neighbouring castes", "Castes have disappeared", "Castes have become smaller only", "Caste has no role"], answer: 0, why: "Caste groups also enter into coalitions and new kinds of caste groups arise in the political arena." },
  { topic: C3C, q: "Caste politics in India has helped:", options: ["People from lower castes to get better access to decision making", "Only the upper castes", "Nobody at all", "Foreign investors"], answer: 0, why: "But it can also be divisive and lead to tensions." },
  { topic: C3C, q: "Who among the following fought against caste discrimination in India?", options: ["All of these", "Jyotiba Phule", "Mahatma Gandhi", "B.R. Ambedkar"], answer: 0, why: "Social reformers worked to end untouchability and caste discrimination." },
  { topic: C3C, q: "The belief that caste is the sole basis of social community is called:", options: ["Casteism", "Secularism", "Federalism", "Communalism"], answer: 0, why: "Casteism is to caste what communalism is to religion." },
],
};
