/* SST topic-wise MCQ bank — GEOGRAPHY (Contemporary India II).
   Chapters: 1 Resources and Development, 2 Forest and Wildlife Resources,
   3 Water Resources, 4 Agriculture. Topic-tagged per NCERT sub-heading. */
import type { QuizQ } from "./types";

const G1A = "Classification of Resources";
const G1B = "Development of Resources and Resource Planning";
const G1C = "Land Utilisation and Land Use Pattern";
const G1D = "Land Degradation and Conservation";
const G1E = "Soil as a Resource and Classification of Soils";
const G1F = "Soil Erosion and Soil Conservation";

const G2A = "Flora and Fauna in India";
const G2B = "Causes of Depletion of Flora and Fauna";
const G2C = "Conservation of Forest and Wildlife in India";
const G2D = "Types and Distribution of Forest and Wildlife Resources";
const G2E = "Community and Conservation";

const G3A = "Water Scarcity and the Need for Conservation";
const G3B = "Multi-Purpose River Projects and Dams";
const G3C = "Rainwater Harvesting";

const G4A = "Types of Farming";
const G4B = "Cropping Seasons";
const G4C = "Major Food Crops";
const G4D = "Non-Food Crops";
const G4E = "Technological and Institutional Reforms";
const G4F = "Food Security";

export const SST_MCQ_GEOGRAPHY: Record<string, QuizQ[]> = {

/* ============ GEOGRAPHY CHAPTER 1 ============ */
"sst-1-0": [
  { topic: G1A, q: "A resource is anything that can be used to satisfy our needs and is:", options: ["Technologically accessible, economically feasible and culturally acceptable", "Found only deep inside the earth", "Always man-made", "Available only to industry"], answer: 0, why: "All three conditions must be satisfied for something to qualify as a resource." },
  { topic: G1A, q: "On the basis of origin, resources are classified as:", options: ["Biotic and abiotic", "Renewable and non-renewable", "Individual and community", "Potential and developed"], answer: 0, why: "Biotic resources have life; abiotic resources are non-living." },
  { topic: G1A, q: "Iron ore is which type of resource?", options: ["Non-renewable", "Renewable", "Biotic", "Flow"], answer: 0, why: "Minerals take millions of years to form and are exhaustible." },
  { topic: G1A, q: "Under which type of resource can tidal energy be put?", options: ["Replenishable", "Human-made", "Abiotic only", "Non-recyclable"], answer: 0, why: "Tidal energy is replenishable/renewable as tides occur continuously." },
  { topic: G1A, q: "On the basis of ownership, resources are classified as:", options: ["Individual, community, national and international", "Biotic and abiotic", "Renewable and non-renewable", "Potential and stock"], answer: 0, why: "Ownership is the third basis of classification." },
  { topic: G1A, q: "Oceanic resources beyond 200 nautical miles of the Exclusive Economic Zone belong to:", options: ["Open ocean, and no individual country can use them", "The nearest coastal nation", "The United Nations only", "The country with the largest navy"], answer: 0, why: "These are international resources, regulated by international institutions." },
  { topic: G1A, q: "Resources found in a region but not utilised so far are called:", options: ["Potential resources", "Developed resources", "Reserves", "Stock"], answer: 0, why: "Example: solar and wind energy in Rajasthan and Gujarat." },
  { topic: G1A, q: "Materials in the environment which can satisfy human needs but we lack the technology to access are called:", options: ["Stock", "Reserve", "Developed resource", "Potential resource"], answer: 0, why: "Hydrogen in water is the classic example." },
  { topic: G1B, q: "The Rio de Janeiro Earth Summit was held in:", options: ["1992", "1985", "2000", "1972"], answer: 0, why: "In June 1992, leaders signed Agenda 21 on global sustainable development." },
  { topic: G1B, q: "Agenda 21 is related to:", options: ["Combating environmental damage, poverty and disease through global cooperation", "Free trade in minerals", "Building more dams", "Increasing fertiliser use"], answer: 0, why: "One of its major objectives is that every local government should draw its own local Agenda 21." },
  { topic: G1B, q: "The first step of resource planning in India is:", options: ["Identification and inventory of resources", "Conservation of resources", "Exporting surplus resources", "Building industries"], answer: 0, why: "This involves surveying, mapping and qualitative and quantitative estimation." },
  { topic: G1B, q: "Resource planning is essential for which kind of existence?", options: ["Sustainable existence", "Industrial existence", "Urban existence", "Temporary existence"], answer: 0, why: "Sustainable existence is a crucial part of the idea of sustainable development." },
  { topic: G1C, q: "Land left without cultivation for one or less than one agricultural year is called:", options: ["Current fallow", "Culturable waste land", "Barren land", "Net sown area"], answer: 0, why: "If left fallow for more than five agricultural years it is culturable waste land." },
  { topic: G1C, q: "The total geographical area of India is about:", options: ["3.28 million sq km", "32.8 million sq km", "328 thousand sq km", "1.28 million sq km"], answer: 0, why: "Land use data however is available for only about 93 per cent of the total area." },
  { topic: G1C, q: "Land use data is available only for 93 per cent of India's area because:", options: ["Land records are not properly maintained in some states", "The rest is under the sea", "The rest is desert", "It is a secret"], answer: 0, why: "Records are not proper in states like Jammu and Kashmir and Arunachal Pradesh." },
  { topic: G1C, q: "According to the National Forest Policy of 1952, what percentage of the geographical area should be under forest?", options: ["33 per cent", "20 per cent", "50 per cent", "11 per cent"], answer: 0, why: "The present forest area is much lower than this desired 33 per cent." },
  { topic: G1C, q: "The net sown area is more than 80 per cent of the total area in:", options: ["Punjab and Haryana", "Arunachal Pradesh and Mizoram", "Rajasthan and Gujarat", "Kerala and Tamil Nadu"], answer: 0, why: "In Arunachal Pradesh, Mizoram, Manipur and the Andaman and Nicobar Islands it is less than 10 per cent." },
  { topic: G1C, q: "Land put to non-agricultural uses is increasing because of:", options: ["Industrialisation, urbanisation and housing", "Falling population", "Less demand for land", "Decline in industry"], answer: 0, why: "Expanding cities and industries are the main reasons." },
  { topic: G1D, q: "The main cause of land degradation in Punjab is:", options: ["Over-irrigation", "Deforestation", "Overgrazing", "Mining"], answer: 0, why: "Over-irrigation causes waterlogging and increases salinity and alkalinity." },
  { topic: G1D, q: "In which state has mining caused severe land degradation?", options: ["Jharkhand", "Kerala", "Uttarakhand", "Punjab"], answer: 0, why: "Mining in Jharkhand, Chhattisgarh, Madhya Pradesh and Odisha has degraded land." },
  { topic: G1D, q: "In which states is overgrazing responsible for land degradation?", options: ["Madhya Pradesh and Rajasthan", "Punjab and Haryana", "Kerala and Tamil Nadu", "Assam and Bihar"], answer: 0, why: "Overgrazing strips the land of vegetation cover in these states." },
  { topic: G1D, q: "Which of the following does NOT check land degradation?", options: ["Over-irrigation of fields", "Afforestation", "Proper grazing management", "Shelter belts of plants"], answer: 0, why: "Over-irrigation CAUSES waterlogging and salinity." },
  { topic: G1E, q: "Which soil is found predominantly in Maharashtra?", options: ["Black soil", "Alluvial soil", "Arid soil", "Laterite soil"], answer: 0, why: "Black soil, also called regur, is made of lava in the Deccan trap region." },
  { topic: G1E, q: "Black soil is ideal for growing which crop?", options: ["Cotton", "Tea", "Coffee", "Rubber"], answer: 0, why: "It is clayey, moisture retentive and rich in iron, lime, calcium, magnesium and potash." },
  { topic: G1E, q: "Which soil is found in the river deltas of the eastern coast?", options: ["Alluvial soil", "Black soil", "Laterite soil", "Forest soil"], answer: 0, why: "Alluvial soil is widespread in the northern plains and the eastern coastal deltas." },
  { topic: G1E, q: "The older alluvium, found above the flood level, is called:", options: ["Bhangar", "Khadar", "Regur", "Kankar"], answer: 0, why: "Bhangar is old alluvium and contains calcareous deposits called kankar; khadar is new alluvium." },
  { topic: G1E, q: "Laterite soil develops in areas of:", options: ["High temperature and heavy rainfall", "Low temperature and low rainfall", "Desert conditions", "Snow-covered mountains"], answer: 0, why: "Heavy leaching makes it acidic and low in humus; tea, coffee and cashew grow well on it." },
  { topic: G1E, q: "Arid soils are characterised by:", options: ["Lack of humus and moisture, and a kankar layer below", "High humus content", "Very high rainfall", "Heavy leaching"], answer: 0, why: "The kankar layer in the bottom horizons restricts the infiltration of water." },
  { topic: G1F, q: "Terrace cultivation is practised in which state?", options: ["Uttarakhand", "Punjab", "Haryana", "Plains of Uttar Pradesh"], answer: 0, why: "Terrace farming is practised on steep slopes in the Western and Central Himalayas to slow down the flow of water." },
  { topic: G1F, q: "Gully erosion creates which type of landform?", options: ["Badland or ravines", "Deltas", "Dunes", "Flood plains"], answer: 0, why: "Deep gullies due to running water create badland topography, as in the Chambal basin." },
  { topic: G1F, q: "When water flows as a sheet over large areas down a slope and washes away topsoil, it is called:", options: ["Sheet erosion", "Gully erosion", "Wind erosion", "Leaching"], answer: 0, why: "Sheet erosion is a major form of soil erosion on gentle slopes." },
  { topic: G1F, q: "Shelter belts are planted to stabilise which landform?", options: ["Sand dunes in western deserts", "River deltas", "Mountain peaks", "Plateau tops"], answer: 0, why: "In western Rajasthan shelter belts of trees have helped stabilise sand dunes." },
  { topic: G1F, q: "Strip cropping helps in soil conservation by:", options: ["Growing strips of grass between crops to break the wind", "Ploughing across contour lines", "Cutting steps into slopes", "Adding chemical fertilisers"], answer: 0, why: "Contour ploughing follows the contour line; terrace farming cuts steps into slopes." },
],

/* ============ GEOGRAPHY CHAPTER 2 ============ */
"sst-1-1": [
  { topic: G2A, q: "Biodiversity refers to:", options: ["The variety of life forms at ecosystem, species and genetic levels", "Only the number of trees", "Only wild animals", "Only medicinal plants"], answer: 0, why: "Tropical regions cover 10 per cent of the earth's surface and house 90 per cent of species." },
  { topic: G2A, q: "India is one of the world's richest countries in terms of:", options: ["Biological diversity", "Mineral oil reserves", "Desert area", "Population density"], answer: 0, why: "It is a mega-diverse country with a very wide range of flora and fauna." },
  { topic: G2A, q: "The International Union for Conservation of Nature and Natural Resources classifies species into how many categories?", options: ["Six", "Two", "Ten", "Three"], answer: 0, why: "Normal, endangered, vulnerable, rare, endemic and extinct." },
  { topic: G2A, q: "Asiatic cheetah and pink-headed duck are examples of:", options: ["Extinct species", "Endangered species", "Vulnerable species", "Rare species"], answer: 0, why: "These species have been lost from India over the last two centuries." },
  { topic: G2A, q: "Which of these is an ENDANGERED species of India?", options: ["Black buck", "Cattle", "Sal", "Rodents"], answer: 0, why: "Endangered species include black buck, crocodile, Indian wild ass, Indian rhino, lion-tailed macaque and sangai." },
  { topic: G2A, q: "The Gangetic dolphin and Asiatic elephant are classified as:", options: ["Vulnerable species", "Extinct species", "Normal species", "Endemic species"], answer: 0, why: "Vulnerable species are those whose numbers have declined and may become endangered." },
  { topic: G2A, q: "Wild Asiatic buffalo, desert fox and hornbill are examples of:", options: ["Rare species", "Normal species", "Extinct species", "Endemic species"], answer: 0, why: "Rare species have limited population and may soon become vulnerable or endangered." },
  { topic: G2A, q: "Andaman teal, Nicobar pigeon and mithun are examples of:", options: ["Endemic species", "Extinct species", "Normal species", "Vulnerable species"], answer: 0, why: "Endemic species are found exclusively in a particular area and nowhere else." },
  { topic: G2B, q: "Which is the single greatest cause of depletion of flora and fauna in India?", options: ["Agricultural expansion", "Tourism", "Earthquakes", "Volcanic activity"], answer: 0, why: "Large-scale expansion of agriculture, commercial forestry and shifting cultivation are the leading causes." },
  { topic: G2B, q: "The expansion of the railways was a major cause of deforestation during which period?", options: ["Colonial period", "Post-independence period", "Mughal period", "Harappan period"], answer: 0, why: "Colonial forestry, railway expansion, shipbuilding and agricultural expansion cleared large forest areas." },
  { topic: G2B, q: "Why has human activity in forest areas increased in recent decades?", options: ["Growing population and shortage of space", "Falling population", "Decline in farming", "Less demand for wood"], answer: 0, why: "This has also led to growing conflict between humans and animals." },
  { topic: G2B, q: "Which of these has NOT caused depletion of Indian flora and fauna in recent decades?", options: ["Tree plantation programmes", "Large-scale development projects", "Mining activities", "Unequal access and excessive consumption"], answer: 0, why: "Afforestation programmes conserve forests rather than deplete them." },
  { topic: G2C, q: "Project Tiger was launched in:", options: ["1973", "1983", "1963", "1993"], answer: 0, why: "It is one of India's well-publicised wildlife campaigns." },
  { topic: G2C, q: "The Indian Wildlife (Protection) Act was implemented in:", options: ["1972", "1962", "1982", "1991"], answer: 0, why: "It established national parks and sanctuaries and banned hunting of protected species." },
  { topic: G2C, q: "Which of the following was NOT a conservation step taken by the government?", options: ["Encouraging poaching for trade", "Setting up national parks and sanctuaries", "Banning hunting of certain species", "Legal protection of habitats"], answer: 0, why: "Poaching for trade (shah to Europe, tiger skins) is a THREAT, not a conservation step." },
  { topic: G2C, q: "Joint Forest Management (JFM) programme derives its basis from which state?", options: ["Odisha", "Punjab", "Rajasthan", "Kerala"], answer: 0, why: "It was officially started in 1988 in Odisha, and the Government of India adopted it in 1991." },
  { topic: G2D, q: "Which forests are regarded as the most valuable for conservation?", options: ["Reserved forests", "Protected forests", "Unclassed forests", "Private plantations"], answer: 0, why: "They are more than half of the total forest land in India." },
  { topic: G2D, q: "Protected forests constitute approximately what share of India's forest area?", options: ["One-third of the total forest area", "More than half", "One-tenth", "Three-fourths"], answer: 0, why: "They are found in Bihar, Haryana, Punjab, Himachal Pradesh, Odisha and Rajasthan." },
  { topic: G2D, q: "Unclassed forests include:", options: ["Forests and wastelands belonging to government and private individuals and communities", "Only reserve forests", "Only sanctuaries", "Only national parks"], answer: 0, why: "All North-Eastern states and parts of Gujarat have a very high percentage of unclassed forests." },
  { topic: G2D, q: "Which region of India has a very high percentage of unclassed forests?", options: ["North-Eastern states", "Punjab and Haryana", "Western Rajasthan", "Gujarat plains only"], answer: 0, why: "Local communities in the North-East have long traditions of forest protection." },
  { topic: G2E, q: "In 1731, which woman sacrificed her life for the protection of khejri trees?", options: ["Amrita Devi Bishnoi", "Sunderlal Bahuguna", "Medha Patkar", "Anusuya Devi"], answer: 0, why: "The Bishnoi community of Rajasthan sacrificed everything to protect the trees." },
  { topic: G2E, q: "The Chipko movement was a forest conservation movement launched in:", options: ["The Himalayas", "The Western Ghats", "The Aravallis", "The Sundarbans"], answer: 0, why: "It spread quickly among the hill communities, especially women." },
  { topic: G2E, q: "The Beej Bachao Andolan has been significant in:", options: ["Tehri, Uttarakhand", "Alwar, Rajasthan", "Khonoma, Nagaland", "Gendathur, Karnataka"], answer: 0, why: "It focused on saving seeds and promoting diversity over monocultures." },
  { topic: G2E, q: "The villagers of Alwar district in Rajasthan protected which trees?", options: ["Khejri", "Teak", "Sal", "Sandalwood"], answer: 0, why: "The Bishnoi community has protected the khejri trees for centuries." },
  { topic: G2E, q: "Khonoma Nature Conservation and Tragopan Sanctuary is located in:", options: ["Nagaland", "Mizoram", "Manipur", "Assam"], answer: 0, why: "It was initiated by the villagers of Khonoma to conserve the forest and wildlife." },
],

/* ============ GEOGRAPHY CHAPTER 3 ============ */
"sst-1-2": [
  { topic: G3A, q: "Water scarcity may be a result of:", options: ["Large and growing population, and unequal access to water", "Only low rainfall", "Only drought", "Only floods"], answer: 0, why: "Water scarcity is not just about rainfall - it is also about access, quality and demand." },
  { topic: G3A, q: "To meet the demands of a growing population, water is needed mainly for:", options: ["Irrigation, domestic use and industry", "Recreation only", "Cement production only", "Export only"], answer: 0, why: "Greater food production requires more irrigation, and industries consume huge amounts of water." },
  { topic: G3A, q: "The growing demand for water is met by:", options: ["Using more from rivers and groundwater, and by saving and reusing", "Only by building new towns", "Exporting water", "Reducing population by force"], answer: 0, why: "Over-extraction of groundwater is a major problem in many parts of India." },
  { topic: G3A, q: "Modern industrial methods create water pollution by:", options: ["Discharging untreated effluents into water bodies", "Using less water", "Planting trees", "Harvesting rain"], answer: 0, why: "Industrial effluents, chemicals and fertilisers pollute India's rivers." },
  { topic: G3A, q: "In many parts of India, women have to walk long distances to fetch water, showing that:", options: ["Access to clean water is unequal", "Water is free everywhere", "Rainfall is increasing", "Dams are unnecessary"], answer: 0, why: "Unequal access is a key dimension of water scarcity." },
  { topic: G3B, q: "Dams are built on rivers for:", options: ["Irrigation, electricity, water supply and flood control", "Only for fishing", "Only for transport", "Only for tourism"], answer: 0, why: "Dams are called multi-purpose projects because they serve several purposes at once." },
  { topic: G3B, q: "Jawaharlal Nehru called dams the:", options: ["Temples of modern India", "Palaces of modern India", "Heart of modern India", "Roots of modern India"], answer: 0, why: "He saw them as the driving force of development for agriculture and industry." },
  { topic: G3B, q: "Which of the following is a multi-purpose river project of India?", options: ["Bhakra Nangal", "Suez Canal", "Panama Canal", "Hoover Dam"], answer: 0, why: "Bhakra Nangal on the Sutlej, along with Damodar Valley, Hirakud, Nagarjuna Sagar and Tehri." },
  { topic: G3B, q: "The Damodar Valley Corporation is modelled on the lines of:", options: ["The Tennessee Valley Authority of the USA", "The Rhine Commission", "The Aswan Dam", "The Bay of Fundy project"], answer: 0, why: "The DVC is one of the first major multi-purpose projects of independent India." },
  { topic: G3B, q: "Damming a river affects aquatic life because it:", options: ["Blocks the natural flow and traps sediment", "Increases river flow", "Adds oxygen to water", "Cleanses the water"], answer: 0, why: "Dams fragment rivers so aquatic fauna cannot migrate or spawn properly." },
  { topic: G3B, q: "Submergence caused by dams leads to:", options: ["Displacement of local communities and loss of livelihood", "Higher forest cover", "Better fishing", "No change at all"], answer: 0, why: "Large-scale displacement of peasants and tribal communities is the biggest social cost of dams." },
  { topic: G3B, q: "Which movement opposed the construction of a large dam on the Narmada?", options: ["Narmada Bachao Andolan", "Chipko movement", "Beej Bachao Andolan", "Narmada Water Harvesting Board"], answer: 0, why: "It mobilised tribal people, farmers and environmental groups." },
  { topic: G3B, q: "Excessive irrigation from canal water leads to:", options: ["Soil salinity and waterlogging", "Higher fertility always", "Lower salinity", "Increased forest cover"], answer: 0, why: "Irrigation has changed cropping patterns and caused salinity, alkalinity and waterlogging." },
  { topic: G3B, q: "Which of the following is a major purpose served by multi-purpose projects?", options: ["Hydroelectric power generation", "Increasing desert area", "Reducing rainfall", "Decreasing forest cover"], answer: 0, why: "Other purposes are irrigation, flood control, drinking water and inland navigation." },
  { topic: G3C, q: "Tankas in Rajasthan are:", options: ["Underground tanks built inside the main house or courtyard", "Above-ground tube wells", "Canal systems", "Lakes built by the government"], answer: 0, why: "They are part of the rooftop rainwater harvesting system to store drinking water." },
  { topic: G3C, q: "Khadins and johads are traditional rainwater storage structures of:", options: ["Rajasthan", "Meghalaya", "Kerala", "Tamil Nadu"], answer: 0, why: "They are found in Rajasthan and are still in use in many areas." },
  { topic: G3C, q: "The bamboo drip irrigation system is a traditional practice of:", options: ["Meghalaya", "Rajasthan", "Punjab", "Bihar"], answer: 0, why: "In Meghalaya, bamboo drip irrigation is a centuries-old system." },
  { topic: G3C, q: "Kuls or guls are traditional water conservation structures found in:", options: ["Western Himalayas", "Eastern Ghats", "Thar desert", "Sundarbans"], answer: 0, why: "In the Western Himalayas, diversion channels called kuls or guls are used for agriculture." },
  { topic: G3C, q: "Inundation channels are used for irrigation in:", options: ["The flood plains of Bengal", "The deserts of Rajasthan", "The hills of Meghalaya", "The Deccan plateau"], answer: 0, why: "In the flood plains of Bengal, people developed inundation channels to irrigate their fields." },
  { topic: G3C, q: "Rooftop rainwater harvesting is widely practised in which state?", options: ["Shillong, Meghalaya", "Jaisalmer, Rajasthan", "Ludhiana, Punjab", "Agra, Uttar Pradesh"], answer: 0, why: "Shillong has moved towards a total rooftop system with the help of the government and social organisations." },
  { topic: G3C, q: "Gendathur village, known for rooftop rainwater harvesting, is in:", options: ["Karnataka", "Kerala", "Tamil Nadu", "Maharashtra"], answer: 0, why: "It is in Mysuru district and has earned the reputation of being a rich village with rainwater harvesting." },
  { topic: G3C, q: "Which state was the first to make rooftop rainwater harvesting compulsory for all houses?", options: ["Tamil Nadu", "Rajasthan", "Punjab", "Gujarat"], answer: 0, why: "Tamil Nadu made it compulsory for all houses across the state." },
  { topic: G3C, q: "The main objective of rainwater harvesting is to:", options: ["Collect and store water for future use and recharge groundwater", "Increase floods", "Increase evaporation", "Waste surface water"], answer: 0, why: "It reduces dependence on groundwater and conserves surface water." },
],

/* ============ GEOGRAPHY CHAPTER 4 ============ */
"sst-1-3": [
  { topic: G4A, q: "Slash and burn agriculture is known as Jhumming in:", options: ["North-eastern states of India", "Kerala", "Punjab", "Gujarat"], answer: 0, why: "Also called Milpa in Mexico, Roca in Brazil and Ladang in Malaysia." },
  { topic: G4A, q: "Primitive subsistence farming depends on:", options: ["Monsoon, natural soil fertility and other environmental conditions", "Heavy machines and fertilisers", "Irrigation canals", "Modern genetically modified seeds"], answer: 0, why: "It uses primitive tools and family or community labour with low productivity." },
  { topic: G4A, q: "Intensive subsistence farming is characterised by:", options: ["Small holdings and high use of inputs with intensive labour", "Very large farms", "No use of fertilisers", "Only grazing of animals"], answer: 0, why: "It is practised in areas of high population pressure on land." },
  { topic: G4A, q: "Commercial grain farming is practised mainly to:", options: ["Sell grain in the market", "Feed the farmer's family only", "Grow fodder for horses", "Produce rubber"], answer: 0, why: "It is found in temperate grasslands of North America, Europe and Asia." },
  { topic: G4A, q: "Plantation is a type of farming in which:", options: ["A single crop is grown on a large area with capital and migrant labour", "Many crops are grown on a small plot", "Only vegetables are grown", "Only fruit trees are grown in kitchen gardens"], answer: 0, why: "Tea, coffee, banana, sugarcane and rubber are grown this way in India." },
  { topic: G4A, q: "Mixed farming refers to:", options: ["Growing food and fodder crops along with rearing of livestock", "Growing one crop only", "Mixing chemical fertilisers", "Shifting cultivation"], answer: 0, why: "It is practised in Europe, North America, Australia and New Zealand." },
  { topic: G4B, q: "Rabi crops are sown in:", options: ["Winter", "Monsoon", "Summer", "Autumn"], answer: 0, why: "They are sown in winter from October to December and harvested in summer." },
  { topic: G4B, q: "Which of these is a Rabi crop?", options: ["Wheat", "Paddy", "Jute", "Cotton"], answer: 0, why: "Rabi crops include wheat, barley, peas, gram and mustard." },
  { topic: G4B, q: "Kharif crops are sown:", options: ["With the onset of the monsoon", "In winter", "In summer only", "After harvesting wheat"], answer: 0, why: "They are harvested in September and October; examples are paddy, maize, jowar, bajra and cotton." },
  { topic: G4B, q: "Watermelon, muskmelon and cucumber are grown in which season?", options: ["Zaid", "Kharif", "Rabi", "Winter"], answer: 0, why: "Zaid is a short summer season between Rabi and Kharif." },
  { topic: G4C, q: "Rice requires which conditions to grow?", options: ["High temperature above 25 C, high humidity and rainfall above 100 cm", "Cool temperature and low rainfall", "Very low rainfall", "Frost and snow"], answer: 0, why: "In areas of less rainfall, it grows with the help of irrigation." },
  { topic: G4C, q: "Wheat requires how much rainfall?", options: ["50 to 75 cm", "Above 200 cm", "Below 20 cm", "Above 300 cm"], answer: 0, why: "It is the main food crop of the north and north-western parts of India." },
  { topic: G4C, q: "Which are the two main wheat growing zones of India?", options: ["Ganga-Satluj plains and the black soil region of the Deccan", "Kerala and Tamil Nadu", "Assam and Meghalaya", "Rajasthan and Gujarat"], answer: 0, why: "It is a Rabi crop that needs a cool growing season and bright sunshine at ripening." },
  { topic: G4C, q: "Jowar, bajra and ragi are together known as:", options: ["Millets", "Pulses", "Oilseeds", "Fibre crops"], answer: 0, why: "They are coarse grains with high nutritional value." },
  { topic: G4C, q: "Which state is the largest producer of bajra?", options: ["Rajasthan", "Maharashtra", "Karnataka", "Punjab"], answer: 0, why: "Rajasthan is the largest producer of bajra; Maharashtra leads in jowar and Karnataka in ragi." },
  { topic: G4C, q: "Which millet is rich in iron, calcium and roughage?", options: ["Ragi", "Jowar", "Bajra", "Maize"], answer: 0, why: "Ragi is very nutritious and is a major crop of Karnataka." },
  { topic: G4C, q: "Pulses help in restoring soil fertility because they:", options: ["Fix nitrogen from the air", "Add potassium only", "Loosen the soil", "Attract earthworms only"], answer: 0, why: "Being leguminous, they fix nitrogen, so they are grown in rotation with other crops." },
  { topic: G4C, q: "India is the largest producer as well as consumer of:", options: ["Pulses", "Rice", "Wheat", "Rubber"], answer: 0, why: "Pulses are the major source of protein in a vegetarian diet." },
  { topic: G4C, q: "Maize is which type of crop?", options: ["Kharif", "Rabi", "Zaid", "Plantation"], answer: 0, why: "It is used both as food and fodder and grows well on old alluvial soil." },
  { topic: G4D, q: "India is the largest producer of which crop?", options: ["Sugarcane", "Coffee", "Rubber", "Tea"], answer: 0, why: "India is the largest producer of sugarcane; it is a tropical as well as sub-tropical crop." },
  { topic: G4D, q: "Cotton grows best on which soil?", options: ["Black soil of the Deccan plateau", "Laterite soil", "Arid soil", "Forest soil"], answer: 0, why: "Cotton needs 210 frost-free days, bright sunshine and 50 to 75 cm of rainfall." },
  { topic: G4D, q: "Jute is known as:", options: ["The golden fibre", "The white fibre", "The king of fibres", "The desert fibre"], answer: 0, why: "It grows well on well-drained fertile soils in flood plains, mainly in West Bengal." },
  { topic: G4D, q: "Coffee cultivation in India began on which hills?", options: ["Baba Budan Hills", "Nilgiri Hills", "Aravalli Hills", "Shivalik Hills"], answer: 0, why: "The Arabica variety brought from Yemen was initially introduced on the Baba Budan Hills." },
  { topic: G4D, q: "Rubber is which type of crop?", options: ["Equatorial crop", "Desert crop", "Mountain crop", "Rabi crop"], answer: 0, why: "It needs moist and humid climate with rainfall of more than 200 cm and temperature above 25 C." },
  { topic: G4D, q: "Tea cultivation requires:", options: ["Deep, fertile, well-drained soil rich in humus and organic matter", "Sandy desert soil", "Saline soil", "Waterlogged clay soil"], answer: 0, why: "It needs a warm, moist, frost-free climate and is labour intensive." },
  { topic: G4E, q: "The Green Revolution in India was associated with:", options: ["A substantial increase in the production of food grains", "Increase in milk production", "Increase in fish production", "Increase in oil production"], answer: 0, why: "It came in the 1960s and 1970s and was based on the use of HYV seeds, fertilisers and irrigation." },
  { topic: G4E, q: "The White Revolution is related to:", options: ["Milk production", "Wheat production", "Cotton production", "Rubber production"], answer: 0, why: "It is also known as Operation Flood." },
  { topic: G4E, q: "Kisan Credit Card (KCC) was introduced to help farmers with:", options: ["Timely credit for buying agricultural inputs", "Free seeds forever", "Insurance against floods only", "Land ownership"], answer: 0, why: "Along with PAIS (Personal Accident Insurance Scheme) it is a major institutional reform." },
  { topic: G4E, q: "The Bhoodan-Gramdan movement was led by:", options: ["Vinoba Bhave", "Jawaharlal Nehru", "Baba Ramchandra", "M.S. Swaminathan"], answer: 0, why: "Bhoodan means land gift; the movement is also known as the Blood-less Revolution." },
  { topic: G4E, q: "The main aim of land reform in India was:", options: ["Consolidation of holdings and abolition of zamindari", "Increasing the number of zamindars", "Reducing irrigation", "Increasing fragmentation of land"], answer: 0, why: "Land reform was the main focus of the First Five Year Plan." },
  { topic: G4F, q: "Food security depends on:", options: ["A buffer stock of food grains and the public distribution system", "Only good rainfall", "Only imports", "Only exports"], answer: 0, why: "Buffer stocks and the PDS ensure food availability for the poor." },
  { topic: G4F, q: "Agriculture's share in India's GDP has:", options: ["Declined, though it still employs a very large workforce", "Increased continuously", "Remained exactly the same", "Become zero"], answer: 0, why: "Agriculture is still the backbone of the economy as the largest source of livelihood." },
  { topic: G4F, q: "Agriculture is called the backbone of the Indian economy because it:", options: ["Provides employment to a very large section of the population", "Produces only for export", "Uses no water", "Employs only machines"], answer: 0, why: "Two-thirds of India's population is still engaged in agricultural activities." },
],
};
