/* SST topic-wise MCQ bank — ECONOMICS (Understanding Economic Development).
   Chapters: 1 Development, 2 Sectors of the Indian Economy.
   Topic-tagged per NCERT sub-heading. */
import type { QuizQ } from "./types";

const E1A = "Different People, Different Goals";
const E1B = "Income and Other Goals";
const E1C = "National Development";
const E1D = "Comparing Countries: Income and Other Criteria";
const E1E = "Public Facilities";
const E1F = "Sustainability of Development";

const E2A = "Sectors of Economic Activities";
const E2B = "Comparing the Three Sectors";
const E2C = "Primary, Secondary and Tertiary Sectors in India";
const E2D = "Organised and Unorganised Sectors";
const E2E = "Public and Private Sectors";

export const SST_MCQ_ECONOMICS: Record<string, QuizQ[]> = {

/* ============ ECONOMICS CHAPTER 1 ============ */
"sst-3-0": [
  { topic: E1A, q: "Different persons can have different developmental goals because:", options: ["Their situations and needs differ", "Development means the same to everyone", "Everyone wants the same thing", "Goals never change"], answer: 0, why: "A landless labourer and a prosperous farmer will have very different goals." },
  { topic: E1A, q: "For a landless rural labourer, development would mean:", options: ["More days of work and better wages", "More factories in the city", "Higher land prices", "More imported goods"], answer: 0, why: "Along with quality education for children and better healthcare." },
  { topic: E1A, q: "For a girl from a rich urban family, development may mean:", options: ["Getting as much freedom as her brother", "More agricultural land", "Higher crop prices", "Working as a labourer"], answer: 0, why: "She may want the freedom to decide what she wants to do in life." },
  { topic: E1A, q: "What may be development for one person can be:", options: ["Destructive for another", "Good for everybody always", "Neutral for everyone", "The same for all"], answer: 0, why: "A dam may give electricity to industry but displace villagers." },
  { topic: E1A, q: "Besides income, people also seek which other goals?", options: ["Equal treatment, freedom, security and respect from others", "Only money", "Only property", "Only imported goods"], answer: 0, why: "These are non-material goals that matter for a good life." },
  { topic: E1B, q: "Which of these is a non-material goal of development?", options: ["Freedom and security", "Higher income", "More savings", "A bigger house"], answer: 0, why: "People look for equal treatment and respect along with income." },
  { topic: E1B, q: "For development goals, which of the following is true?", options: ["Material and non-material goals can both matter", "Only money matters", "Only respect matters", "Nothing matters"], answer: 0, why: "Income is one important goal, but it is not the only one." },
  { topic: E1C, q: "National development refers to:", options: ["The ability of a nation to improve the lives of all its citizens", "Only the growth of big cities", "Only industrial growth", "Only higher exports"], answer: 0, why: "It requires a fair and just path for everyone, not just a section of people." },
  { topic: E1C, q: "Different persons may have different notions of a country's development because:", options: ["They belong to different regions and have different priorities", "Everyone has identical priorities", "Development means the same everywhere", "It is decided only by the government"], answer: 0, why: "Development for a farmer differs from that for an industrialist." },
  { topic: E1D, q: "Per capita income is calculated as:", options: ["Total income of the country divided by total population", "Total income multiplied by population", "Total exports minus imports", "Total savings of the country"], answer: 0, why: "It is also called average income." },
  { topic: E1D, q: "Which organisation publishes the World Development Report?", options: ["The World Bank", "The United Nations only", "The Reserve Bank of India", "The WHO"], answer: 0, why: "The World Bank classifies countries based on per capita income." },
  { topic: E1D, q: "Countries with higher per capita income are generally considered:", options: ["More developed than those with less income", "Less developed", "Equal to all others", "Free from all problems"], answer: 0, why: "Income is the most common criterion used to compare countries." },
  { topic: E1D, q: "India falls in which category of countries according to the World Bank?", options: ["Low middle income", "High income", "Low income", "Very high income"], answer: 0, why: "India is a low middle income country in World Bank classification." },
  { topic: E1D, q: "Which of these is NOT a criterion used in the Human Development Report?", options: ["Amount of gold reserves", "Life expectancy", "Education levels", "Per capita income"], answer: 0, why: "The UNDP's HDI uses health, education and income." },
  { topic: E1D, q: "Average income is a useful measure but it:", options: ["Hides the distribution of income among people", "Shows exactly how income is shared", "Shows only the income of the rich", "Is always accurate"], answer: 0, why: "Two countries may have the same average income but very different distribution." },
  { topic: E1D, q: "Infant Mortality Rate refers to the number of children per 1000 that die:", options: ["Before the age of one year", "Before the age of five years", "Before the age of ten", "Before birth"], answer: 0, why: "It is an important indicator of health facilities." },
  { topic: E1D, q: "Literacy rate measures the proportion of the literate population in the age group:", options: ["7 years and above", "5 years and above", "10 years and above", "15 years and above"], answer: 0, why: "It is a key educational indicator." },
  { topic: E1D, q: "Net Attendance Ratio refers to the percentage of children of which age group attending school?", options: ["6 to 10 years", "3 to 5 years", "10 to 15 years", "15 to 18 years"], answer: 0, why: "It measures participation in school education." },
  { topic: E1D, q: "Body Mass Index (BMI) is used to determine whether:", options: ["Adults are undernourished", "Children can read", "People have jobs", "Houses are pucca"], answer: 0, why: "If an adult's BMI is less than 18.5, the person is considered undernourished." },
  { topic: E1E, q: "Why is income alone not an adequate indicator of development?", options: ["Because money cannot buy services that are not available", "Because money has no value", "Because everyone is rich", "Because income never changes"], answer: 0, why: "If there is no school or hospital nearby, income cannot buy that facility." },
  { topic: E1E, q: "Public facilities provided by the government include:", options: ["Schools, healthcare, transport and security", "Only mobile phones", "Only private cars", "Only jewellery"], answer: 0, why: "Collective provision of such services is essential for a good life." },
  { topic: E1E, q: "Which Indian state has a lower per capita income than Haryana but better human development indicators?", options: ["Kerala", "Punjab", "Maharashtra", "Gujarat"], answer: 0, why: "Kerala has better health and educational facilities and a lower infant mortality rate." },
  { topic: E1E, q: "Kerala's success in human development is mainly because of:", options: ["Better health and educational facilities provided by the government", "Higher per capita income than all states", "More factories", "More mineral resources"], answer: 0, why: "It shows that public facilities matter as much as income." },
  { topic: E1F, q: "Which of these is an example of overuse of an important natural resource in India?", options: ["Excessive use of groundwater", "Planting trees", "Rainwater harvesting", "Building check dams"], answer: 0, why: "Groundwater over-draught is common in Punjab, western Uttar Pradesh and parts of central and south India." },
  { topic: E1F, q: "Crude oil reserves are an example of:", options: ["A non-renewable resource that will eventually run out", "A renewable resource", "An unlimited resource", "A man-made resource"], answer: 0, why: "Its reserves are limited and will last only about 50 years at current rates of use." },
  { topic: E1F, q: "Sustainable development means:", options: ["Development without damaging the environment and without compromising future generations", "Maximum use of all resources now", "Stopping all development", "Only industrial growth"], answer: 0, why: "It means we should use resources carefully and not exhaust them." },
  { topic: E1F, q: "Which practice shows concern for sustainability?", options: ["Using renewable resources like solar energy", "Cutting forests for farmland", "Overusing groundwater", "Burning more coal"], answer: 0, why: "Sustainable use means not exhausting non-renewable resources." },
],

/* ============ ECONOMICS CHAPTER 2 ============ */
"sst-3-1": [
  { topic: E2A, q: "Which sector produces a good by exploiting natural resources?", options: ["Primary sector", "Secondary sector", "Tertiary sector", "Public sector"], answer: 0, why: "It is also called the agriculture and related sector." },
  { topic: E2A, q: "Manufacturing that changes natural products into other forms belongs to the:", options: ["Secondary sector", "Primary sector", "Tertiary sector", "Unorganised sector"], answer: 0, why: "For example, making cloth from cotton - it is the industrial sector." },
  { topic: E2A, q: "Which sector provides services that support the primary and secondary sectors?", options: ["Tertiary sector", "Primary sector", "Secondary sector", "Private sector"], answer: 0, why: "Transport, storage, communication, banking and trade - the service sector." },
  { topic: E2A, q: "Banking, transport and insurance belong to which sector?", options: ["Tertiary sector", "Primary sector", "Secondary sector", "Manufacturing sector"], answer: 0, why: "These activities generate services rather than goods." },
  { topic: E2A, q: "Dairy, fishing and forestry belong to which sector?", options: ["Primary sector", "Secondary sector", "Tertiary sector", "Service sector"], answer: 0, why: "They are based directly on natural resources." },
  { topic: E2A, q: "A sugar mill that makes sugar from sugarcane is part of the:", options: ["Secondary sector", "Primary sector", "Tertiary sector", "Public sector"], answer: 0, why: "It manufactures a new product from a natural one." },
  { topic: E2B, q: "GDP stands for:", options: ["Gross Domestic Product", "General Domestic Product", "Gross Development Product", "Great Domestic Production"], answer: 0, why: "It is the value of all final goods and services produced within a country in a year." },
  { topic: E2B, q: "Why are only final goods and services counted in GDP?", options: ["To avoid double counting of intermediate goods", "Because final goods are cheaper", "Because intermediate goods are not sold", "Because final goods are taxed"], answer: 0, why: "The value of intermediate goods is already included in the value of final goods." },
  { topic: E2B, q: "Who estimates GDP in India?", options: ["A central government ministry with the help of various government departments", "Only the Reserve Bank of India", "Private companies only", "The World Bank"], answer: 0, why: "It collects information relating to the total volume of goods and services." },
  { topic: E2B, q: "Which sector contributes the largest share to India's GDP today?", options: ["Tertiary sector", "Primary sector", "Secondary sector", "Agricultural sector"], answer: 0, why: "The tertiary sector has emerged as the largest producing sector in India." },
  { topic: E2B, q: "In developed countries, which sector has become the most important in terms of total production?", options: ["Tertiary sector", "Primary sector", "Secondary sector", "None"], answer: 0, why: "There has been a shift from primary to secondary and then to tertiary over 100 years." },
  { topic: E2C, q: "Why did the tertiary sector become important in India?", options: ["All of these", "Basic services like hospitals and schools became essential", "Development of agriculture and industry created demand for services", "Rising income led people to demand more services"], answer: 0, why: "New ICT-based services like call centres and software also became important." },
  { topic: E2C, q: "Which sector employs the largest number of people in India?", options: ["Primary sector", "Secondary sector", "Tertiary sector", "Public sector"], answer: 0, why: "More than half the workers are in the primary sector, mainly agriculture." },
  { topic: E2C, q: "Despite employing the largest number of people, agriculture produces:", options: ["Only a small share of GDP", "Most of the GDP", "Half of the GDP", "All of the GDP"], answer: 0, why: "This shows that workers in agriculture are underemployed." },
  { topic: E2C, q: "Underemployment is also known as:", options: ["Disguised unemployment", "Full employment", "Over employment", "Seasonal employment"], answer: 0, why: "People appear to be working but all of them work less than their potential." },
  { topic: E2C, q: "If a farmer's family of five works on a plot that needs only three people, the extra two are:", options: ["Underemployed", "Unemployed but seeking work", "Employed full time", "Employed in the tertiary sector"], answer: 0, why: "This is disguised unemployment - removing them would not reduce output." },
  { topic: E2C, q: "The Mahatma Gandhi National Rural Employment Guarantee Act was passed in:", options: ["2005", "1995", "2010", "2018"], answer: 0, why: "It guarantees 100 days of employment in a year." },
  { topic: E2C, q: "Under MGNREGA 2005, how many days of employment are guaranteed?", options: ["100 days", "50 days", "365 days", "200 days"], answer: 0, why: "If the government fails to provide employment, it must give unemployment allowances." },
  { topic: E2C, q: "Which of these can create more employment in rural India?", options: ["All of these", "Building dams and irrigation canals", "Promoting tourism", "Starting industries in rural areas"], answer: 0, why: "Developing infrastructure like schools and hospitals also creates jobs." },
  { topic: E2D, q: "Workers in the organised sector:", options: ["Get fixed working hours, paid holidays and benefits like provident fund", "Have no job security", "Are paid daily without benefits", "Work without any rules"], answer: 0, why: "They are registered and follow the rules of the Factories Act and Minimum Wages Act." },
  { topic: E2D, q: "Which Act provides for gratuity to workers?", options: ["Payment of Gratuity Act", "Factories Act", "Minimum Wages Act", "Equal Remuneration Act"], answer: 0, why: "Gratuity is a retirement benefit for organised sector workers." },
  { topic: E2D, q: "Workers in the unorganised sector:", options: ["Have low-paid, often irregular jobs without benefits", "Get pension and provident fund", "Get paid holidays", "Have total job security"], answer: 0, why: "Rules exist but are not followed in this sector." },
  { topic: E2D, q: "Which of these is an example of unorganised sector work?", options: ["A street vendor", "A bank officer", "A teacher in a government school", "An engineer in a registered factory"], answer: 0, why: "Small and scattered units largely outside the control of the government." },
  { topic: E2D, q: "In India, the majority of the workforce is employed in the:", options: ["Unorganised sector", "Organised sector", "Public sector only", "Government"], answer: 0, why: "They need protection and support for their economic and social development." },
  { topic: E2E, q: "In the public sector, the government:", options: ["Owns most of the assets and provides all the services", "Has no role", "Only collects taxes", "Only regulates"], answer: 0, why: "The purpose is not profit but public welfare." },
  { topic: E2E, q: "In the private sector, ownership of assets and delivery of services is in the hands of:", options: ["Private individuals or companies", "The government", "Village panchayats", "Cooperative societies only"], answer: 0, why: "The main motive of the private sector is profit." },
  { topic: E2E, q: "The public sector is needed to provide services like roads and bridges because:", options: ["The private sector is not willing to invest in them", "They are always profitable", "They are illegal for private firms", "They need no money"], answer: 0, why: "Construction of roads, bridges, railways and power plants needs huge investment with uncertain returns." },
  { topic: E2E, q: "Why must the government take responsibility for basic services like education and health?", options: ["Because they must be available to everyone, including the poor", "Because they are unprofitable and useless", "Because private firms are banned", "Because only the rich need them"], answer: 0, why: "The government must ensure that the benefits of development reach all sections." },
  { topic: E2E, q: "Sectors are classified into public and private on the basis of:", options: ["Ownership", "Working conditions", "Capital investment", "Location"], answer: 0, why: "Who owns the assets and delivers the service decides the classification." },
  { topic: E2E, q: "Which of the following is an example of a public sector enterprise in India?", options: ["Steel Authority of India Limited (SAIL)", "TISCO", "A private five-star hotel", "A privately owned call centre"], answer: 0, why: "SAIL is owned by the government. TISCO, on the other hand, was the first PRIVATE iron and steel company of India." },
  { topic: E2E, q: "The main motive of the private sector is:", options: ["Profit", "Public welfare", "Charity", "Free service to all"], answer: 0, why: "The public sector, by contrast, works for public welfare rather than profit." },
],
};
