/* SST topic-wise MCQ bank — HISTORY (India and the Contemporary World II).
   Chapters: 1 (Rise of Nationalism in Europe), 2 (Nationalism in India).
   Every question carries a `topic` = the NCERT sub-heading it is set from, so a
   student sees exactly which topic the question can be asked from.
   Accuracy notes: dates, names and figures are from the NCERT text. */
import type { QuizQ } from "./types";

const T1 = "French Revolution and the Idea of the Nation";
const T2 = "The Making of Nationalism in Europe";
const T3 = "The Age of Revolutions: 1830-1848";
const T4 = "The Making of Germany and Italy";
const T5 = "Visualising the Nation";
const T6 = "Nationalism and Imperialism";

const I1 = "First World War, Khilafat and Non-Cooperation";
const I2 = "Differing Strands within the Movement";
const I3 = "Towards Civil Disobedience";
const I4 = "The Sense of Collective Belonging";

export const SST_MCQ_HISTORY: Record<string, QuizQ[]> = {

/* ================= HISTORY CHAPTER 1 ================= */
"sst-0-0": [
  { topic: T1, q: "The first clear expression of nationalism came with which event?", options: ["The French Revolution of 1789", "The Congress of Vienna of 1815", "The Greek revolt of 1821", "The unification of Italy in 1861"], answer: 0, why: "NCERT opens the chapter with 1789 France as the first clear expression of nationalism." },
  { topic: T1, q: "In revolutionary France, the idea of la patrie and le citoyen meant:", options: ["The fatherland and the citizen", "The king and the subject", "The church and the state", "The army and the general"], answer: 0, why: "la patrie = the fatherland, le citoyen = the citizen, giving the united community equal rights under a constitution." },
  { topic: T1, q: "Which of these steps did French revolutionaries NOT take to create a collective identity?", options: ["Abolishing internal customs duties", "Adopting a uniform system of weights and measures", "Encouraging regional dialects", "Making French the common language of the nation"], answer: 2, why: "Regional dialects were DISCOURAGED, not encouraged. They promoted French as the common language." },
  { topic: T1, q: "The Estates General was renamed as:", options: ["The National Assembly", "The Directory", "The Convention of Paris", "The Consulate"], answer: 0, why: "In 1789 the Estates General was renamed the National Assembly." },
  { topic: T1, q: "The Civil Code of 1804 is better known as:", options: ["The Napoleonic Code", "The Vienna Code", "The Metternich Code", "The Frankfurt Code"], answer: 0, why: "It is commonly called the Napoleonic Code." },
  { topic: T1, q: "Which of the following was a feature of the Napoleonic Code?", options: ["Privileges based on birth", "Equality before the law", "Feudal dues enforced", "Guild restrictions strengthened"], answer: 1, why: "It abolished privileges based on birth, established equality before law and secured the right to property." },
  { topic: T1, q: "Why did the Napoleonic Code become unpopular in the areas under French control?", options: ["It abolished equality before law", "It introduced censorship, new taxes and forced conscription", "It restored feudalism", "It banned the right to property"], answer: 1, why: "Administrative efficiency came with forced recruitment into French armies, new taxes and censorship." },
  { topic: T2, q: "The word liberalism has its root in the Latin word liber, which means:", options: ["Free", "Law", "King", "Trade"], answer: 0, why: "liber means free; liberalism stood for freedom of the individual and equality before the law." },
  { topic: T2, q: "For the new middle classes, liberalism meant:", options: ["Universal adult suffrage", "Freedom for the individual and equality of all before the law", "Rule by the aristocracy", "Freedom for trade guilds"], answer: 1, why: "Political liberalism demanded government by consent, but NOT universal suffrage." },
  { topic: T2, q: "In the early nineteenth century, the right to vote in liberal thinking was given to:", options: ["Every adult citizen", "Only property-owning men", "Only women", "Only the clergy"], answer: 1, why: "Women and propertyless men were excluded from suffrage all over the world." },
  { topic: T2, q: "Zollverein, formed in 1834, was:", options: ["A customs union in Prussia", "A secret society in Italy", "A congress in Vienna", "A constitution in Frankfurt"], answer: 0, why: "It abolished tariff barriers and reduced the number of currencies from over thirty to two." },
  { topic: T2, q: "The aim of the Zollverein was to:", options: ["Bind the Germans economically into a nation", "Unite Italy politically", "Restore the Bourbon dynasty", "Spread Romantic literature"], answer: 0, why: "It was an economic measure that strengthened wider nationalist sentiments in Germany." },
  { topic: T2, q: "Conservatism after 1815 stood for preserving:", options: ["Revolution and democracy", "Monarchy, the Church, social hierarchies and property", "Free markets only", "Secret societies"], answer: 1, why: "Conservatives accepted change in a limited way but wanted traditional institutions preserved." },
  { topic: T2, q: "The Congress of Vienna of 1815 was hosted by:", options: ["Duke Metternich", "Giuseppe Mazzini", "Otto von Bismarck", "Count Cavour"], answer: 0, why: "Duke Metternich of Austria hosted the Congress of Vienna." },
  { topic: T2, q: "Which territory was given to Prussia on its western frontiers after 1815?", options: ["Sardinia-Piedmont", "Important new territories on the west", "The Kingdom of Two Sicilies", "Greece"], answer: 1, why: "Prussia was given important new territories on its western frontiers." },
  { topic: T3, q: "The Greek struggle for independence from the Ottoman Empire began in:", options: ["1821", "1815", "1830", "1848"], answer: 0, why: "The struggle began in 1821; Greece was recognised as independent by the Treaty of Constantinople in 1832." },
  { topic: T3, q: "Which treaty recognised Greece as an independent nation?", options: ["Treaty of Vienna", "Treaty of Constantinople", "Treaty of Versailles", "Treaty of Lausanne"], answer: 1, why: "The Treaty of Constantinople of 1832 recognised Greece as an independent nation." },
  { topic: T3, q: "Romanticism was essentially a:", options: ["Political movement", "Religious movement", "Cultural movement", "Military movement"], answer: 2, why: "It was a cultural movement that sought to develop a particular form of national sentiment." },
  { topic: T3, q: "Which German philosopher claimed that true German culture was to be discovered among the common people (das volk)?", options: ["Johann Gottfried Herder", "Ernst Renan", "Frederic Sorrieu", "Karol Kurpinski"], answer: 0, why: "Herder said the true spirit of the nation lay in folk songs, folk poetry and folk dances." },
  { topic: T3, q: "Karol Kurpinski used which art form for the Polish national struggle?", options: ["Opera and music", "Oil painting", "Sculpture", "Novel writing"], answer: 0, why: "He celebrated the national struggle through his operas and music, turning folk dances into nationalist symbols." },
  { topic: T3, q: "The 1848 revolution of the liberals in Germany was led by:", options: ["Educated middle classes", "Landed aristocracy", "The clergy", "Peasant armies"], answer: 0, why: "It was led by the educated middle classes demanding a constitutional nation." },
  { topic: T3, q: "The Frankfurt Parliament met in:", options: ["The Church of St Paul", "The Palace of Versailles", "The Vienna Congress Hall", "The University of Berlin"], answer: 0, why: "831 elected representatives met in the Church of St Paul on 18 May 1848." },
  { topic: T3, q: "Who was offered the crown of a united Germany by the Frankfurt Parliament?", options: ["Friedrich Wilhelm IV, King of Prussia", "Kaiser Wilhelm I", "Otto von Bismarck", "Napoleon III"], answer: 0, why: "He rejected the offer and joined other monarchs to oppose the elected assembly." },
  { topic: T3, q: "The Silesian weavers revolted in 1845 against:", options: ["Contractors who supplied them raw material", "The Prussian army", "The Catholic Church", "Foreign rulers of Poland"], answer: 0, why: "They marched to the contractor's mansion and demanded higher wages." },
  { topic: T4, q: "Who was called the architect of German unification?", options: ["Otto von Bismarck", "Giuseppe Mazzini", "Count Cavour", "Giuseppe Garibaldi"], answer: 0, why: "Bismarck, the Chief Minister of Prussia, carried out the unification with the help of the Prussian army and bureaucracy." },
  { topic: T4, q: "Bismarck fought three wars over seven years with:", options: ["Denmark, Austria and France", "Italy, Russia and Spain", "Britain, Russia and Austria", "Greece, Turkey and Egypt"], answer: 0, why: "Denmark (1864), Austria (1866) and France (1870-71)." },
  { topic: T4, q: "In January 1871, the Prussian King William I was proclaimed German Emperor at:", options: ["Versailles", "Berlin", "Vienna", "Frankfurt"], answer: 0, why: "The ceremony was held in the Palace of Versailles." },
  { topic: T4, q: "Who founded the secret society Young Italy?", options: ["Giuseppe Mazzini", "Count Cavour", "Giuseppe Garibaldi", "Victor Emmanuel II"], answer: 0, why: "Born in Genoa in 1807, Mazzini founded Young Italy at Marseilles and Young Europe at Berne." },
  { topic: T4, q: "Metternich described Mazzini as:", options: ["The most dangerous enemy of our social order", "The soul of Italy", "The sword of Italy", "The brain of Italy"], answer: 0, why: "Metternich called him the most dangerous enemy of our social order." },
  { topic: T4, q: "The Chief Minister who led the diplomatic victory in Italian unification was:", options: ["Count Camillo de Cavour", "Giuseppe Mazzini", "Giuseppe Garibaldi", "Duke Metternich"], answer: 0, why: "Cavour, Chief Minister of Sardinia-Piedmont, entered a tactful diplomatic alliance with France and defeated Austria in 1859." },
  { topic: T4, q: "Garibaldi's armed volunteers were known as:", options: ["Red Shirts", "Carbonari", "Young Italy", "Black Coats"], answer: 0, why: "In 1860 they marched into South Italy and the Kingdom of Two Sicilies." },
  { topic: T4, q: "The Kingdom of Italy was proclaimed in 1861 with which ruler?", options: ["Victor Emmanuel II", "Napoleon III", "Kaiser Wilhelm I", "Friedrich Wilhelm IV"], answer: 0, why: "Victor Emmanuel II was proclaimed king of united Italy in 1861." },
  { topic: T5, q: "Personification of a country as a female figure is called:", options: ["Allegory", "Romanticism", "Liberalism", "Conservatism"], answer: 0, why: "Allegory = an abstract idea expressed through a person or thing." },
  { topic: T5, q: "The female figure that represents France is:", options: ["Marianne", "Germania", "Liberty", "Athena"], answer: 0, why: "Marianne, with the red cap, the tricolour and the cockade, personifies France." },
  { topic: T5, q: "Germania wears a crown of oak leaves because oak stands for:", options: ["Heroism", "Peace", "Justice", "Wealth"], answer: 0, why: "In German mythology the oak stands for heroism." },
  { topic: T5, q: "The sword that Germania carries signifies:", options: ["Readiness to fight", "Love of peace", "Justice in court", "Freedom from slavery"], answer: 0, why: "The sword meant readiness to fight; the olive branch around it meant a willingness to make peace." },
  { topic: T5, q: "Who painted the first image of Bharat Mata as an ascetic figure?", options: ["Abanindranath Tagore", "Frederic Sorrieu", "Ravi Varma", "Bankim Chandra Chattopadhyay"], answer: 0, why: "Abanindranath Tagore painted her as calm, composed, divine and spiritual." },
  { topic: T6, q: "After 1871, the most serious source of nationalist tension in Europe was:", options: ["The Balkans", "Scandinavia", "The Iberian peninsula", "Ireland"], answer: 0, why: "The Balkans became the most serious source of nationalist tension in Europe after 1871." },
  { topic: T6, q: "The Balkans was a region of geographical and ethnic variation comprising:", options: ["Albania, Bulgaria, Greece, Romania, Serbia and others", "Only Greece and Bulgaria", "Denmark, Austria and France", "Prussia and Piedmont"], answer: 0, why: "The region included Albania, Bosnia, Bulgaria, Croatia, Greece, Macedonia, Montenegro, Romania, Serbia and Slovenia." },
  { topic: T6, q: "Why did the Balkan region become a source of conflict after 1871?", options: ["Big powers wanted control as the Ottoman Empire declined", "It had no natural resources", "It was ruled by France", "It had no ethnic groups"], answer: 0, why: "As the Ottoman Empire disintegrated, Russia, Germany, England and Austro-Hungary competed to control the region." },
  { topic: T6, q: "The Balkan region was called the powder keg of Europe because:", options: ["Rivalry there could explode into a big war", "It produced gunpowder", "It had many volcanoes", "Its people were united"], answer: 0, why: "Intense rivalry made the region a tinderbox that finally ignited the First World War in 1914." },
  { topic: T6, q: "Who created the first print of the series The Dream of Worldwide Democratic and Social Republics?", options: ["Frederic Sorrieu", "Ernst Renan", "Karol Kurpinski", "Giuseppe Mazzini"], answer: 0, why: "French artist Frederic Sorrieu prepared a series of four prints in 1848." },
  { topic: T6, q: "Ernst Renan, in his famous essay, argued that a nation is:", options: ["A soul, a spiritual principle built on shared memories and consent", "A dynasty ruling a territory", "A group speaking one language", "A common religion"], answer: 0, why: "Renan said a nation is not formed by dynasty, language, religion, race or territory alone." },
],

/* ================= HISTORY CHAPTER 2 ================= */
"sst-0-1": [
  { topic: I1, q: "During the First World War, the British army in India introduced:", options: ["Forced recruitment in rural areas", "Free education", "Abolition of taxes", "Trade concessions"], answer: 0, why: "Forced recruitment plus increased taxes and doubling of prices 1913-1918 caused anger." },
  { topic: I1, q: "The influenza epidemic of 1918-19 in India caused how many deaths?", options: ["12 to 13 million", "1 to 2 million", "50 million", "5 lakh"], answer: 0, why: "Between 12 and 13 million people died, deepening the people's distress." },
  { topic: I1, q: "Mahatma Gandhi returned to India from South Africa in:", options: ["January 1915", "January 1919", "March 1920", "January 1930"], answer: 0, why: "He returned in January 1915 and successfully organised satyagraha in Champaran, Kheda and Ahmedabad." },
  { topic: I1, q: "Gandhiji's 1916 satyagraha at Champaran was against:", options: ["The oppressive indigo plantation system", "Mill workers' wages", "Revenue demand in Kheda", "The Rowlatt Act"], answer: 0, why: "Champaran in Bihar: peasants were obliged to grow indigo on part of their land." },
  { topic: I1, q: "The Rowlatt Act of 1919 allowed the government to:", options: ["Detain political prisoners without trial for two years", "Ban all political parties", "Impose a salt tax", "Abolish the zamindari system"], answer: 0, why: "It was passed despite united opposition from Indian members of the Imperial Legislative Council." },
  { topic: I1, q: "Gandhiji called for a nationwide hartal against the Rowlatt Act on:", options: ["6 April 1919", "13 April 1919", "26 January 1930", "12 March 1930"], answer: 0, why: "6 April 1919 was observed as a day of hartal." },
  { topic: I1, q: "The Jallianwala Bagh massacre took place at:", options: ["Amritsar", "Lahore", "Meerut", "Agra"], answer: 0, why: "On 13 April 1919 General Dyer opened fire on a crowd in Amritsar." },
  { topic: I1, q: "The Jallianwala Bagh incident occurred on the day of which festival?", options: ["Baisakhi", "Diwali", "Holi", "Eid"], answer: 0, why: "It was Baisakhi, when villagers had come to the city for the fair." },
  { topic: I1, q: "The Khilafat Committee was formed in Bombay in:", options: ["March 1919", "December 1920", "January 1930", "March 1931"], answer: 0, why: "Young Muslim leaders Shaukat Ali and Muhammad Ali formed the Khilafat Committee in March 1919." },
  { topic: I1, q: "At which session did the Congress adopt the Non-Cooperation programme?", options: ["Nagpur session, December 1920", "Lahore session, 1929", "Calcutta session, 1919", "Karachi session, 1931"], answer: 0, why: "The programme was finally adopted at the Nagpur Congress session in December 1920." },
  { topic: I1, q: "Which book did Mahatma Gandhi write outlining his idea of swaraj?", options: ["Hind Swaraj", "Vande Mataram", "Anandamath", "The Folklore of Southern India"], answer: 0, why: "In Hind Swaraj (1909) Gandhiji declared British rule was established with Indian cooperation." },
  { topic: I2, q: "Baba Ramchandra led the peasant movement in:", options: ["Awadh", "Punjab", "Bengal", "Assam"], answer: 0, why: "In Awadh the peasants demanded a reduction of revenue, abolition of begar and a boycott of oppressive landlords." },
  { topic: I2, q: "The Oudh Kisan Sabha was set up by:", options: ["Jawaharlal Nehru and Baba Ramchandra", "Gandhiji and Sardar Patel", "Alluri Sitaram Raju", "C.R. Das and Motilal Nehru"], answer: 0, why: "It was set up by Jawaharlal Nehru and Baba Ramchandra in October 1920." },
  { topic: I2, q: "Alluri Sitaram Raju led the tribal peasant movement in:", options: ["The Gudem Hills of Andhra Pradesh", "Champaran in Bihar", "Kheda in Gujarat", "The tea gardens of Assam"], answer: 0, why: "In the Gudem Hills of Andhra Pradesh he led a militant guerrilla movement." },
  { topic: I2, q: "Which statement about Alluri Sitaram Raju is INCORRECT?", options: ["He believed in Gandhiji's principle of non-violence", "He claimed to have special powers", "He persuaded people to give up drinking", "He was inspired by the Non-Cooperation Movement"], answer: 0, why: "He was inspired by Gandhiji but did NOT believe in non-violence; he advocated guerrilla warfare. He was captured and executed in 1924." },
  { topic: I2, q: "The Inland Emigration Act of 1859 affected plantation workers because:", options: ["They could not leave the tea gardens without permission", "They were given free land", "They were allowed to travel freely", "They received higher wages"], answer: 0, why: "Under the Act, plantation workers were not permitted to leave the tea gardens without permission." },
  { topic: I2, q: "For plantation workers in Assam, swaraj meant:", options: ["The right to move freely in and out of the confined space", "Higher wages only", "A separate province", "Free education"], answer: 0, why: "For them freedom meant the right to move freely and retain a link with the village from which they had come." },
  { topic: I2, q: "Gandhiji called off the Non-Cooperation Movement in February 1922 because of:", options: ["The Chauri Chaura incident", "His arrest", "The Simon Commission", "The Poona Pact"], answer: 0, why: "At Chauri Chaura (Gorakhpur) a police station was attacked and 22 policemen were burnt." },
  { topic: I2, q: "When Gandhiji was arrested in March 1922 he was sentenced to:", options: ["Six years imprisonment", "Two years imprisonment", "Life imprisonment", "A fine only"], answer: 0, why: "He was tried for sedition, sentenced to six years, but released in February 1924." },
  { topic: I3, q: "The Swaraj Party was formed by:", options: ["C.R. Das and Motilal Nehru", "Gandhiji and Nehru", "Ambedkar and Gandhi", "Subhas Chandra Bose"], answer: 0, why: "C.R. Das and Motilal Nehru formed the Swaraj Party within the Congress to return to council politics." },
  { topic: I3, q: "The Simon Commission was greeted with protests because:", options: ["It had no Indian member", "It banned the Congress", "It imposed a salt tax", "It abolished elections"], answer: 0, why: "The Statutory Commission set up in 1928 had no Indian member." },
  { topic: I3, q: "Purna Swaraj (complete independence) was declared at the Congress session of:", options: ["Lahore, December 1929", "Nagpur, December 1920", "Karachi, 1931", "Calcutta, 1919"], answer: 0, why: "Under Jawaharlal Nehru's presidency the Lahore Congress formalised the demand for Purna Swaraj." },
  { topic: I3, q: "26 January 1930 was celebrated as:", options: ["Independence Day", "Republic Day", "Khilafat Day", "Flag Day"], answer: 0, why: "It was to be observed as Independence Day when people would pledge to struggle for complete independence." },
  { topic: I3, q: "The Dandi March began on:", options: ["12 March 1930 from Sabarmati", "6 April 1930 from Dandi", "5 March 1931", "26 January 1930"], answer: 0, why: "Gandhiji started from Sabarmati with 78 volunteers and reached Dandi on 6 April 1930." },
  { topic: I3, q: "The Dandi March covered a distance of about:", options: ["240 miles", "100 miles", "500 miles", "50 miles"], answer: 0, why: "About 240 miles (roughly 375 km) in 24 days." },
  { topic: I3, q: "The Civil Disobedience Movement was launched with the breaking of:", options: ["The salt law", "The Rowlatt Act", "The Inland Emigration Act", "The Poona Pact"], answer: 0, why: "Salt was chosen because it was consumed by rich and poor alike." },
  { topic: I3, q: "The Gandhi-Irwin Pact was signed on:", options: ["5 March 1931", "26 January 1930", "6 April 1930", "September 1932"], answer: 0, why: "Gandhiji agreed to attend the Second Round Table Conference and the government agreed to release political prisoners." },
  { topic: I3, q: "Dr B.R. Ambedkar organised the Dalits into the Depressed Classes Association in:", options: ["1930", "1920", "1927", "1932"], answer: 0, why: "He formed the association in 1930 and clashed with Gandhiji over separate electorates." },
  { topic: I3, q: "The Poona Pact of September 1932 gave Depressed Classes:", options: ["Reserved seats in provincial and central legislative councils", "Separate electorates", "A separate nation", "Free education only"], answer: 0, why: "They got reserved seats voted by the general electorate; separate electorates were dropped." },
  { topic: I3, q: "Why was Gandhiji opposed to separate electorates for Dalits?", options: ["He believed it would halt their integration into society", "He wanted the British to decide", "He wanted only Ambedkar to contest", "He wanted a longer movement"], answer: 0, why: "Gandhiji fasted unto death against the proposal; Ambedkar finally accepted the Poona Pact." },
  { topic: I4, q: "Who wrote the hymn Vande Mataram?", options: ["Bankim Chandra Chattopadhyay", "Rabindranath Tagore", "Abanindranath Tagore", "Natesa Sastri"], answer: 0, why: "Bankim Chandra Chattopadhyay wrote it in the 1870s as a hymn to the motherland." },
  { topic: I4, q: "The image of Bharat Mata was painted by:", options: ["Abanindranath Tagore", "Ravi Varma", "Natesa Sastri", "Bankim Chandra Chattopadhyay"], answer: 0, why: "Abanindranath Tagore painted her in 1905 as an ascetic figure." },
  { topic: I4, q: "Who collected Tamil folktales and published The Folklore of Southern India?", options: ["Natesa Sastri", "Rabindranath Tagore", "Ravi Varma", "Abanindranath Tagore"], answer: 0, why: "In Madras, Natesa Sastri published a massive four-volume collection." },
  { topic: I4, q: "In 1921, who designed the Swaraj flag?", options: ["Mahatma Gandhi", "Rabindranath Tagore", "Bankim Chandra Chattopadhyay", "Jawaharlal Nehru"], answer: 0, why: "A tricolour (red, green and white) with a spinning wheel at the centre, symbolising self-help." },
  { topic: I4, q: "The first tricolour flag during the Swadeshi movement had how many lotuses?", options: ["Eight", "Three", "Twelve", "One"], answer: 0, why: "The Bengal flag had eight lotuses representing the eight provinces, with a crescent moon." },
  { topic: I4, q: "Nationalism spread when people began to believe that they were all part of:", options: ["The same community sharing a common history and heritage", "Separate princely states", "Different colonial empires", "One religious group only"], answer: 0, why: "Rediscovering India's past, folklore and symbols created a sense of collective belonging." },
],
};
